import { z } from 'zod'

const choice=z.object({publicId:z.string(),text:z.string(),position:z.number()})
const question=z.object({publicId:z.string(),position:z.number(),prompt:z.string(),selectedChoicePublicId:z.string().nullable(),markedForReview:z.boolean(),choices:z.array(choice)})
const attempt=z.object({publicId:z.string(),attemptNumber:z.number().optional(),mode:z.enum(['timed','untimed']).optional(),status:z.string(),createdAt:z.string().optional(),startedAt:z.string().nullable().optional(),deadlineAt:z.string().nullable().optional(),serverNow:z.string().optional()})
const attemptPayload=z.object({attempt,examination:z.object({title:z.string(),slug:z.string(),questionCount:z.number(),passingScore:z.number(),timedDurationMinutes:z.number(),simulationLabel:z.string()}),questions:z.array(question),answeredCount:z.number(),markedForReviewCount:z.number(),totalCount:z.number()})
const resultBreakdown=z.object({slug:z.string(),title:z.string(),position:z.number(),total:z.number(),correct:z.number(),incorrect:z.number(),unanswered:z.number(),percentage:z.number(),status:z.string()})
const result=z.object({examination:z.object({title:z.string(),slug:z.string(),passingScore:z.number(),passingTarget:z.number(),simulationLabel:z.string()}),attempt:z.object({publicId:z.string(),attemptNumber:z.number(),mode:z.enum(['timed','untimed']),status:z.string(),startedAt:z.string().nullable(),deadlineAt:z.string().nullable(),submittedAt:z.string(),durationSeconds:z.number().nullable(),autoSubmitted:z.boolean()}),totalPoints:z.number(),earnedPoints:z.number(),scorePercent:z.number(),passed:z.boolean(),correctCount:z.number(),incorrectCount:z.number(),unansweredCount:z.number(),subjects:z.array(resultBreakdown),topics:z.array(resultBreakdown),strongestSubject:resultBreakdown.nullable(),weakestSubject:resultBreakdown.nullable(),strongestTopic:resultBreakdown.nullable(),weakestTopic:resultBreakdown.nullable(),resultUrl:z.string(),notice:z.string()})
const summary=z.object({examination:z.object({publicId:z.string(),title:z.string(),slug:z.string(),description:z.string(),simulationLabel:z.string(),questionCount:z.number(),passingScore:z.number(),passingTarget:z.number(),timedDurationMinutes:z.number(),maximumAttempts:z.number().nullable(),blueprintVersion:z.number(),sourceUrl:z.string(),status:z.literal('published')}),notice:z.string(),activeAttempt:z.record(z.string(),z.unknown()).nullable(),latestScore:z.number().nullable(),bestScore:z.number().nullable(),attemptCount:z.number(),history:z.array(z.record(z.string(),z.unknown()))})
const response=<T extends z.ZodTypeAny>(data:T)=>z.object({success:z.literal(true),data})
async function call<T extends z.ZodTypeAny>(path:string,schema:T,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('accept','application/json');if(init.body!==undefined)headers.set('content-type','application/json');const res=await fetch(path,{...init,headers});const body:unknown=await res.json();if(!res.ok){const parsed=z.object({error:z.object({message:z.string()})}).safeParse(body);throw new Error(parsed.success?parsed.data.error.message:'Request failed.')}return schema.parse(body)}
export type MockExamSummary=z.infer<typeof summary>
export type MockAttempt=z.infer<typeof attemptPayload>
export type MockResult=z.infer<typeof result>
export type MockQuestion=z.infer<typeof question>
export async function fetchMockSummary(signal?:AbortSignal){return (await call('/api/student/mock-examinations/full-cse-professional-mock-examination',response(summary),{signal})).data}
export async function createMockAttempt(mode:'timed'|'untimed'){return (await call('/api/student/mock-examinations/full-cse-professional-mock-examination/attempts',response(attemptPayload),{method:'POST',body:JSON.stringify({mode})})).data}
export async function fetchMockAttempt(id:string,signal?:AbortSignal){return (await call(`/api/student/mock-exam-attempts/${encodeURIComponent(id)}`,response(z.union([attemptPayload,z.object({attempt,resultAvailable:z.literal(true)})])),{signal})).data}
export async function startMockProper(id:string){return (await call(`/api/student/mock-exam-attempts/${encodeURIComponent(id)}/start`,response(attemptPayload),{method:'POST'})).data}
export async function saveMockChoice(attemptId:string,questionId:string,choiceId:string){await call(`/api/student/mock-exam-attempts/${encodeURIComponent(attemptId)}/answers/${encodeURIComponent(questionId)}`,response(z.object({saved:z.literal(true),answeredCount:z.number(),totalCount:z.number()})),{method:'PUT',body:JSON.stringify({selectedChoicePublicId:choiceId})})}
export async function saveMockReviewFlag(attemptId:string,questionId:string,markedForReview:boolean){await call(`/api/student/mock-exam-attempts/${encodeURIComponent(attemptId)}/review-flags/${encodeURIComponent(questionId)}`,response(z.object({saved:z.literal(true),markedForReview:z.boolean()})),{method:'PUT',body:JSON.stringify({markedForReview})})}
export async function fetchSubmissionReview(id:string){return (await call(`/api/student/mock-exam-attempts/${encodeURIComponent(id)}/submission-review`,response(z.object({attempt,answeredCount:z.number(),unansweredCount:z.number(),markedForReviewCount:z.number(),unansweredQuestionNumbers:z.array(z.number()),markedQuestionNumbers:z.array(z.number()),subjectAllocation:z.array(z.object({title:z.string(),count:z.number()}))})))).data}
export async function submitMock(id:string){return (await call(`/api/student/mock-exam-attempts/${encodeURIComponent(id)}/submit`,response(result),{method:'POST'})).data}
export async function fetchMockResult(id:string,signal?:AbortSignal){return (await call(`/api/student/mock-exam-attempts/${encodeURIComponent(id)}/results`,response(result),{signal})).data}
const review=result.extend({questions:z.array(z.object({publicId:z.string(),position:z.number(),subject:z.object({slug:z.string(),title:z.string()}),topic:z.object({slug:z.string(),title:z.string()}),prompt:z.string(),difficulty:z.string(),markedForReview:z.boolean(),selectedChoice:choice.nullable(),correctChoice:choice,isCorrect:z.boolean(),unanswered:z.boolean(),explanation:z.string().nullable(),source:z.unknown(),parameters:z.unknown(),metadata:z.unknown(),choices:z.array(choice)}))})
export async function fetchMockReview(id:string,signal?:AbortSignal){return (await call(`/api/student/mock-exam-attempts/${encodeURIComponent(id)}/review`,response(review),{signal})).data}
