import { rankingDistractor, selectRankingDistractors } from '../../domain/ordering-ranking/ordering-ranking-distractors'
import { ordinal, rankingNumericValue } from '../../domain/ordering-ranking/ordering-ranking-format'
import { middlePositions, movePosition, oppositeRank, overtake, totalFromTwoRanks, updateQueue } from '../../domain/ordering-ranking/ordering-ranking-math'
import type { RankingScenario } from '../../domain/ordering-ranking/ordering-ranking.types'
import { hasExactlyOneRankingAnswer, hasUniqueRankingChoices, uniqueTotalOrder } from '../../domain/ordering-ranking/ordering-ranking-validation'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const version = 1
const supportedDifficulties = ['easy', 'medium', 'hard'] as const
type Random = ReturnType<typeof createSeededRandom>
const names = ['Ana', 'Ben', 'Carlo', 'Dina', 'Eli', 'Faye'] as const
const d = (text: string | number, mistake: Parameters<typeof rankingDistractor>[1]) => rankingDistractor(String(text), mistake)
function randomFor(seed: string, slug: GeneratorSlug, difficulty: GeneratorDifficulty): Random { return createSeededRandom(`${seed}|${slug}|${version}|${difficulty}`) }

function oppositeScenario(random: Random, difficulty: GeneratorDifficulty): RankingScenario { const total = random.integer(15, difficulty === 'hard' ? 60 : 35); const rank = random.integer(2, total - 2); const correct = oppositeRank(total, rank); const wording = difficulty === 'easy' ? `A book is ${ordinal(rank)} from the left on a shelf of ${total} books.` : `A student has ${rank - 1} people ahead in a queue of ${total}.`; return { prompt: `${wording} What is the rank from the other end?`, correct: String(correct), steps: [`Known rank is ${rank}.`, `Opposite rank = ${total} - ${rank} + 1.`, `The answer is ${correct}.`], signature: `opposite|${total}|${rank}|${difficulty}`, parameters: { total, rank, recomputedCorrect: String(correct) }, distractors: [d(total - rank, 'ranking_omitted_plus_one'), d(rank, 'ranking_reversed_direction'), d(total + rank, 'ranking_added_rank_to_total'), d(rank - 1, 'ranking_treated_before_as_rank'), d(correct + 1, 'ranking_counted_starting_position'), d(correct - 2, 'ranking_updated_wrong_direction')] } }
function totalScenario(random: Random): RankingScenario { const left = random.integer(3, 18); const right = random.integer(3, 18); const correct = totalFromTwoRanks(left, right); return { prompt: `A runner is ${ordinal(left)} from the front and ${ordinal(right)} from the back. How many runners are there?`, correct: String(correct), steps: [`The two ranks describe the same runner.`, `Total = ${left} + ${right} - 1.`, `There are ${correct} runners.`], signature: `total|${left}|${right}`, parameters: { left, right, recomputedCorrect: String(correct) }, distractors: [d(left + right, 'ranking_counted_item_twice'), d(Math.abs(left - right), 'ranking_used_rank_difference'), d(Math.max(left, right), 'ranking_used_one_rank'), d(left + right + 1, 'ranking_added_without_overlap')] } }
function rearrangedScenario(random: Random, difficulty: GeneratorDifficulty): RankingScenario { const total = random.integer(18, 45); const rank = random.integer(7, total - 6); const places = random.integer(2, 5); const overtaking = difficulty !== 'easy'; const correct = overtaking ? overtake(rank, places, total) : movePosition(rank, places, 'right', total); return { prompt: overtaking ? `A runner is ${ordinal(rank)} and overtakes ${places} runners. What is the new rank?` : `A book is ${ordinal(rank)} from the left and moves ${places} places right. What is its new position?`, correct: String(correct), steps: [overtaking ? 'Overtaking improves rank, so subtract.' : 'Moving right increases the left rank.', `${rank} ${overtaking ? '-' : '+'} ${places} = ${correct}.`, `The new rank is ${correct}.`], signature: `move|${total}|${rank}|${places}|${overtaking}`, parameters: { total, rank, places, overtaking, recomputedCorrect: String(correct) }, distractors: [d(overtaking ? rank + places : rank - places, 'ranking_wrong_movement_direction'), d(correct + 1, 'ranking_counted_starting_position'), d(places, 'ranking_confused_rank_with_places'), d(rank, 'ranking_ignored_movement')] } }
function comparativeScenario(random: Random): RankingScenario { const shuffled = random.shuffle(names.slice(0, 5)); const [a, b, c, fourth, fifth] = shuffled as [string, string, string, string, string]; const order = uniqueTotalOrder(shuffled, [{ higher: a, lower: b }, { higher: b, lower: c }, { higher: c, lower: fourth }, { higher: fourth, lower: fifth }]); if (order === null) throw new Error('Ordering chain is not unique.'); return { prompt: `${a} scored higher than ${b}; ${b} scored higher than ${c}; ${c} scored higher than ${fourth}; ${fourth} scored higher than ${fifth}. Who ranked highest?`, correct: a, steps: [`Write the chain ${order.join(' > ')}.`, 'The first item in the complete chain is highest.', `${a} ranked highest.`], signature: `compare|${order.join('|')}`, parameters: { order, recomputedCorrect: a }, distractors: [d(b, 'ranking_selected_second_highest'), d(fifth, 'ranking_reversed_comparison'), d(c, 'ranking_used_incomplete_chain'), d(fourth, 'ranking_ignored_transitivity')] } }
function beforeAfterScenario(random: Random): RankingScenario { const first = random.integer(3, 14); const between = random.integer(2, 5); const correct = first + between + 1; return { prompt: `There are ${between} people between D and E. D is ${ordinal(first)} and E is after D. What is E's position?`, correct: String(correct), steps: [`${between} people between means a difference of ${between + 1}.`, `E is after D, so add: ${first} + ${between + 1}.`, `E is ${ordinal(correct)}.`], signature: `between|${first}|${between}`, parameters: { first, between, recomputedCorrect: String(correct) }, distractors: [d(first + between, 'ranking_confused_between_with_difference'), d(first - between - 1, 'ranking_reversed_before_after'), d(first + 1, 'ranking_treated_as_immediate'), d(between + 1, 'ranking_ignored_direction')] } }
function middleScenario(random: Random, difficulty: GeneratorDifficulty): RankingScenario { const total = difficulty === 'easy' ? random.integer(5, 20) * 2 + 1 : random.integer(5, 20) * 2; const middle = middlePositions(total); const correct = middle.join(' and '); return { prompt: middle.length === 1 ? `What is the middle position in a line of ${total}?` : `Which two positions are central in a line of ${total}?`, correct, steps: [middle.length === 1 ? `For an odd total, use (${total} + 1) / 2.` : `For an even total, use ${total}/2 and ${total}/2 + 1.`, `The middle position${middle.length === 1 ? ' is' : 's are'} ${correct}.`], signature: `middle|${total}`, parameters: { total, recomputedCorrect: correct }, distractors: [d(String(Math.floor(total / 2)), 'ranking_used_half_incorrectly'), d(String(Math.ceil(total / 2) + 1), 'ranking_forgot_middle_person'), d(middle.length === 1 ? `${middle[0]} and ${(middle[0] ?? 1) + 1}` : String(middle[0]), 'ranking_chose_one_even_middle'), d(String(total + 1), 'ranking_doubled_side_without_person')] } }
function multiRankScenario(random: Random): RankingScenario { const p = random.integer(4, 10); const below = random.integer(3, 6); const above = random.integer(1, below - 1); const q = p + below; const correct = q - above; return { prompt: `P is ranked ${p}. Q is ${below} places below P. R is ${above} places above Q. What is R's rank?`, correct: String(correct), steps: [`Q = ${p} + ${below} = ${q}.`, `R = ${q} - ${above} = ${correct}.`, `R is ranked ${correct}.`], signature: `multi-rank|${p}|${below}|${above}`, parameters: { p, q, above, recomputedCorrect: String(correct) }, distractors: [d(q, 'ranking_answered_intermediate_rank'), d(p - below + above, 'ranking_wrong_above_below'), d(q + above, 'ranking_failed_to_combine_clues'), d(p, 'ranking_duplicated_rank')] } }
function queueScenario(random: Random, difficulty: GeneratorDifficulty): RankingScenario { const total = random.integer(20, 40); const rank = random.integer(7, 15); const count = random.integer(2, 5); const kind = difficulty === 'easy' ? 'leave-front' : difficulty === 'medium' ? 'join-ahead' : 'leave-behind'; const result = updateQueue({ total, rankFromFront: rank }, { kind, count }); return { prompt: kind === 'leave-front' ? `A student is ${ordinal(rank)} in a queue of ${total}. ${count} people ahead leave. What is the new front rank?` : kind === 'join-ahead' ? `A student is ${ordinal(rank)} in a queue of ${total}. ${count} people join ahead. What is the new front rank?` : `A student is ${ordinal(rank)} in a queue of ${total}. ${count} people behind leave. What is the new front rank?`, correct: String(result.rankFromFront), steps: [`Update only changes that occur ahead of the named student.`, `${kind === 'leave-front' ? 'Subtract' : kind === 'join-ahead' ? 'Add' : 'People behind do not change the front rank'}.`, `The new rank is ${result.rankFromFront}.`], signature: `queue|${total}|${rank}|${kind}|${count}`, parameters: { total, rank, kind, count, newTotal: result.total, recomputedCorrect: String(result.rankFromFront) }, distractors: [d(rank + count, 'ranking_updated_wrong_direction'), d(rank - count, 'ranking_updated_total_not_rank'), d(result.rankFromFront + 1, 'ranking_counted_named_person'), d(oppositeRank(total, rank), 'ranking_confused_front_back'), d(result.rankFromFront - 1, 'ranking_omitted_plus_one'), d(result.rankFromFront + 2, 'ranking_counted_starting_position')] } }
function buildScenario(slug: GeneratorSlug, seed: string, difficulty: GeneratorDifficulty): RankingScenario { const random = randomFor(seed, slug, difficulty); switch (slug) { case 'left-right-ranking': return oppositeScenario(random, difficulty); case 'total-from-two-ranks': return totalScenario(random); case 'rearranged-position': return rearrangedScenario(random, difficulty); case 'comparative-ordering': return comparativeScenario(random); case 'before-after-order': return beforeAfterScenario(random); case 'middle-position': return middleScenario(random, difficulty); case 'multi-rank-comparison': return multiRankScenario(random); case 'queue-line-ranking': return queueScenario(random, difficulty); case 'mixed-ordering-ranking': { const variants = ['left-right-ranking', 'total-from-two-ranks', 'rearranged-position', 'comparative-ordering', 'before-after-order', 'middle-position', 'multi-rank-comparison', 'queue-line-ranking'] as const; const selected = random.pick(variants); const scenario = buildScenario(selected, `${seed}|mixed`, difficulty); return { ...scenario, signature: `mixed|${selected}|${scenario.signature}`, parameters: { ...scenario.parameters, mixedGenerator: selected } } } default: throw new Error(`Unsupported Ordering and Ranking generator: ${slug}`) } }
function buildQuestion(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const scenario = buildScenario(slug, input.seed, input.difficulty); const distractors = selectRankingDistractors(scenario.correct, scenario.distractors); const choices = randomFor(input.seed, slug, input.difficulty).shuffle([{ text: scenario.correct, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: rankingNumericValue(scenario.correct) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [rankingNumericValue(item.text)] }, qualityScore: 0.9, numericValue: rankingNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: version, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: scenario.parameters, choices, explanation: { title: 'Ordering and Ranking solution', steps: scenario.steps, finalAnswer: scenario.correct }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${input.difficulty}|${scenario.signature}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { try { const raw = question.parameters.recomputedCorrect; const correct = typeof raw === 'string' ? raw : ''; const texts = question.choices.map((choice) => choice.text); const valid = correct.length > 0 && hasUniqueRankingChoices(texts) && hasExactlyOneRankingAnswer(texts, correct) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.find((choice) => choice.isCorrect)?.text === correct && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType !== null && choice.derivation !== null); return { valid, reason: valid ? null : 'Ordering and Ranking validation failed.' } } catch (error) { return { valid: false, reason: error instanceof Error ? error.message : 'Invalid Ordering and Ranking question.' } } }
function make(slug: GeneratorSlug, title: string): QuestionGenerator { return { slug, version, title, supportedDifficulties, generate: (input) => buildQuestion(slug, input), validate } }
export const orderingRankingGenerators = [['left-right-ranking', 'Rank from the Left or Right'], ['total-from-two-ranks', 'Total Persons from Two Ranks'], ['rearranged-position', 'Position After Rearrangement'], ['comparative-ordering', 'Comparative Ordering'], ['before-after-order', 'Before-and-After Relationships'], ['middle-position', 'Middle Position Problems'], ['multi-rank-comparison', 'Comparing Multiple Ranks'], ['queue-line-ranking', 'Queue and Line Problems'], ['mixed-ordering-ranking', 'Mixed Ordering and Ranking Problems']].map(([slug, title]) => make(slug as GeneratorSlug, title ?? 'Ordering and Ranking'))
