import { vocabularyBankV1 } from '../../domain/vocabulary/vocabulary-bank'
import { selectVocabularyDistractors, vocabularyDistractor } from '../../domain/vocabulary/vocabulary-distractors'
import { partOfSpeechLabel, vocabularyNumericValue } from '../../domain/vocabulary/vocabulary-format'
import { hasUniqueAnswer, hasUniqueVisibleChoices } from '../../domain/vocabulary/vocabulary-validation'
import type { VocabularyMistakeType, VocabularyScenario } from '../../domain/vocabulary/vocabulary.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const version = 1
const supportedDifficulties = ['easy', 'medium', 'hard'] as const
const mistake = (text: string, type: VocabularyMistakeType) => ({ text, mistake: type })
const scenario = (prompt: string, correct: string, wrong: readonly (readonly [string, VocabularyMistakeType])[], targetWord: string, signature: string, rule: string): VocabularyScenario => ({ prompt, correct, distractors: wrong.map(([text, type]) => mistake(text, type)), targetWord, signature, explanation: [rule, `The correct answer is “${correct}.”`] })

function rootScenarios(): VocabularyScenario[] {
  return vocabularyBankV1.filter((item) => item.base !== item.word && item.base.length > 2).flatMap((item, index) => [
    scenario(`What is the base word in “${item.word}”?`, item.base, [[item.prefix?.replace('-', '') ?? item.suffix?.replace('-', '') ?? 'word', 'vocabulary_wrong_affix'], [item.word, 'vocabulary_wrong_base'], [item.base.slice(0, Math.max(2, item.base.length - 1)), 'vocabulary_similar_spelling']], item.word, `base|${item.word}`, `Remove a valid prefix or suffix and keep the central form ${item.base}.`),
    scenario(`Which part carries the central meaning of “${item.word}”?`, item.base, [[item.prefix ?? 'prefix', 'vocabulary_wrong_affix'], [item.suffix ?? 'suffix', 'vocabulary_wrong_affix'], [`${item.base}${index + 1}`, 'vocabulary_similar_spelling']], item.word, `central|${item.word}`, `The base ${item.base} carries the central meaning.`),
  ])
}

const prefixMeaning: Record<string, string> = { 're-': 'again', 'mis-': 'incorrectly', 'pre-': 'before', 'under-': 'too little', 'un-': 'not', 'dis-': 'not or opposite', 'inter-': 'between or among' }
function prefixScenarios(): VocabularyScenario[] { return vocabularyBankV1.filter((item) => item.prefix !== null).flatMap((item) => { const meaning = prefixMeaning[item.prefix ?? ''] ?? 'changes the base meaning'; return [scenario(`What does the prefix in “${item.word}” contribute?`, meaning, [['after', 'vocabulary_wrong_affix'], ['completely', 'vocabulary_related_not_equivalent'], [item.definition, 'vocabulary_wrong_base']], item.word, `prefix|${item.word}`, `${item.prefix} contributes the meaning ${meaning}.`), scenario(`Which meaning best matches “${item.word}”?`, item.definition, [[item.denotation === item.definition ? item.base : item.denotation, 'vocabulary_wrong_base'], [`the opposite of ${item.base}`, 'vocabulary_wrong_affix'], [`a person who ${item.base}s`, 'vocabulary_wrong_part_of_speech']], item.word, `prefixed-meaning|${item.word}`, `Combine ${item.prefix} with ${item.base}; the curated meaning is ${item.definition}.`)] }) }

function suffixScenarios(): VocabularyScenario[] { return vocabularyBankV1.filter((item) => item.suffix !== null).flatMap((item) => { const partDistractors = (['noun', 'verb', 'adjective', 'adverb'] as const).filter((part) => part !== item.partOfSpeech).map((part) => [partOfSpeechLabel(part), 'vocabulary_wrong_part_of_speech'] as const); return [scenario(`Which suffix appears in “${item.word}”?`, item.suffix ?? '', [[item.prefix ?? `${item.base.slice(0, 2)}-`, 'vocabulary_wrong_affix'], [`-${item.base.slice(-2)}`, 'vocabulary_similar_spelling'], [item.base, 'vocabulary_wrong_base']], item.word, `suffix|${item.word}`, `${item.word} is built from ${item.base} and ${item.suffix}.`), scenario(`What part of speech is “${item.word}” in: “${item.example}”?`, partOfSpeechLabel(item.partOfSpeech), partDistractors, item.word, `suffix-pos|${item.word}`, `The suffix and sentence role make ${item.word} a ${item.partOfSpeech}.`)] }) }

function familyScenarios(): VocabularyScenario[] { return vocabularyBankV1.filter((item) => item.family.length >= 3).flatMap((item) => item.family.map((form, index) => { const other = item.family.filter((candidate) => candidate.word !== form.word); return scenario(`Which member of the “${item.base}” family is a ${form.partOfSpeech}?`, form.word, [[other[0]?.word ?? item.base, 'vocabulary_wrong_part_of_speech'], [other[1]?.word ?? `${item.base}ly`, 'vocabulary_wrong_part_of_speech'], [`${form.word}ish`, 'vocabulary_similar_spelling']], item.word, `family|${item.base}|${form.partOfSpeech}|${index}`, `The form ${form.word} functions as a ${form.partOfSpeech}.`) })) }

function connotationScenarios(): VocabularyScenario[] { const pairs = [['economical', 'cheap', 'positive'], ['helpful', 'interfering', 'positive'], ['careless', 'relaxed', 'negative'], ['creative', 'unusual', 'positive']] as const; return pairs.flatMap(([word, contrast, tone]) => [scenario(`What connotation does “${word}” usually carry in the sentence from the vocabulary bank?`, tone, [['neutral', 'vocabulary_wrong_connotation'], [tone === 'positive' ? 'negative' : 'positive', 'vocabulary_wrong_connotation'], ['literal definition only', 'vocabulary_related_not_equivalent']], word, `tone|${word}`, `The sentence uses ${word} with a broadly ${tone} association.`), scenario(`Which word gives the more favorable tone?`, tone === 'positive' ? word : contrast, [[tone === 'positive' ? contrast : word, 'vocabulary_wrong_connotation'], ['ordinary', 'vocabulary_related_not_equivalent'], ['unrelated', 'vocabulary_related_not_equivalent']], word, `tone-pair|${word}`, `The pair has related subject matter but ${word} carries the intended ${tone} tone.`)]) }

function multipleScenarios(): VocabularyScenario[] { return vocabularyBankV1.filter((item) => item.senses.length > 1).flatMap((item) => item.senses.map((sense, index) => { const alternate = item.senses[(index + 1) % item.senses.length]; return scenario(`In “${sense.example}” what does “${item.word}” mean?`, sense.meaning, [[alternate?.meaning ?? item.definition, 'vocabulary_alternate_sense'], [item.definition === sense.meaning ? item.denotation : item.definition, 'vocabulary_related_not_equivalent'], [`a person connected with ${item.word}`, 'vocabulary_wrong_part_of_speech']], item.word, `sense|${item.word}|${index}`, `The surrounding words and grammatical role select the sense “${sense.meaning}.”`) })) }

function definitionScenarios(): VocabularyScenario[] { return vocabularyBankV1.map((item, index) => { const first = vocabularyBankV1[(index + 1) % vocabularyBankV1.length]!; const second = vocabularyBankV1[(index + 4) % vocabularyBankV1.length]!; const third = vocabularyBankV1[(index + 9) % vocabularyBankV1.length]!; return scenario(`Which word means “${item.definition}”?`, item.word, [[first.word, 'vocabulary_related_not_equivalent'], [second.word, 'vocabulary_similar_spelling'], [third.word, 'vocabulary_related_not_equivalent']], item.word, `definition|${item.word}`, `The curated learner-friendly definition matches ${item.word}.`) }) }

function confusedScenarios(): VocabularyScenario[] { return vocabularyBankV1.filter((item) => item.confusedWith !== null && vocabularyBankV1.some((candidate) => candidate.word === item.confusedWith)).map((item, index) => { const partner = vocabularyBankV1.find((candidate) => candidate.word === item.confusedWith)!; const spellingDistractor = ['accept', 'except'].find((word) => word !== item.word && word !== partner.word) ?? 'similar word'; return scenario(`Choose the word that correctly completes the meaning: ${item.example.replace(new RegExp(item.word, 'iu'), '_____')}`, item.word, [[partner.word, 'vocabulary_confused_partner'], [spellingDistractor, 'vocabulary_similar_spelling'], [item.base + 'ly', 'vocabulary_wrong_part_of_speech']], item.word, `confused|${item.word}|${index}`, `${item.word} matches both the sentence meaning and its ${item.partOfSpeech} role; ${partner.word} means ${partner.definition}.`) }) }

function scenariosFor(slug: GeneratorSlug): VocabularyScenario[] { switch (slug) { case 'root-word-meaning': return rootScenarios(); case 'prefix-meaning': return prefixScenarios(); case 'suffix-meaning': return suffixScenarios(); case 'word-family-form': return familyScenarios(); case 'denotation-connotation': return connotationScenarios(); case 'multiple-meaning-word': return multipleScenarios(); case 'definition-example-match': return definitionScenarios(); case 'commonly-confused-words': return confusedScenarios(); case 'mixed-vocabulary-word-meaning': return [...rootScenarios(), ...prefixScenarios(), ...suffixScenarios(), ...familyScenarios(), ...connotationScenarios(), ...multipleScenarios(), ...definitionScenarios(), ...confusedScenarios()]; default: throw new Error(`Unsupported vocabulary generator ${slug}.`) } }

function buildQuestion(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|${version}|${input.difficulty}`); const pool = scenariosFor(slug); const selected = random.pick(pool); const wrong = selectVocabularyDistractors(selected.correct, selected.distractors.map((item) => vocabularyDistractor(item.text, item.mistake))); const choices = random.shuffle([{ text: selected.correct, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: vocabularyNumericValue(selected.correct) }, ...wrong.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [vocabularyNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: vocabularyNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: version, difficulty: input.difficulty, seed: input.seed, prompt: selected.prompt, parameters: { targetWord: selected.targetWord, recomputedCorrect: selected.correct, scenarioSignature: selected.signature }, choices, explanation: { title: 'Vocabulary and Word Meaning solution', steps: [...selected.explanation], finalAnswer: selected.correct }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${input.difficulty}|${selected.signature}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const target = question.parameters.targetWord; const correct = question.parameters.recomputedCorrect; const texts = question.choices.map((choice) => choice.text); const valid = typeof target === 'string' && vocabularyBankV1.some((item) => item.word === target) && typeof correct === 'string' && hasUniqueVisibleChoices(texts) && hasUniqueAnswer(texts, correct) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.find((choice) => choice.isCorrect)?.text === correct && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('vocabulary_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Vocabulary question failed bank, answer, or distractor validation.' } }
function make(slug: GeneratorSlug, title: string): QuestionGenerator { return { slug, version, title, supportedDifficulties, generate: (input) => buildQuestion(slug, input), validate } }
export const vocabularyGenerators = [['root-word-meaning', 'Roots and Base Words'], ['prefix-meaning', 'Prefixes and Meaning'], ['suffix-meaning', 'Suffixes and Meaning'], ['word-family-form', 'Word Families and Parts of Speech'], ['denotation-connotation', 'Denotation and Connotation'], ['multiple-meaning-word', 'Multiple-Meaning Words'], ['definition-example-match', 'Definitions and Examples'], ['commonly-confused-words', 'Commonly Confused Words'], ['mixed-vocabulary-word-meaning', 'Mixed Vocabulary and Word Meaning']].map(([slug, title]) => make(slug as GeneratorSlug, title ?? 'Vocabulary and Word Meaning'))
