import type { ParagraphOrganizationEntry, SentenceNode } from './paragraph-organization.types'

export function normalizeParagraphChoice(value: string): string { return value.trim().toLowerCase().replaceAll(/[–—]/gu, '-').replaceAll(/\s+/gu, ' ') }
export function formatOrder(order: readonly SentenceNode['id'][]): string { return order.join('-') }
export function nodeById(entry: ParagraphOrganizationEntry, id: SentenceNode['id']): SentenceNode | null { return entry.nodes.find((item) => item.id === id) ?? null }
export function topicSentenceValid(entry: ParagraphOrganizationEntry): boolean { return nodeById(entry, entry.topicSentenceId)?.role === 'topic' && entry.openingSentenceId === entry.topicSentenceId && entry.correctOrder[0] === entry.topicSentenceId }
export function supportRelationsValid(entry: ParagraphOrganizationEntry): boolean { return entry.nodes.filter((item) => ['support', 'example'].includes(item.role)).every((item) => entry.dependencies.some((edge) => edge.before === entry.topicSentenceId && edge.after === item.id) || entry.correctOrder.indexOf(item.id) > 0) }
export function chronologyValid(entry: ParagraphOrganizationEntry): boolean { return entry.organizationType !== 'chronological' || entry.dependencies.filter((item) => item.relation === 'chronology').length >= 3 }
export function causeEffectValid(entry: ParagraphOrganizationEntry): boolean { if (entry.organizationType !== 'cause_effect') return true; const cause = entry.nodes.find((item) => item.role === 'cause'); const effect = entry.nodes.find((item) => item.role === 'effect'); return cause !== undefined && effect !== undefined && entry.correctOrder.indexOf(cause.id) < entry.correctOrder.indexOf(effect.id) }
export function comparisonPairsValid(entry: ParagraphOrganizationEntry): boolean { return entry.organizationType !== 'comparison_contrast' || entry.nodes.filter((item) => ['comparison', 'contrast'].includes(item.role)).length >= 2 && entry.dependencies.some((item) => item.relation === 'comparison') }
export function hierarchyValid(entry: ParagraphOrganizationEntry): boolean { if (!['general_to_specific', 'specific_to_general'].includes(entry.organizationType)) return true; return entry.organizationType === 'general_to_specific' ? entry.correctOrder[0] === entry.topicSentenceId : nodeById(entry, entry.correctOrder.at(-1)!)?.role === 'closing' }
export function referenceLinksValid(entry: ParagraphOrganizationEntry): boolean { return entry.referenceLinks.every(([antecedent, reference]) => nodeById(entry, reference)?.refersTo === antecedent && entry.correctOrder.indexOf(antecedent) < entry.correctOrder.indexOf(reference)) }
export function transitionLinksValid(entry: ParagraphOrganizationEntry): boolean { return entry.transitionLinks.every(([target, transition]) => nodeById(entry, transition)?.transition !== null && entry.correctOrder.indexOf(target) + 1 === entry.correctOrder.indexOf(transition)) }
export function openingClosingValid(entry: ParagraphOrganizationEntry): boolean { const opening = nodeById(entry, entry.openingSentenceId); const closing = nodeById(entry, entry.closingSentenceId); return opening !== null && closing?.role === 'closing' && opening.refersTo === null && opening.transition === null && entry.correctOrder[0] === opening.id && entry.correctOrder.at(-1) === closing.id }
