import { formatOrder } from './paragraph-organization-rules'
import type { OrganizationType, ParagraphOrganizationEntry, ParagraphSkill, SentenceNode } from './paragraph-organization.types'

type Raw = readonly [string, ParagraphSkill, OrganizationType, ParagraphOrganizationEntry['difficulty'], readonly [string, string, string, string]]
const labelPatterns: Readonly<Record<ParagraphOrganizationEntry['difficulty'], readonly SentenceNode['id'][]>> = { easy: ['B', 'D', 'A', 'C'], medium: ['C', 'A', 'D', 'B'], hard: ['D', 'B', 'C', 'A'] }
const raws: readonly Raw[] = [
  ['topic-counter-easy', 'topic_sentence', 'topic_support', 'easy', ['The service counter follows a clear morning routine.', 'First, the clerk checks the appointment list.', 'The clerk then prepares the required forms.', 'This routine helps transactions begin on time.']],
  ['topic-records-medium', 'topic_sentence', 'topic_support', 'medium', ['Accurate records support efficient office work.', 'Updated files help staff answer requests quickly.', 'Complete entries also prevent repeated checking.', 'For these reasons, careful record keeping benefits everyone.']],
  ['topic-community-hard', 'topic_sentence', 'topic_support', 'hard', ['A community clean-up succeeds through organized teamwork.', 'Coordinators first assign areas to small groups.', 'Each group then collects and sorts the waste.', 'Together, these steps make the project manageable.']],
  ['support-library-easy', 'supporting_detail', 'stepwise', 'easy', ['The school library uses a simple return procedure.', 'A student places returned books on the service cart.', 'The librarian checks each book and updates its record.', 'Finally, the books are returned to their shelves.']],
  ['support-notice-medium', 'supporting_detail', 'topic_support', 'medium', ['An effective office notice gives readers essential information.', 'It states the activity and its purpose.', 'It also gives the date, time, and location.', 'These details help employees prepare correctly.']],
  ['support-map-hard', 'supporting_detail', 'stepwise', 'hard', ['The information desk explains the building by area.', 'The ground floor contains reception and payment counters.', 'The second floor contains records and permit offices.', 'This floor-by-floor order helps visitors find services.']],
  ['chron-application-easy', 'chronological', 'chronological', 'easy', ['First, the applicant completes the form.', 'Next, the clerk checks the documents.', 'Then, the applicant pays the required fee.', 'Finally, the application is submitted for processing.']],
  ['chron-meeting-medium', 'chronological', 'chronological', 'medium', ['Before the meeting, the secretary distributes the agenda.', 'When the meeting begins, the chair reviews the objectives.', 'After the discussion, members vote on the proposals.', 'Finally, the secretary records the decisions.']],
  ['chron-project-hard', 'chronological', 'chronological', 'hard', ['The project team first surveys the proposed site.', 'Once the survey is complete, it prepares a work plan.', 'After the plan is approved, workers begin construction.', 'The team finally inspects the completed project.']],
  ['cause-rain-easy', 'cause_effect', 'cause_effect', 'easy', ['Heavy rain flooded the road near the office.', 'As a result, buses moved more slowly than usual.', 'Several employees therefore arrived after opening time.', 'For this reason, the morning briefing began later.']],
  ['cause-form-medium', 'cause_effect', 'cause_effect', 'medium', ['Several application forms lacked required signatures.', 'Because the forms were incomplete, clerks could not approve them.', 'The applicants had to return and sign the missing sections.', 'Consequently, processing took an additional day.']],
  ['cause-maintenance-hard', 'cause_effect', 'cause_effect', 'hard', ['The office scheduled regular maintenance for its computers.', 'Technicians found and replaced worn components early.', 'Therefore, unexpected equipment failures decreased.', 'As a result, employees completed more transactions without interruption.']],
  ['compare-counters-easy', 'comparison_contrast', 'comparison_contrast', 'easy', ['Two service counters handle requests in different ways.', 'Counter A accepts walk-in transactions throughout the day.', 'In contrast, Counter B serves visitors by appointment.', 'Both systems help the office manage the number of clients.']],
  ['compare-travel-medium', 'comparison_contrast', 'comparison_contrast', 'medium', ['The bus and train offer different advantages for commuters.', 'The bus reaches more neighborhood stops.', 'However, the train usually avoids road traffic.', 'Both options can be useful depending on a commuter’s route.']],
  ['compare-schedules-hard', 'comparison_contrast', 'comparison_contrast', 'hard', ['The two work schedules divide time differently.', 'The regular schedule uses five equal workdays.', 'By comparison, the compressed schedule uses fewer but longer days.', 'Either schedule requires employees to complete the same weekly duties.']],
  ['general-id-easy', 'general_specific', 'general_to_specific', 'easy', ['Visitors need valid identification for several office transactions.', 'For example, an applicant may present a government-issued card.', 'The card should show a clear name and photograph.', 'This requirement helps staff verify each applicant’s identity.']],
  ['general-training-medium', 'general_specific', 'specific_to_general', 'medium', ['New employees observe experienced staff during the first week.', 'They then practice routine tasks with supervision.', 'Later, they perform the tasks independently.', 'These stages show how training gradually builds confidence.']],
  ['general-safety-hard', 'general_specific', 'general_to_specific', 'hard', ['Workplace safety depends on consistent preventive habits.', 'Employees keep walkways clear and store supplies properly.', 'They also report damaged equipment without delay.', 'These specific habits reduce avoidable accidents.']],
  ['link-documents-easy', 'transition_link', 'transition_link', 'easy', ['Applicants submit an identification card and proof of address.', 'The clerk checks these documents for completeness.', 'This review confirms that the basic requirements are present.', 'Afterward, the clerk records the application.']],
  ['link-online-medium', 'transition_link', 'transition_link', 'medium', ['The office introduced an online appointment system.', 'This system lets visitors choose an available time.', 'However, walk-in assistance remains available for urgent concerns.', 'Together, the two options give visitors practical access to service.']],
  ['link-recycling-hard', 'transition_link', 'transition_link', 'hard', ['The school placed labeled recycling bins in each hallway.', 'Students began separating paper, plastic, and metal.', 'As a result, less reusable material entered the general waste bins.', 'This improvement encouraged the school to expand the program.']],
  ['open-permit-easy', 'opening_closing', 'topic_support', 'easy', ['Applying for a local permit involves several clear steps.', 'The applicant first gathers the listed documents.', 'The service desk then reviews the completed form.', 'Following the steps carefully helps prevent delays.']],
  ['open-commute-medium', 'opening_closing', 'topic_support', 'medium', ['Planning a daily commute can save time and reduce uncertainty.', 'A commuter checks the route and departure schedule.', 'The commuter also prepares an alternative route for delays.', 'Good preparation makes daily travel more predictable.']],
  ['open-inventory-hard', 'opening_closing', 'topic_support', 'hard', ['A regular inventory keeps office supplies available and organized.', 'Staff count the remaining items and compare them with the record.', 'They report shortages before essential materials run out.', 'Thus, accurate inventory work supports uninterrupted service.']],
]

function relationFor(type: OrganizationType): ParagraphOrganizationEntry['dependencies'][number]['relation'] { if (type === 'chronological' || type === 'stepwise') return 'chronology'; if (type === 'cause_effect') return 'cause_effect'; if (type === 'comparison_contrast') return 'comparison'; if (type === 'general_to_specific' || type === 'specific_to_general') return 'hierarchy'; if (type === 'transition_link') return 'transition'; return 'support' }
function roleFor(skill: ParagraphSkill, index: number): SentenceNode['role'] { if (index === 0) return 'topic'; if (index === 3) return 'closing'; if (skill === 'cause_effect') return index === 1 ? 'cause' : 'effect'; if (skill === 'comparison_contrast') return index === 1 ? 'comparison' : 'contrast'; return index === 2 ? 'example' : 'support' }
function make([id, skill, organizationType, difficulty, sentences]: Raw): ParagraphOrganizationEntry {
  const order = labelPatterns[difficulty]
  const logicalNodes = sentences.map((text, index) => { const transition = /^(next|then|finally|once|when|after|as a result|therefore|consequently|for this reason|however|in contrast|by comparison|for example|afterward|thus)\b/iu.exec(text)?.[0] ?? null; const refers = /\b(this|these|they|it|together|either)\b/iu.test(text) && index > 0 ? order[index - 1] ?? null : null; return { id: order[index]!, text, role: roleFor(skill, index), transition, refersTo: refers } satisfies SentenceNode })
  const nodes = [...logicalNodes].sort((left, right) => left.id.localeCompare(right.id))
  const relation = relationFor(organizationType)
  const dependencies = order.slice(0, -1).map((before, index) => ({ before, after: order[index + 1]!, relation }))
  const transitionLinks = logicalNodes.flatMap((node, index) => node.transition !== null && index > 0 ? [[order[index - 1]!, node.id] as const] : [])
  const referenceLinks = logicalNodes.flatMap((node) => node.refersTo === null ? [] : [[node.refersTo, node.id] as const])
  const mode = skill === 'topic_sentence' ? 'topic' : skill === 'opening_closing' ? 'opening_closing' : 'order'
  const sequence = formatOrder(order)
  const correctChoice = mode === 'topic' ? logicalNodes[0]!.text : mode === 'opening_closing' ? `${order[0]} opens; ${order[3]} closes` : sequence
  const reversed = formatOrder([...order].reverse())
  const swapFirst = formatOrder([order[1]!, order[0]!, order[2]!, order[3]!])
  const swapMiddle = formatOrder([order[0]!, order[2]!, order[1]!, order[3]!])
  const mistake = skill === 'chronological' ? 'paragraph_reversed_chronology' : skill === 'cause_effect' ? 'paragraph_effect_before_cause' : skill === 'comparison_contrast' ? 'paragraph_broken_comparison_pair' : skill === 'general_specific' ? 'paragraph_example_before_general' : skill === 'transition_link' ? 'paragraph_transition_separated' : 'paragraph_adjacent_sentences_reversed'
  const distractors: ParagraphOrganizationEntry['distractors'] = mode === 'topic' ? [{ text: logicalNodes[1]!.text, mistakeType: 'paragraph_detail_before_topic' as const }, { text: logicalNodes[2]!.text, mistakeType: 'paragraph_surface_keyword_order' as const }, { text: logicalNodes[3]!.text, mistakeType: 'paragraph_conclusion_before_support' as const }] : mode === 'opening_closing' ? [{ text: `${order[3]} opens; ${order[0]} closes`, mistakeType: 'paragraph_opening_closing_swapped' as const }, { text: `${order[1]} opens; ${order[3]} closes`, mistakeType: 'paragraph_detail_before_topic' as const }, { text: `${order[0]} opens; ${order[2]} closes`, mistakeType: 'paragraph_new_idea_as_closing' as const }] : [{ text: swapFirst, mistakeType: skill === 'cause_effect' ? 'paragraph_effect_before_cause' as const : skill === 'general_specific' ? 'paragraph_example_before_general' as const : 'paragraph_detail_before_topic' as const }, { text: swapMiddle, mistakeType: mistake }, { text: reversed, mistakeType: skill === 'chronological' ? 'paragraph_reversed_chronology' as const : 'paragraph_conclusion_before_support' as const }]
  return { id, skill, questionMode: mode, promptStem: mode === 'topic' ? 'Which sentence best states the main idea and should come first?' : mode === 'opening_closing' ? 'Which labeled pair provides the best opening and closing?' : 'Which labeled sequence creates the most coherent paragraph?', nodes, correctOrder: order, topicSentenceId: order[0]!, openingSentenceId: order[0]!, closingSentenceId: order[3]!, organizationType, dependencies, transitionLinks, referenceLinks, correctChoice, difficulty, distractors, explanationRationale: `The uniquely coherent order is ${sequence}: it introduces the main idea, satisfies every ${relation} link, and ends with a supported conclusion.` }
}

export const paragraphOrganizationBankV1: readonly ParagraphOrganizationEntry[] = raws.map(make)
export function findParagraphOrganizationEntry(id: string): ParagraphOrganizationEntry | null { return paragraphOrganizationBankV1.find((entry) => entry.id === id) ?? null }
