import { findSentenceStructureEntry, sentenceStructureBankV1 } from '../../domain/sentence-structure/sentence-structure-bank'
import { selectStructureDistractors, structureDistractor } from '../../domain/sentence-structure/sentence-structure-distractors'
import { sentenceStructureSkillLabel, structureNumericValue } from '../../domain/sentence-structure/sentence-structure-format'
import { clauseMetadataValid, classifySentenceType, commaSpliceDetected, connectorLogicValid, fragmentDetected, logicalComparisonValid, parallelFormValid, runOnDetected, segmentedErrorValid, structureAnswerMatches } from '../../domain/sentence-structure/sentence-structure-rules'
import { uniqueStructureAnswer, uniqueStructureChoices } from '../../domain/sentence-structure/sentence-structure-validation'
import type { SentenceStructureSkill } from '../../domain/sentence-structure/sentence-structure.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const slugs = ['subject-predicate-clause-identification', 'sentence-type-classification', 'sentence-fragment-detection', 'run-on-comma-splice-detection', 'coordination-subordination-error', 'parallel-structure-error', 'unclear-illogical-sentence', 'sentence-part-error-identification', 'mixed-sentence-structure-errors'] as const satisfies readonly GeneratorSlug[]
const skills = ['parts_clauses', 'sentence_type', 'fragment', 'run_on', 'coordination', 'parallel', 'unclear_logical', 'segmented_error'] as const satisfies readonly SentenceStructureSkill[]
const frames = [(stem: string, sentence: string) => `${stem} "${sentence}"`, (stem: string, sentence: string) => `Analyze the sentence structure. ${stem} "${sentence}"`, (stem: string, sentence: string, skill: string) => `Apply ${skill}. ${stem} "${sentence}"`] as const
function pool(slug: GeneratorSlug, difficulty: GeneratorDifficulty) { const index = slugs.indexOf(slug as (typeof slugs)[number]); const entries = (index === 8 ? sentenceStructureBankV1 : sentenceStructureBankV1.filter((entry) => entry.skill === skills[index])).filter((entry) => entry.difficulty === difficulty); return entries.flatMap((entry) => frames.map((frame, variant) => ({ entry, variant, prompt: frame(entry.promptStem, entry.sentence, sentenceStructureSkillLabel(entry.skill)) }))) }
function build(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`); const scenario = random.pick(pool(slug, input.difficulty)); const entry = scenario.entry; const distractors = selectStructureDistractors(entry.correctChoice, entry.distractors.map((item) => structureDistractor(item.text, item.mistakeType))); const choices = random.shuffle([{ text: entry.correctChoice, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: structureNumericValue(entry.correctChoice) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [structureNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: structureNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: 1, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: { entryId: entry.id, skill: entry.skill, sentenceType: entry.sentenceType, errorType: entry.errorType, clauseCount: entry.clauses.length, recomputedCorrect: entry.correctChoice, scenarioSignature: `${entry.id}|${scenario.variant}` }, choices, explanation: { title: 'Sentence Structure solution', steps: [`The primary rule is ${sentenceStructureSkillLabel(entry.skill)}.`, entry.ruleDetail, `Independent clauses: ${entry.clauses.filter((item) => item.kind === 'independent').length}; dependent clauses: ${entry.clauses.filter((item) => item.kind === 'dependent').length}.`, entry.explanationRationale, `Correct form or classification: "${entry.correctChoice}".`], finalAnswer: entry.correctChoice }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${entry.id}|${scenario.variant}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const id = question.parameters.entryId; const answer = question.parameters.recomputedCorrect; const entry = typeof id === 'string' ? findSentenceStructureEntry(id) : null; const choices = question.choices.map((choice) => choice.text); const special = entry !== null && (entry.errorType !== 'fragment' || fragmentDetected(entry)) && (entry.errorType !== 'fused_sentence' || runOnDetected(entry)) && (entry.errorType !== 'comma_splice' || commaSpliceDetected(entry)); const valid = entry !== null && typeof answer === 'string' && answer === entry.correctChoice && clauseMetadataValid(entry) && special && (['fragment', 'fused_sentence', 'comma_splice'].includes(entry.errorType) || classifySentenceType(entry) === entry.sentenceType) && connectorLogicValid(entry) && parallelFormValid(entry) && logicalComparisonValid(entry) && segmentedErrorValid(entry) && structureAnswerMatches(entry, answer) && uniqueStructureChoices(choices) && uniqueStructureAnswer(choices, answer) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('structure_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Sentence-structure validation failed.' } }
const make = (slug: GeneratorSlug): QuestionGenerator => ({ slug, version: 1, title: slug.replaceAll('-', ' '), supportedDifficulties: ['easy', 'medium', 'hard'], generate: (input) => build(slug, input), validate })
export const sentenceStructureGenerators = slugs.map(make)
