import { entriesForRa6713Category,findRa6713Entry,ra6713BankV1 } from '../../domain/ra-6713/ra-6713.bank'
import { ra6713Distractor,selectRa6713Distractors } from '../../domain/ra-6713/ra-6713.distractors'
import { formatRa6713Reference,ra6713CategoryLabel,ra6713StableNumber } from '../../domain/ra-6713/ra-6713.format'
import { ra6713SourceComplete,rejectsCurrentPersonContent,rejectsExternalLawMisattribution,uniqueRa6713Answer,uniqueVisibleChoices } from '../../domain/ra-6713/ra-6713.rules'
import type { Ra6713Category,Ra6713SourceMetadata } from '../../domain/ra-6713/ra-6713.types'
import { validateRa6713Entry } from '../../domain/ra-6713/ra-6713.validation'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion,GeneratorDifficulty,GeneratorSlug,GeneratorValidationResult,QuestionGenerator } from '../generator.types'
const categoryBySlug={'ra6713-policy-coverage-definitions':'policy_coverage_definitions','ra6713-norms-of-conduct':'norms','ra6713-public-facing-duties':'public_duties','ra6713-saln-disclosure':'saln_disclosure','ra6713-conflict-divestment':'conflict_divestment','ra6713-financial-material-interests':'financial_interests','ra6713-outside-employment-information':'outside_information','ra6713-gifts-favors':'gifts','ra6713-incentives-penalties':'incentives_penalties'} as const satisfies Partial<Record<GeneratorSlug,Ra6713Category>>
const slugs=[...Object.keys(categoryBySlug),'mixed-ra6713-ethics'] as GeneratorSlug[]
const frames=[(concept:string)=>`Which statement accurately describes ${concept} under Republic Act No. 6713?`,(concept:string)=>`Which choice is consistent with the source-verified rule on ${concept}?`,(concept:string)=>`Select the accurate RA 6713 statement about ${concept}.`,(concept:string)=>`Which statement preserves the statutory conditions concerning ${concept}?`]
function pool(slug:GeneratorSlug,difficulty:GeneratorDifficulty){const category=slug==='mixed-ra6713-ethics'?undefined:categoryBySlug[slug as keyof typeof categoryBySlug];const entries=(category===undefined?ra6713BankV1:entriesForRa6713Category(category)).filter((entry)=>entry.difficulty===difficulty);return entries.flatMap((entry)=>frames.map((frame,variant)=>({entry,variant,prompt:frame(entry.concept)})))}
function build(slug:GeneratorSlug,input:{seed:string;difficulty:GeneratorDifficulty}):GeneratedQuestion{const random=createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`);const scenario=random.pick(pool(slug,input.difficulty));const entry=scenario.entry;const distractors=selectRa6713Distractors(entry.paraphrase,entry.distractors.map((item)=>ra6713Distractor(item.text,item.mistakeType)));const choices=random.shuffle([{text:entry.paraphrase,isCorrect:true,distractorType:null,mistakeType:null,derivation:null,qualityScore:1,numericValue:ra6713StableNumber(entry.paraphrase)},...distractors.map((item)=>({text:item.text,isCorrect:false,distractorType:item.mistakeType,mistakeType:item.mistakeType,derivation:{operation:item.mistakeType,inputs:[ra6713StableNumber(item.text)]},qualityScore:item.qualityScore,numericValue:ra6713StableNumber(item.text)}))]);return{generatorSlug:slug,generatorVersion:1,difficulty:input.difficulty,seed:input.seed,prompt:scenario.prompt,parameters:{entryId:entry.id,category:entry.category,section:entry.section,rule:entry.rule,source:{...entry.source},scenarioFacts:[...entry.scenarioFacts],recomputedCorrect:entry.paraphrase,scenarioSignature:`${entry.id}|${scenario.variant}`},choices,explanation:{title:'RA 6713 source-verified solution',steps:[`The tested area is ${ra6713CategoryLabel(entry.category)}.`,entry.paraphrase,`Authoritative source: ${formatRa6713Reference(entry.source)}.`,`Misconception rejected: ${entry.misconception}`,'This educational review is not legal advice or official CSC examination material. The official law and implementing rules control.'],finalAnswer:entry.paraphrase},metadata:{answerKind:'text',unit:null,canonicalSignature:`${slug}|${entry.id}|${scenario.variant}`}}}
function validate(question:GeneratedQuestion):GeneratorValidationResult{const id=question.parameters.entryId;const entry=typeof id==='string'?findRa6713Entry(id):null;const answer=question.parameters.recomputedCorrect;const source=question.parameters.source as Ra6713SourceMetadata|undefined;const choices=question.choices.map((choice)=>choice.text);const valid=entry!==null&&validateRa6713Entry(entry).length===0&&typeof answer==='string'&&source!==undefined&&ra6713SourceComplete(source)&&JSON.stringify(source)===JSON.stringify(entry.source)&&question.parameters.section===entry.section&&question.parameters.rule===entry.rule&&rejectsCurrentPersonContent(`${question.prompt} ${choices.join(' ')}`)&&rejectsExternalLawMisattribution(`${question.prompt} ${choices.join(' ')}`)&&uniqueVisibleChoices(choices)&&uniqueRa6713Answer(choices,answer)&&question.choices.filter((choice)=>choice.isCorrect).length===1&&question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('ra6713_')===true&&choice.derivation!==null)&&question.explanation.steps.some((step)=>step.includes(entry.section)&&(entry.rule===null||step.includes(entry.rule)));return{valid,reason:valid?null:'RA 6713 validation failed.'}}
const make=(slug:GeneratorSlug):QuestionGenerator=>({slug,version:1,title:slug.replaceAll('-',' '),supportedDifficulties:['easy','medium','hard'],generate:(input)=>build(slug,input),validate})
export const ra6713Generators=slugs.map(make)