import { describe, expect, it } from 'vitest'
import { ageProblemsLessonSpecs } from '../scripts/lib/age-problems-teaching-system-content.mjs'
import legacySource from '../scripts/create-and-publish-age-problems-topic.mjs?raw'
import numberSource from '../scripts/lib/number-problems-teaching-system-content.mjs?raw'
import averageSource from '../scripts/lib/average-teaching-system-content.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(ageProblemsLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Age Problems Teaching System v1',()=>{
 it('preserves all twelve authoritative activities, types, order, and durations',()=>{expect(ageProblemsLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
 ['understanding-age-relationships','reading',12],['present-past-and-future-ages','practice',13],['age-difference','practice',11],['sum-of-ages','practice',12],['age-ratios','practice',13],['parent-and-child-problems','practice',14],['sibling-and-group-age-problems','practice',13],['ages-after-several-years','practice',13],['ages-several-years-ago','practice',13],['mixed-age-relationships','practice',15],['mixed-age-problems-practice','practice',16],['age-problems-topic-quiz','quiz',18]])})
 it('uses valid deterministic canonical blocks without illustrated guided teaching',()=>{for(const item of ageProblemsLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('teaches present, future, and past expressions with shared timeline movement',()=>{const intro=lesson('understanding-age-relationships');expect(intro).toContain('present: x');expect(intro).toContain('x+n');expect(intro).toContain('x−n');expect(intro).toContain('time passes equally');expect(lesson('present-past-and-future-ages')).toContain('x+13');expect(lesson('present-past-and-future-ages')).toContain('x−3')})
 it('proves constant difference and changing ratio',()=>{expect(lesson('age-difference')).toContain('52−24=28');const ratios=lesson('age-ratios');expect(ratios).toContain('2:1 becomes 5:3');expect(ratios).toContain('Difference stays; ratio changes.')})
 it('distinguishes older-by from times-as-old and verifies sums and family timelines',()=>{const intro=lesson('understanding-age-relationships');expect(intro).toContain('M=A+8');expect(intro).toContain('M=2A');expect(lesson('sum-of-ages')).toContain('2×5=10');expect(lesson('sum-of-ages')).toContain('3×4=12');expect(lesson('parent-and-child-problems')).toContain('future ages 30 and 60')})
 it('solves future and past ratios correctly and rejects impossible ages',()=>{expect(lesson('ages-after-several-years')).toContain('48 and 24');expect(lesson('ages-after-several-years')).toContain('60=2(30)');expect(lesson('ages-several-years-ago')).toContain('36 and 12');expect(lesson('ages-several-years-ago')).toContain('negative');expect(lesson('mixed-age-relationships')).toContain('future ages 18 and 36')})
 it('uses seven accessible timeline visuals with reasoned memory rules, common mistakes, and CTAs',()=>{const blocks=ageProblemsLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(7);expect(visuals.length).toBeGreaterThanOrEqual(9);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20)}expect(blocks.filter((block)=>block.content.title==='Common mistake')).toHaveLength(11);for(const item of ageProblemsLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
 it('preserves nine generators, fixed practice, quiz, Smart Recovery source ownership, and unrelated manifests',()=>{for(const slug of ['present-age-equations','age-difference','sum-of-ages','age-ratios','parent-child-ages','sibling-group-ages','future-age-problems','past-age-problems','mixed-age-relationships'])expect(legacySource).toContain(`'${slug}'`);expect(legacySource).toContain('validateFixedQuestions(\'Mixed Age Problems Practice\', practice.questions, 8)');expect(legacySource).toContain('validateFixedQuestions(\'Age Problems Topic Quiz\', quiz.questions, 15)');expect(legacySource).toContain('passingScore: 70');expect(numberSource).toContain("slug:'translating-number-statements'");expect(averageSource).toContain("slug:'understanding-average'")})
})