import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'
import { averageLessonBySlug } from '../scripts/lib/average-teaching-system-content.mjs'
import { classifyReviewedAverageDeletion, reviewedAverageLegacyDeletions } from '../scripts/lib/average-reviewed-legacy-deletions.mjs'
import { analyzeTeachingPlan, normalizePublisherPlan } from '../scripts/lib/safe-teaching-release.mjs'

const block=(review:typeof reviewedAverageLegacyDeletions[number])=>({id:review.legacyBlockId,type:review.blockType,position:1,content:structuredClone(review.expectedContent)})
const classify=(review:typeof reviewedAverageLegacyDeletions[number],overrides:Record<string,unknown>={})=>classifyReviewedAverageDeletion({topic:'average',lessonSlug:review.lessonSlug,block:{...block(review),...overrides},canonicalLesson:averageLessonBySlug.get(review.lessonSlug)})

describe('Average reviewed legacy deletion metadata',()=>{
 it('classifies all fourteen exact reviewed blocks as equivalent supersessions',()=>{expect(reviewedAverageLegacyDeletions.map((review)=>review.legacyBlockId)).toEqual([403,404,412,413,428,429,436,437,445,453,461,468,469,477]);for(const review of reviewedAverageLegacyDeletions){const result=classify(review);expect(result.learnerContentAssessment).toBe('superseded-with-equivalent-content');if(result.learnerContentAssessment!=='superseded-with-equivalent-content')throw new Error(`Reviewed block ${review.legacyBlockId} was not classified safe.`);expect(result.replacementEvidence.canonicalBlockIdentifier.length).toBeGreaterThan(0);expect(result.replacementEvidence.conceptFingerprint).toMatch(/^[a-f0-9]{64}$/u);expect(result.reviewedLegacyContentFingerprint).toBe(review.expectedContentFingerprint)}})
 it('fails closed when block 403 identifier or content changes',()=>{const review=reviewedAverageLegacyDeletions[0];expect(classify(review,{content:{...review.expectedContent,title:'Changed mistakes'}})).toEqual({learnerContentAssessment:'requires-human-review'});expect(classify(review,{content:{...review.expectedContent,text:'Changed learner content'}})).toEqual({learnerContentAssessment:'requires-human-review'})})
 it('fails closed when another reviewed block content changes',()=>{const review=reviewedAverageLegacyDeletions.find((item)=>item.legacyBlockId===429)!;expect(classify(review,{content:{text:'Different practice promise'}})).toEqual({learnerContentAssessment:'requires-human-review'})})
 it('keeps unknown Average and unrelated-topic deletions under human review',()=>{const unknown={id:9999,type:'paragraph',content:{text:'Unknown'},position:99};expect(classifyReviewedAverageDeletion({topic:'average',lessonSlug:'understanding-average',block:unknown,canonicalLesson:averageLessonBySlug.get('understanding-average')})).toEqual({learnerContentAssessment:'requires-human-review'});const review=reviewedAverageLegacyDeletions[0];expect(classifyReviewedAverageDeletion({topic:'fractions',lessonSlug:review.lessonSlug,block:block(review),canonicalLesson:averageLessonBySlug.get(review.lessonSlug)})).toEqual({learnerContentAssessment:'requires-human-review'})})
 it('does not approve by block ID alone',()=>{const review=reviewedAverageLegacyDeletions[0];expect(classify(review,{type:'summary',content:{items:['Common mistakes']}})).toEqual({learnerContentAssessment:'requires-human-review'})})
 it('requires the canonical mean-versus-median replacement for block 403',()=>{const review=reviewedAverageLegacyDeletions[0];const canonical=structuredClone(averageLessonBySlug.get('understanding-average')!);canonical.blocks[6]={...canonical.blocks[6],content:{...canonical.blocks[6].content,text:'Generic warning without the reviewed distinction.'}};expect(classifyReviewedAverageDeletion({topic:'average',lessonSlug:review.lessonSlug,block:block(review),canonicalLesson:canonical})).toEqual({learnerContentAssessment:'requires-human-review'})})
 it('binds the deletion fingerprint to the classified current plan',()=>{const plan=reviewedAverageLegacyDeletions.map((review)=>({lessonSlug:review.lessonSlug,blockId:review.legacyBlockId,blockType:review.blockType,identifier:review.expectedIdentifier,...classify(review)}));const fingerprint=createHash('sha256').update(JSON.stringify(plan)).digest('hex');expect(fingerprint).toMatch(/^[a-f0-9]{64}$/u);const changed=structuredClone(plan);changed[0].identifier='Changed';expect(createHash('sha256').update(JSON.stringify(changed)).digest('hex')).not.toBe(fingerprint)})
 it('still blocks unsafe deletions in content release',()=>{const unsafe=normalizePublisherPlan({topicSlug:'average',lessonCount:12,writesRequired:true,totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:1},deletionPlanFingerprint:'fingerprint',deletions:[{learnerContentAssessment:'requires-human-review'}]});expect(analyzeTeachingPlan(unsafe)).toMatchObject({allowed:false,reason:'content_review_required'})})
})