import { describe, expect, it } from 'vitest'
import { averageLessonSpecs } from '../scripts/lib/average-teaching-system-content.mjs'
import averagePublisherSource from '../scripts/create-and-publish-average-topic.mjs?raw'
import ratioContentSource from '../scripts/lib/ratio-proportion-teaching-system-content.mjs?raw'
import decimalsContentSource from '../scripts/lib/decimals-teaching-system-content.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
import type { VisualTeaching } from '../src/shared/visual-teaching.schema'

const lesson=(slug:string)=>JSON.stringify(averageLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Average Teaching System v1',()=>{
 it('preserves all twelve authoritative activities, types, order, and durations',()=>{expect(averageLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
  ['understanding-average','reading',9],['sum-count-and-mean','reading',10],['finding-the-average','practice',11],['finding-a-missing-value','practice',11],['combined-average','practice',12],['weighted-average','practice',12],['average-after-adding-a-value','practice',11],['average-after-removing-a-value','practice',11],['average-age-problems','practice',12],['average-score-and-salary-problems','practice',13],['mixed-average-applications','practice',14],['average-topic-quiz','quiz',18]])})
 it('uses valid deterministic blocks with semantic headings, summaries, and no guided pilot',()=>{for(const item of averageLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('teaches meaning, sum-count derivation, missing values, addition, removal, replacement, and targets',()=>{expect(lesson('understanding-average')).toContain('equal-share value');expect(lesson('sum-count-and-mean')).toContain('75×8=600');expect(lesson('finding-a-missing-value')).toContain('56 − 37 = 19');expect(lesson('average-after-adding-a-value')).toContain('130 ÷ 6 ≈ 21.67');expect(lesson('average-after-removing-a-value')).toContain('90−12+22=100');expect(lesson('average-score-and-salary-problems')).toContain('328−240=88')})
 it('teaches combined, equal-group, weighted, consecutive-range checks, and rate distinctions correctly',()=>{expect(lesson('combined-average')).toContain('1,850÷25=74');expect(lesson('combined-average')).toContain('(80+70)÷2=75');expect(lesson('weighted-average')).toContain('830÷10=83');expect(lesson('finding-the-average')).toContain('between 18 and 25');expect(lesson('finding-the-average')).toContain('(4+16)÷2=10');expect(lesson('finding-the-average')).toContain('requires equal spacing');expect(lesson('mixed-average-applications')).toContain('120÷3=40 km/h');expect(lesson('mixed-average-applications')).toContain('90÷2=45 km/h');expect(lesson('mixed-average-applications')).toContain('65÷5=13 items/hour')})
 it('uses seven accessible visuals with complete explanations and reasoned memory rules',()=>{const blocks=averageLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]) as VisualTeaching[];expect(visuals).toHaveLength(7);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((item)=>item.whatChanged&&item.why&&item.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20)}expect(blocks.filter((block)=>block.content.title==='Common mistake')).toHaveLength(11)})
 it('keeps all eight generators, fixed practice, and quiz academic configuration unchanged',()=>{for(const slug of ['finding-average','missing-value-average','combined-average','weighted-average','average-after-adding','average-after-removing','average-age','average-score-salary'])expect(averagePublisherSource).toContain(`'${slug}'`);expect(averagePublisherSource).toContain('const mixedQuestions = [');expect(averagePublisherSource).toContain('const quizQuestions = [');expect(averagePublisherSource).toContain('passingScore: 70');expect(averagePublisherSource).toContain('A fixed 15-question quiz')})
 it('does not alter other authoritative teaching-system manifests',()=>{expect(ratioContentSource).toContain("slug:'introduction-to-ratios'");expect(decimalsContentSource).toContain("slug:'introduction-to-decimals'")})
})