import { describe, expect, it } from 'vitest'
import { codingNumericValue, normalizeCodingAnswer } from '../src/worker/domain/coding-decoding/coding-decoding-format'
import { applyTransformations, evaluateCodedOperation, formatPositions, invertMap, mapCode, reverseAlphabetWord, reverseTransformations, reverseWord, shiftWord, validateOneToOneMap } from '../src/worker/domain/coding-decoding/coding-decoding-rules'
import { hasExactlyOneCodingAnswer, hasUniqueCodingChoices, isUnambiguousCodingInference } from '../src/worker/domain/coding-decoding/coding-decoding-validation'
import { generateValidatedQuestion, getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty, GeneratorSlug } from '../src/worker/generators/generator.types'

const slugs = ['letter-shift-codes', 'reverse-alphabet-codes', 'letter-position-codes', 'word-substitution-codes', 'symbol-replacement-codes', 'mixed-letter-number-codes', 'infer-coding-rule', 'multi-step-coding-rules', 'mixed-coding-decoding'] as const satisfies readonly GeneratorSlug[]

describe('Coding and Decoding pure utilities', () => {
  it('applies shifts with wraparound and reverse-alphabet mappings exactly', () => { expect(shiftWord('YAZ', 2)).toBe('ACB'); expect(shiftWord('ABC', -2)).toBe('YZA'); expect(reverseAlphabetWord('CAT')).toBe('XZG'); expect(reverseAlphabetWord(reverseAlphabetWord('DOG'))).toBe('DOG') })
  it('formats positions, validates one-to-one substitutions, and reverses mappings', () => { const map = validateOneToOneMap([['CAT', 'MIP'], ['DOG', 'RAV']]); expect(formatPositions('MAP')).toBe('13-1-16'); expect(mapCode('CAT', map)).toBe('MIP'); expect(mapCode('MIP', invertMap(map))).toBe('CAT'); expect(() => validateOneToOneMap([['CAT', 'MIP'], ['DOG', 'MIP']])).toThrow('one-to-one') })
  it('preserves operation order and supports only explicit exact coded operations', () => { const forward = [{ kind: 'reverse-order' as const }, { kind: 'shift' as const, amount: 1 }]; expect(applyTransformations('CAT', forward)).toBe('UBD'); expect(applyTransformations('UBD', reverseTransformations(forward))).toBe('CAT'); expect(reverseWord('CAT')).toBe('TAC'); expect(evaluateCodedOperation(8, '÷', 2)).toBe(4); expect(() => evaluateCodedOperation(7, '÷', 2)).toThrow('exact') })
  it('rejects visible duplicates and ambiguous inference', () => { expect(hasUniqueCodingChoices(['A', 'B', 'C', 'D'])).toBe(true); expect(hasUniqueCodingChoices(['A', 'A', 'C', 'D'])).toBe(false); expect(hasExactlyOneCodingAnswer(['A', 'B', 'C', 'D'], 'C')).toBe(true); expect(isUnambiguousCodingInference([['CAT', 'DBU'], ['DOG', 'EPH']], [{ kind: 'shift', amount: 1 }], [[{ kind: 'shift', amount: -1 }], [{ kind: 'reverse-alphabet' }]])).toBe(true); expect(isUnambiguousCodingInference([['CAT', 'DBU'], ['DOG', 'EPH']], [{ kind: 'shift', amount: 1 }], [[{ kind: 'shift', amount: 1 }, { kind: 'reverse-order' }]])).toBe(true); expect(normalizeCodingAnswer(' dbu ')).toBe('DBU'); expect(codingNumericValue('DBU')).toBe(codingNumericValue(' dbu ')) })
})

describe('Coding and Decoding generator registry', () => {
  it.each(slugs)('registers %s version 1 for all difficulties', (slug) => { const generator = getGenerator(slug, 1); expect(generator).not.toBeNull(); expect(generator?.supportedDifficulties).toEqual(['easy', 'medium', 'hard']) })
  it('stress-validates 1,000 deterministic questions per generator', () => { for (const slug of slugs) { const generator = getGenerator(slug, 1); if (generator === null) throw new Error(`Missing ${slug}`); for (let index = 0; index < 1_000; index += 1) { const difficulty: GeneratorDifficulty = (['easy', 'medium', 'hard'] as const)[index % 3] ?? 'easy'; const input = { seed: `coding-decoding-${slug}-${index}`, difficulty }; const question = generator.generate(input); expect(generator.generate(input)).toEqual(question); const validation = generator.validate(question); if (!validation.valid) throw new Error(`${slug} failed seed ${index}: ${validation.reason ?? 'unknown'}`); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => choice.text)).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType !== null && choice.derivation !== null)).toBe(true); expect(question.prompt).not.toMatch(/undefined|NaN/u) } } }, 120_000)
  it.each(slugs)('produces five unique immutable generated snapshots for %s', (slug) => { const signatures = new Set<string>(); const prompts = new Set<string>(); for (let position = 1; position <= 5; position += 1) { const difficulty: GeneratorDifficulty = position <= 2 ? 'easy' : position <= 4 ? 'medium' : 'hard'; const question = generateValidatedQuestion({ attemptSeed: `coding-attempt-${slug}`, generatorSlug: slug, generatorVersion: 1, difficulty, position, existingSignatures: signatures, existingPrompts: prompts }); signatures.add(question.metadata.canonicalSignature); prompts.add(question.prompt.trim().toLowerCase()) }; expect(signatures.size).toBe(5); expect(prompts.size).toBe(5) })
})
