import { env } from 'cloudflare:workers'
import { describe, expect, it } from 'vitest'
import { app } from '../src/worker'
import { calculateCseReadiness, CSE_READINESS_WEIGHTS, type ReadinessCalculationInput, type ReadinessAssessmentEvidence, type ReadinessSkillEvidence } from '../src/worker/domain/cse-readiness'
import { createVerifiedPasswordStudent } from '../src/worker/services/auth.service'
import type { Bindings } from '../src/worker/types/bindings'

const now = new Date('2026-08-10T00:00:00.000Z')
const subjects = [
  ['verbal-ability', 'Verbal Ability'], ['numerical-ability', 'Numerical Ability'], ['analytical-ability', 'Analytical Ability'], ['general-information', 'General Information'],
] as const
function assessments(score = 80, previous: number | null = null): ReadinessAssessmentEvidence[] { return subjects.map(([subjectSlug, subjectTitle]) => ({ subjectSlug, subjectTitle, assessmentSlug: `${subjectSlug}-subject-assessment`, latestScorePercent: score, previousScorePercent: previous, attemptCount: previous === null ? 1 : 2, latestSubmittedAt: now.toISOString() })) }
function skills(status: ReadinessSkillEvidence['status'], count = 8): ReadinessSkillEvidence[] { return Array.from({ length: count }, (_, index) => ({ slug: `skill-${index}`, title: `Skill ${index + 1}`, subjectSlug: subjects[index % 4]?.[0] ?? 'verbal-ability', status, evidenceCount: 5 })) }
function input(overrides: Partial<ReadinessCalculationInput> = {}): ReadinessCalculationInput { return { mock: null, assessments: [], recentPractice: [], skills: [], totalSkillEvidenceCount: 0, generatedAt: now, ...overrides } }

describe('CSE Readiness formula v1', () => {
  it('returns a deterministic low-evidence new learner state', () => { const first = calculateCseReadiness(input()); const second = calculateCseReadiness(input()); expect(first).toEqual(second); expect(first).toMatchObject({ formulaVersion: 1, score: 0, hasSufficientEvidence: false, confidence: 'low', readinessBand: 'building_foundations' }); expect(first.recommendation.route).toContain('mock-examinations') })
  it('uses the declared 35/30/20/10/5 component weights', () => { expect(CSE_READINESS_WEIGHTS).toEqual({ fullMock: 35, subjectAssessments: 30, skillStrength: 20, recentPractice: 10, improvementConsistency: 5 }); const result = calculateCseReadiness(input({ mock: { latestScorePercent: 80, previousScorePercent: null, bestScorePercent: 100, attemptCount: 2, latestSubmittedAt: now.toISOString() } })); expect(result.components[0]).toMatchObject({ contribution: 29.4, maximum: 35 }) })
  it('does not silently reweight missing subject assessments', () => { const one = assessments(100)[0]; const result = calculateCseReadiness(input({ assessments: one === undefined ? [] : [one] })); expect(result.components.find((item) => item.key === 'subjectAssessments')?.contribution).toBe(10); expect(result.evidence.subjectsAssessed).toBe(1) })
  it('uses only observed classified skills and does not treat unobserved skills as failures', () => { const result = calculateCseReadiness(input({ skills: [...skills('strong', 5), ...skills('not_enough_data', 2)], totalSkillEvidenceCount: 35 })); expect(result.components.find((item) => item.key === 'skillStrength')?.contribution).toBe(20); expect(result.evidence).toMatchObject({ observedSkillCount: 7, classifiedSkillCount: 5 }) })
  it('bounds recent practice contribution and handles low mock with strong practice', () => { const practice = Array.from({ length: 50 }, () => ({ wasCorrect: true, submittedAt: now.toISOString() })); const result = calculateCseReadiness(input({ mock: { latestScorePercent: 40, previousScorePercent: null, bestScorePercent: 40, attemptCount: 1, latestSubmittedAt: now.toISOString() }, recentPractice: practice })); expect(result.components.find((item) => item.key === 'recentPractice')?.contribution).toBe(10); expect(result.components.find((item) => item.key === 'fullMock')?.contribution).toBe(14) })
  it('keeps high mock evidence separate from weak skill evidence', () => { const result = calculateCseReadiness(input({ mock: { latestScorePercent: 100, previousScorePercent: null, bestScorePercent: 100, attemptCount: 1, latestSubmittedAt: now.toISOString() }, skills: skills('needs_more_practice'), totalSkillEvidenceCount: 40 })); expect(result.components.find((item) => item.key === 'fullMock')?.contribution).toBe(35); expect(result.components.find((item) => item.key === 'skillStrength')?.contribution).toBe(8) })
  it('assigns low, moderate, and strong confidence from explicit coverage rules', () => { const mock = { latestScorePercent: 80, previousScorePercent: null, bestScorePercent: 80, attemptCount: 1, latestSubmittedAt: now.toISOString() }; expect(calculateCseReadiness(input({ mock })).confidence).toBe('low'); expect(calculateCseReadiness(input({ mock, assessments: assessments().slice(0, 3), skills: skills('improving'), totalSkillEvidenceCount: 40 })).confidence).toBe('moderate'); expect(calculateCseReadiness(input({ mock, assessments: assessments(), skills: skills('strong'), totalSkillEvidenceCount: 40, recentPractice: Array.from({ length: 30 }, () => ({ wasCorrect: true, submittedAt: now.toISOString() })) })).confidence).toBe('strong') })
  it('returns all four subjects and marks missing evidence without fabricating a percentage', () => { const result = calculateCseReadiness(input({ assessments: assessments(82).slice(0, 1) })); expect(result.subjects).toHaveLength(4); expect(result.subjects.filter((subject) => subject.readinessPercent === null)).toHaveLength(3); expect(result.subjects.find((subject) => subject.slug === 'verbal-ability')).toMatchObject({ readinessPercent: 82, readinessLabel: 'Strong' }) })
  it('uses deterministic recommendation priorities', () => { const mock = { latestScorePercent: 80, previousScorePercent: null, bestScorePercent: 80, attemptCount: 1, latestSubmittedAt: now.toISOString() }; expect(calculateCseReadiness(input()).recommendation.title).toContain('Full Mock'); expect(calculateCseReadiness(input({ mock, assessments: assessments().slice(0, 3) })).recommendation.title).toContain('General Information'); expect(calculateCseReadiness(input({ mock, assessments: assessments(), skills: skills('needs_more_practice'), totalSkillEvidenceCount: 40 })).recommendation.route).toBe('/smart-recovery'); const uneven = assessments(80); if (uneven[0] !== undefined) uneven[0].latestScorePercent = 50; expect(calculateCseReadiness(input({ mock, assessments: uneven, skills: skills('strong', 2), totalSkillEvidenceCount: 10 })).recommendation.title).toContain('Verbal Ability'); expect(calculateCseReadiness(input({ mock: { ...mock, latestScorePercent: 90, bestScorePercent: 90 }, assessments: assessments(90), skills: skills('strong'), totalSkillEvidenceCount: 40, recentPractice: Array.from({ length: 30 }, () => ({ wasCorrect: true, submittedAt: now.toISOString() })) })).recommendation.title).toContain('timed full mock') })
  it('clamps the final score to 0-100 and gives small evidence limited trend credit', () => { const result = calculateCseReadiness(input({ mock: { latestScorePercent: 500, previousScorePercent: 0, bestScorePercent: 500, attemptCount: 2, latestSubmittedAt: now.toISOString() }, assessments: assessments(500, 0), skills: skills('strong'), totalSkillEvidenceCount: 40, recentPractice: Array.from({ length: 50 }, () => ({ wasCorrect: true, submittedAt: now.toISOString() })) })); expect(result.score).toBe(100); const tiny = calculateCseReadiness(input({ mock: { latestScorePercent: 80, previousScorePercent: 80, bestScorePercent: 80, attemptCount: 2, latestSubmittedAt: now.toISOString() } })); expect(tiny.components.find((item) => item.key === 'improvementConsistency')?.contribution).toBeLessThanOrEqual(1.3) })
})

const allowAllRateLimiter = { limit: (): Promise<RateLimitOutcome> => Promise.resolve({ success: true }) }
function bindings(): Bindings { return { DB: env.DB, ENVIRONMENT: 'production', REGISTRATION_MODE: 'open', LOGIN_IP_RATE_LIMITER: allowAllRateLimiter, LOGIN_ACCOUNT_RATE_LIMITER: allowAllRateLimiter, REGISTRATION_RATE_LIMITER: allowAllRateLimiter, ATTEMPT_RATE_LIMITER: allowAllRateLimiter, AUTOSAVE_RATE_LIMITER: allowAllRateLimiter, ADMIN_RATE_LIMITER: allowAllRateLimiter } }
async function register(email: string) {
  const registered = await createVerifiedPasswordStudent(env.DB, {
    email, password: 'SecurePassword123', confirmPassword: 'SecurePassword123',
    firstName: 'Ready', lastName: 'Learner',
  }, { userAgent: 'Readiness test', ipAddress: '192.0.2.50' })
  const cookie = `cse_session=${registered.sessionToken}`
  const user = await env.DB.prepare('SELECT id FROM users WHERE email=?1')
    .bind(email).first<{ id: number }>()
  if (user === null) {
    throw new Error('Readiness test registration failed.')
  }
  await env.DB.prepare('DELETE FROM course_enrollments WHERE user_id=?1')
    .bind(user.id).run()
  return { cookie, userId: user.id }
}
async function enroll(userId: number) { await env.DB.prepare(`INSERT INTO course_enrollments(user_id,course_id,enrollment_status,access_starts_at,enrollment_source) SELECT ?1,id,'active','2000-01-01T00:00:00.000Z','admin' FROM courses WHERE slug='cse-professional'`).bind(userId).run() }

describe('CSE Readiness learner API', () => {
  it('requires authentication, learner role, and active enrollment', async () => { expect((await app.request('/api/student/readiness', undefined, bindings())).status).toBe(401); const learner = await register(`readiness-unenrolled-${crypto.randomUUID()}@example.test`); expect((await app.request('/api/student/readiness', { headers: { cookie: learner.cookie } }, bindings())).status).toBe(403); await env.DB.prepare("UPDATE users SET role='admin' WHERE id=?1").bind(learner.userId).run(); expect((await app.request('/api/student/readiness', { headers: { cookie: learner.cookie } }, bindings())).status).toBe(403) })
  it('returns a bounded learner-owned dashboard-safe payload without answers or internal IDs', async () => { const learner = await register(`readiness-${crypto.randomUUID()}@example.test`); await enroll(learner.userId); const response = await app.request('/api/student/readiness?userId=999999', { headers: { cookie: learner.cookie } }, bindings()); expect(response.status).toBe(200); const body = await response.json<{ data: { formulaVersion: number; score: number; subjects: unknown[]; evidence: { recentPracticeQuestionCount: number }; recommendation: { route: string } } }>(); expect(body.data).toMatchObject({ formulaVersion: 1, score: 0 }); expect(body.data.subjects).toHaveLength(4); expect(body.data.evidence.recentPracticeQuestionCount).toBeLessThanOrEqual(50); expect(body.data.recommendation.route).toContain('mock-examinations'); const serialized = JSON.stringify(body); expect(serialized).not.toMatch(/correctAnswer|selectedAnswer|generatorSeed|userId|internal.*id/iu) })
})
