import { describe, expect, it } from 'vitest'
import { distanceSpeedTimeLessonSpecs } from '../scripts/lib/distance-speed-time-teaching-system-content.mjs'
import legacySource from '../scripts/create-and-publish-distance-speed-time-topic.mjs?raw'
import workRateSource from '../scripts/lib/work-rate-teaching-system-content.mjs?raw'
import ageSource from '../scripts/lib/age-problems-teaching-system-content.mjs?raw'
import numberSource from '../scripts/lib/number-problems-teaching-system-content.mjs?raw'
import averageSource from '../scripts/lib/average-teaching-system-content.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(distanceSpeedTimeLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Distance, Speed and Time Teaching System v1',()=>{
 it('preserves all twelve authoritative activities, types, order, and durations',()=>{expect(distanceSpeedTimeLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
 ['understanding-distance-speed-and-time','reading',12],['finding-distance','practice',10],['finding-speed','practice',10],['finding-time','practice',10],['distance-speed-and-time-unit-conversions','practice',13],['average-speed','practice',13],['relative-speed-in-the-same-direction','practice',12],['relative-speed-in-opposite-directions','practice',12],['meeting-and-overtaking-problems','practice',14],['mixed-travel-problems','practice',15],['mixed-distance-speed-and-time-practice','practice',16],['distance-speed-and-time-topic-quiz','quiz',18]])})
 it('uses valid deterministic canonical blocks without duplicate illustrated teaching',()=>{for(const item of distanceSpeedTimeLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('teaches D=S×T conceptually and verifies distance, speed, and time arithmetic',()=>{const intro=lesson('understanding-distance-speed-and-time');expect(intro).toContain('60+60=120');expect(intro).toContain('D=S×T');expect(intro).toContain('memory tool');expect(lesson('finding-distance')).toContain('75×3=225');expect(lesson('finding-speed')).toContain('180÷3=60');expect(lesson('finding-time')).toContain('240÷80=3');expect(lesson('finding-time')).toContain('1 hour 30 minutes')})
 it('covers minute-hour and speed-unit conversions with compatible units',()=>{const conversions=lesson('distance-speed-and-time-unit-conversions');for(const value of ['15 min=0.25 h','30 min=0.5 h','45 min=0.75 h','90 min=1.5 h','2.5 h=150 min','1 m/s=3.6 km/h','1 km/h=5/18 m/s','72 km/h×5/18=20 m/s'])expect(conversions).toContain(value);expect(conversions).toContain('3600 m=3.6 km')})
 it('distinguishes total-trip, equal-time, and equal-distance average speed',()=>{const average=lesson('average-speed');expect(average).toContain('120÷3=40 km/h, not 45');expect(average).toContain('matching (40+60)÷2 because time weights are equal');expect(average).toContain('2ab/(a+b)');expect(lesson('mixed-distance-speed-and-time-practice')).toContain('240÷5=48 km/h, not 50')})
 it('teaches same/opposite relative speed, head starts, meeting place, and clock time',()=>{const same=lesson('relative-speed-in-the-same-direction');expect(same).toContain('80−60=20');expect(same).toContain('Relative speed=50−50=0');const opposite=lesson('relative-speed-in-opposite-directions');expect(opposite).toContain('60+40=100');expect(opposite).toContain('180 km from A');expect(opposite).toContain('180+120=300');const catchUp=lesson('meeting-and-overtaking-problems');expect(catchUp).toContain('50×2=100');expect(catchUp).toContain('70×5=350');expect(catchUp).toContain('2:00 PM')})
 it('covers multi-stage, stopped-time, delay, and fixed-distance reasoning',()=>{const mixed=lesson('mixed-travel-problems');expect(mixed).toContain('100+180=280');expect(mixed).toContain('280÷5=56');expect(mixed).toContain('180÷4=45');expect(mixed).toContain('60×4=80×T');expect(mixed).toContain('1-hour delay');expect(mixed).toContain('33.33%');expect(mixed).toContain('25%')})
 it('uses eight accessible visual boards with reasoning, memory rules, common mistakes, and CTAs',()=>{const blocks=distanceSpeedTimeLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(8);expect(visuals.length).toBeGreaterThanOrEqual(10);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20);expect(visual.ariaLabel.length).toBeGreaterThan(40)}expect(blocks.filter((block)=>block.content.title==='Common mistake')).toHaveLength(12);for(const item of distanceSpeedTimeLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
 it('preserves generators, fixed practice, quiz, mappings, and unrelated canonical manifests',()=>{for(const slug of ['distance-from-speed-time','speed-from-distance-time','time-from-distance-speed','travel-unit-conversions','average-speed','same-direction-relative-speed','opposite-direction-relative-speed','meeting-and-overtaking','mixed-distance-speed-time'])expect(legacySource).toContain("'"+slug+"'");expect(legacySource).toContain("spec.slug === 'mixed-distance-speed-and-time-practice'");expect(legacySource).toContain("spec.slug === 'distance-speed-and-time-topic-quiz'");expect(legacySource).toContain('passingScore: 70');expect(workRateSource).toContain("slug:'understanding-work-rates'");expect(ageSource).toContain("slug:'understanding-age-relationships'");expect(numberSource).toContain("slug:'translating-number-statements'");expect(averageSource).toContain("slug:'understanding-average'")})
})