import { describe,expect,it } from 'vitest'
import { environmentBankV1 } from '../src/worker/domain/environment-management/environment-management.bank'
import { eiaConceptValid,environmentDomainValid,environmentSourceComplete,institutionRoleValid,lawConceptValid,mitigationAdaptationValid,rejectsActiveControversy,rejectsCurrentPerson,rejectsProjectAdvice,rejectsUnsupportedScientificClaim,rejectsUnverifiedNumber,scenarioSafe,validEnvironmentProvision,wasteCategoryConceptValid } from '../src/worker/domain/environment-management/environment-management.rules'
import type { EnvironmentEntry,EnvironmentSource } from '../src/worker/domain/environment-management/environment-management.types'
import { validateEnvironmentBank,validateEnvironmentEntry } from '../src/worker/domain/environment-management/environment-management.validation'
import { generateValidatedQuestion,getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty,GeneratorSlug } from '../src/worker/generators/generator.types'
const slugs=['environmental-rights-sustainability','clean-air-management','clean-water-management','ecological-solid-waste','toxic-hazardous-substances','biodiversity-wildlife-protected-areas','environmental-impact-assessment','climate-mitigation-adaptation','environmental-institutions-action','mixed-environment-management'] as const satisfies readonly GeneratorSlug[]
const categories=['rights_sustainability','air','water','solid_waste','hazardous','biodiversity','eia','climate','institutions'] as const;const difficulties=['easy','medium','hard'] as const satisfies readonly GeneratorDifficulty[]
describe('source-locked environmental bank',()=>{
 it('requires complete authoritative metadata, legal matching, safe scenarios, and accurate roles',()=>{expect(validateEnvironmentBank(environmentBankV1)).toEqual([]);expect(environmentBankV1).toHaveLength(27);expect(new Set(environmentBankV1.map((entry)=>entry.id)).size).toBe(27);for(const entry of environmentBankV1){expect(environmentSourceComplete(entry.source)).toBe(true);expect(validEnvironmentProvision(entry.source.provisionId)).toBe(true);expect(lawConceptValid(entry)&&environmentDomainValid(entry)&&wasteCategoryConceptValid(entry)&&eiaConceptValid(entry)&&institutionRoleValid(entry)&&mitigationAdaptationValid(entry)).toBe(true);expect(rejectsCurrentPerson(JSON.stringify(entry))&&rejectsActiveControversy(JSON.stringify(entry))&&scenarioSafe(JSON.stringify(entry))&&rejectsProjectAdvice(JSON.stringify(entry))&&rejectsUnverifiedNumber(JSON.stringify(entry))).toBe(true)}})
 it('covers every focused category at every difficulty',()=>{for(const category of categories)for(const difficulty of difficulties)expect(environmentBankV1.some((entry)=>entry.category===category&&entry.difficulty===difficulty)).toBe(true)})
 it('rejects missing sources, invalid citations, current controversies, unsafe handling, project advice, and unverified standards',()=>{const source=environmentBankV1[0]?.source;expect(source).toBeDefined();if(source===undefined)return;expect(environmentSourceComplete({...source,sourceTitle:''})).toBe(false);expect(validEnvironmentProvision('Blog section 1')).toBe(false);expect(rejectsCurrentPerson('An incumbent names a named polluter.')).toBe(false);expect(rejectsActiveControversy('An active environmental controversy.')).toBe(false);expect(scenarioSafe('They mix chemicals and enter restricted site.')).toBe(false);expect(scenarioSafe('They must capture wildlife and evade inspection.')).toBe(false);expect(rejectsProjectAdvice('This project is compliant.')).toBe(false);expect(rejectsUnverifiedNumber('The limit is 25 mg/L.')).toBe(false);expect(rejectsUnsupportedScientificClaim('One weather event proves climate change.')).toBe(false)})
 it('rejects institutional overstatement and law mislabeling',()=>{const base=environmentBankV1.find((entry)=>entry.id==='emb-role') as EnvironmentEntry;const bad={...base,explanation:'EMB is a court.',source:{...base.source,paraphrasedRule:'EMB is a court.'}};expect(institutionRoleValid(bad)).toBe(false);expect(validateEnvironmentEntry(bad)).toContain('emb-role: institution role');expect(lawConceptValid({...base,source:{...base.source,lawId:'RA 9147'}})).toBe(false)})
})
describe('Dynamic Environment Management Generator Engine v1',()=>{
 it('registers all ten generators for every difficulty',()=>{for(const slug of slugs)expect(getGenerator(slug,1)?.supportedDifficulties).toEqual(difficulties)})
 it('generates 1,000 deterministic source-verified safe questions per generator, 10,000 total',()=>{for(const slug of slugs){const generator=getGenerator(slug,1);expect(generator).not.toBeNull();if(generator===null)continue;for(let index=0;index<1_000;index+=1){const difficulty=difficulties[index%difficulties.length];const input={seed:`environment-stress-${slug}-${index}`,difficulty};const question=generator.generate(input);expect(generator.generate(input)).toEqual(question);expect(generator.validate(question)).toEqual({valid:true,reason:null});expect(question.choices).toHaveLength(4);expect(new Set(question.choices.map((choice)=>choice.text.trim().toLowerCase()))).toHaveLength(4);expect(question.choices.filter((choice)=>choice.isCorrect)).toHaveLength(1);expect(question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('env_')===true&&choice.derivation!==null)).toBe(true);expect(environmentSourceComplete(question.parameters.source as EnvironmentSource)).toBe(true)}}},180_000)
 it('creates unique 2/2/1 attempts for all nine focused generators',()=>{for(const slug of slugs.slice(0,9)){const signatures=new Set<string>();const prompts=new Set<string>();const plan:GeneratorDifficulty[]=['easy','easy','medium','medium','hard'];for(const [index,difficulty] of plan.entries()){const question=generateValidatedQuestion({attemptSeed:`practice-${slug}`,generatorSlug:slug,generatorVersion:1,difficulty,position:index+1,existingSignatures:signatures,existingPrompts:prompts,maxRetries:50});signatures.add(question.metadata.canonicalSignature);prompts.add(question.prompt.trim().toLowerCase())}expect(signatures.size).toBe(5);expect(prompts.size).toBe(5)}})
})
