import { describe, expect, it } from 'vitest'
import { paragraphOrganizationBankV1 } from '../src/worker/domain/paragraph-organization/paragraph-organization-bank'
import { causeEffectValid, comparisonPairsValid, chronologyValid, hierarchyValid, openingClosingValid, referenceLinksValid, supportRelationsValid, topicSentenceValid, transitionLinksValid } from '../src/worker/domain/paragraph-organization/paragraph-organization-rules'
import { hasUniqueParagraphOrder, solveParagraphOrders } from '../src/worker/domain/paragraph-organization/paragraph-organization-solver'
import { uniqueParagraphAnswer, uniqueParagraphChoices, validateParagraphOrganizationBank } from '../src/worker/domain/paragraph-organization/paragraph-organization-validation'
import { generateValidatedQuestion, getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty, GeneratorSlug } from '../src/worker/generators/generator.types'

const slugs = ['topic-sentence-identification', 'supporting-detail-order', 'chronological-paragraph-order', 'cause-effect-paragraph-order', 'comparison-contrast-order', 'general-specific-order', 'transition-link-order', 'opening-closing-sentence', 'mixed-paragraph-organization'] as const satisfies readonly GeneratorSlug[]
describe('Paragraph Organization pure utilities', () => {
  it('keeps the 24-entry bank complete and internally consistent', () => { expect(paragraphOrganizationBankV1).toHaveLength(24); expect(validateParagraphOrganizationBank()).toEqual([]); expect(new Set(paragraphOrganizationBankV1.map((entry) => entry.id)).size).toBe(24); expect(new Set(paragraphOrganizationBankV1.map((entry) => entry.skill)).size).toBe(8); for (const skill of new Set(paragraphOrganizationBankV1.map((entry) => entry.skill))) expect(new Set(paragraphOrganizationBankV1.filter((entry) => entry.skill === skill).map((entry) => entry.difficulty))).toEqual(new Set(['easy', 'medium', 'hard'])) })
  it('validates topic, support, opening, closing, and general-specific hierarchy', () => { expect(paragraphOrganizationBankV1.every(topicSentenceValid)).toBe(true); expect(paragraphOrganizationBankV1.every(supportRelationsValid)).toBe(true); expect(paragraphOrganizationBankV1.every(openingClosingValid)).toBe(true); expect(paragraphOrganizationBankV1.every(hierarchyValid)).toBe(true) })
  it('validates chronology, cause/effect, comparison, transitions, and references', () => { expect(paragraphOrganizationBankV1.every(chronologyValid)).toBe(true); expect(paragraphOrganizationBankV1.every(causeEffectValid)).toBe(true); expect(paragraphOrganizationBankV1.every(comparisonPairsValid)).toBe(true); expect(paragraphOrganizationBankV1.every(transitionLinksValid)).toBe(true); expect(paragraphOrganizationBankV1.every(referenceLinksValid)).toBe(true) })
  it('uses bounded permutations to accept unique orders and reject ambiguity', () => { const entry = paragraphOrganizationBankV1[0]; expect(hasUniqueParagraphOrder(entry.nodes, entry.dependencies, entry.correctOrder)).toBe(true); expect(solveParagraphOrders(entry.nodes, entry.dependencies.slice(0, 1)).length).toBeGreaterThan(1); expect(uniqueParagraphChoices(['A-B-C-D', 'A-C-B-D', 'B-A-C-D', 'D-C-B-A'])).toBe(true); expect(uniqueParagraphAnswer(['A-B-C-D', 'A-C-B-D', 'B-A-C-D', 'D-C-B-A'], 'A-B-C-D')).toBe(true) })
})
describe('Paragraph Organization generator registry', () => {
  it.each(slugs)('registers %s version 1 for every difficulty', (slug) => { const generator = getGenerator(slug, 1); expect(generator).not.toBeNull(); expect(generator?.supportedDifficulties).toEqual(['easy', 'medium', 'hard']) })
  it('stress-validates 1,000 deterministic questions per generator (9,000 total)', () => { for (const slug of slugs) { const generator = getGenerator(slug, 1); if (generator === null) throw new Error(`Missing ${slug}`); for (let index = 0; index < 1_000; index += 1) { const difficulty: GeneratorDifficulty = (['easy', 'medium', 'hard'] as const)[index % 3] ?? 'easy'; const input = { seed: `paragraph-organization-${slug}-${index}`, difficulty }; const question = generator.generate(input); expect(generator.generate(input)).toEqual(question); const validation = generator.validate(question); if (!validation.valid) throw new Error(`${slug} seed ${index}: ${validation.reason ?? 'unknown'}`); expect(question.prompt).toMatch(/A\.|B\.|C\.|D\./u); expect(question.prompt).not.toMatch(/undefined|NaN/u); expect(question.prompt).not.toContain('Ã'); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => choice.text.trim().toLowerCase())).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('paragraph_') === true && choice.derivation !== null)).toBe(true); expect(question.explanation.steps.join(' ')).toContain('primary pattern') } } }, 120_000)
  it.each(slugs)('creates five unique immutable snapshots for %s', (slug) => { const signatures = new Set<string>(); const prompts = new Set<string>(); for (let position = 1; position <= 5; position += 1) { const difficulty: GeneratorDifficulty = position <= 2 ? 'easy' : position <= 4 ? 'medium' : 'hard'; const question = generateValidatedQuestion({ attemptSeed: `paragraph-attempt-${slug}`, generatorSlug: slug, generatorVersion: 1, difficulty, position, existingSignatures: signatures, existingPrompts: prompts }); signatures.add(question.metadata.canonicalSignature); prompts.add(question.prompt.trim().toLowerCase()) } expect(signatures.size).toBe(5); expect(prompts.size).toBe(5) })
})
