import { describe,expect,it } from 'vitest'
import { peaceHumanRightsBankV1 } from '../src/worker/domain/peace-human-rights/peace-human-rights.bank'
import { categoryClassificationValid,institutionRoleValid,peaceHumanRightsSourceComplete,rejectsCurrentPersonContent,rejectsPartisanOrActiveDispute,rejectsUnsafeAdvice,rejectsUnsupportedTreatyClaim,scenarioIsSafe,validPeaceHumanRightsProvision } from '../src/worker/domain/peace-human-rights/peace-human-rights.rules'
import type { PeaceHumanRightsEntry,PeaceHumanRightsSource } from '../src/worker/domain/peace-human-rights/peace-human-rights.types'
import { validatePeaceHumanRightsBank,validatePeaceHumanRightsEntry } from '../src/worker/domain/peace-human-rights/peace-human-rights.validation'
import { generateValidatedQuestion,getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty,GeneratorSlug } from '../src/worker/generators/generator.types'
const slugs=['human-dignity-universality','civil-political-rights','economic-social-cultural-rights','equality-nondiscrimination','rights-duties-responsibilities','peace-conflict-nonviolence','conflict-prevention-resolution','peacebuilding-concepts','human-rights-institutions','mixed-peace-human-rights'] as const satisfies readonly GeneratorSlug[]
const categories=['dignity_universality','civil_political','economic_social_cultural','equality_nondiscrimination','rights_responsibilities','peace_conflict_nonviolence','conflict_prevention_resolution','peacebuilding','institutions'] as const
const difficulties=['easy','medium','hard'] as const satisfies readonly GeneratorDifficulty[]
describe('source-locked Peace and Human Rights bank',()=>{
 it('requires complete authoritative metadata, valid classifications, safe scenarios, and accurate institution roles',()=>{expect(validatePeaceHumanRightsBank(peaceHumanRightsBankV1)).toEqual([]);expect(peaceHumanRightsBankV1).toHaveLength(27);expect(new Set(peaceHumanRightsBankV1.map((entry)=>entry.id)).size).toBe(27);for(const entry of peaceHumanRightsBankV1){expect(peaceHumanRightsSourceComplete(entry.source)).toBe(true);expect(validPeaceHumanRightsProvision(entry.source.provisionId)).toBe(true);expect(categoryClassificationValid(entry)).toBe(true);expect(institutionRoleValid(entry)).toBe(true);expect(rejectsCurrentPersonContent(JSON.stringify(entry))).toBe(true);expect(rejectsPartisanOrActiveDispute(JSON.stringify(entry))).toBe(true);expect(scenarioIsSafe(JSON.stringify(entry))).toBe(true);expect(rejectsUnsafeAdvice(JSON.stringify(entry))).toBe(true);expect(rejectsUnsupportedTreatyClaim(JSON.stringify(entry))).toBe(true)}})
 it('covers every focused category at every supported difficulty',()=>{for(const category of categories)for(const difficulty of difficulties)expect(peaceHumanRightsBankV1.some((entry)=>entry.category===category&&entry.difficulty===difficulty)).toBe(true)})
 it('rejects missing sources, invalid provisions, current persons, partisan disputes, graphic content, unsafe advice, and unsupported treaty claims',()=>{const source=peaceHumanRightsBankV1[0]?.source;expect(source).toBeDefined();if(source===undefined)return;expect(peaceHumanRightsSourceComplete({...source,sourceTitle:''})).toBe(false);expect(validPeaceHumanRightsProvision('Blog opinion')).toBe(false);expect(rejectsCurrentPersonContent('An incumbent named official decides the issue.')).toBe(false);expect(rejectsPartisanOrActiveDispute('An active political dispute supports the ruling party.')).toBe(false);expect(scenarioIsSafe('A graphic child victimization account.')).toBe(false);expect(rejectsUnsafeAdvice('They must personally mediate danger.')).toBe(false);expect(rejectsUnsupportedTreatyClaim('Treaty bodies automatically convict people.')).toBe(false)})
 it('rejects CHR adjudication overstatement',()=>{const base=peaceHumanRightsBankV1.find((entry)=>entry.id==='chr-mandate') as PeaceHumanRightsEntry;const changed={...base,explanation:'The CHR convicts people as a criminal court.',source:{...base.source,paraphrasedRule:'The CHR convicts people as a criminal court.'}};expect(institutionRoleValid(changed)).toBe(false);expect(validatePeaceHumanRightsEntry(changed)).toContain('chr-mandate: institution role overstatement')})
})
describe('Dynamic Peace and Human Rights Generator Engine v1',()=>{
 it('registers all ten generators for every difficulty',()=>{for(const slug of slugs)expect(getGenerator(slug,1)?.supportedDifficulties).toEqual(difficulties)})
 it('generates 1,000 deterministic source-verified safe questions per generator, 10,000 total',()=>{for(const slug of slugs){const generator=getGenerator(slug,1);expect(generator).not.toBeNull();if(generator===null)continue;for(let index=0;index<1_000;index+=1){const difficulty=difficulties[index%difficulties.length];const input={seed:`peace-human-rights-stress-${slug}-${index}`,difficulty};const question=generator.generate(input);expect(generator.generate(input)).toEqual(question);expect(generator.validate(question)).toEqual({valid:true,reason:null});expect(question.choices).toHaveLength(4);expect(new Set(question.choices.map((choice)=>choice.text.trim().toLowerCase()))).toHaveLength(4);expect(question.choices.filter((choice)=>choice.isCorrect)).toHaveLength(1);expect(question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('phr_')===true&&choice.derivation!==null)).toBe(true);expect(peaceHumanRightsSourceComplete(question.parameters.source as PeaceHumanRightsSource)).toBe(true);expect(question.explanation.steps.some((step)=>step.includes(String(question.parameters.provisionId))&&step.includes(String(question.parameters.institution)))).toBe(true)}}},180_000)
 it('creates unique 2/2/1 attempts for all nine focused generators',()=>{for(const slug of slugs.slice(0,9)){const signatures=new Set<string>();const prompts=new Set<string>();const plan:GeneratorDifficulty[]=['easy','easy','medium','medium','hard'];for(const [index,difficulty] of plan.entries()){const question=generateValidatedQuestion({attemptSeed:`practice-${slug}`,generatorSlug:slug,generatorVersion:1,difficulty,position:index+1,existingSignatures:signatures,existingPrompts:prompts,maxRetries:50});signatures.add(question.metadata.canonicalSignature);prompts.add(question.prompt.trim().toLowerCase())}expect(signatures.size).toBe(5);expect(prompts.size).toBe(5)}})
})
