import { describe, expect, it } from 'vitest'
import { pronounsModifiersLessonSpecs } from '../scripts/lib/pronouns-modifiers-teaching-system-content.mjs'
import legacySource from '../scripts/pronouns-modifiers-topic-content.mjs?raw'
import generatorSource from '../src/worker/generators/pronouns-modifiers/pronouns-modifiers-generators.ts?raw'
import assessmentSource from '../src/worker/domain/subject-assessment-blueprint.ts?raw'
import recoverySource from '../src/worker/domain/smart-recovery-fixed-question-manifest.ts?raw'
import mockSource from '../src/worker/domain/mock-exam-blueprint.ts?raw'
import previousRegistry from '../scripts/lib/teaching-publisher-registry.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(pronounsModifiersLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Pronouns and Modifiers Teaching System v1',()=>{
  it('preserves the authoritative seventh Verbal topic, lesson order, types, and durations',()=>{expect(legacySource).toContain("topicSlug = 'pronouns-and-modifiers'");expect(pronounsModifiersLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([['understanding-pronouns-and-modifiers','reading',16],['pronoun-reference-and-agreement','practice',17],['subject-and-object-pronouns','practice',16],['possessive-and-reflexive-pronouns','practice',17],['relative-pronouns','practice',17],['adjective-and-adverb-modifiers','practice',17],['comparative-modifiers','practice',17],['misplaced-modifiers','practice',18],['dangling-modifiers','practice',18],['mixed-pronoun-modifier-problems','practice',20],['mixed-pronouns-modifiers-practice','practice',20],['pronouns-and-modifiers-topic-quiz','quiz',25]])})
  it('uses valid deterministic blocks and audited production counts',()=>{expect(pronounsModifiersLessonSpecs.map((item)=>item.blocks.length)).toEqual([12,10,10,10,10,10,10,10,10,10,10,10]);for(const item of pronounsModifiersLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
  it('teaches reference, case, possession, reflexives, and relative-clause roles from first principles',()=>{for(const value of ['antecedent','number and person','one clear reference','Rosa clarified'])expect(lesson('pronoun-reference-and-agreement')).toContain(value);for(const value of ['subject forms','object forms','Remove the other person','sent to me'])expect(lesson('subject-and-object-pronouns')).toContain(value);for(const value of ['Possessive determiners','Theirs','it’s means it is','matching antecedent'])expect(lesson('possessive-and-reflexive-pronouns')).toContain(value);for(const value of ['role inside clause','who prepared','whom the manager called','whose desk'])expect(lesson('relative-pronouns')).toContain(value)})
  it('teaches modifier targets, comparisons, placement, and dangling-actor repair',()=>{for(const value of ['linking verbs','report is accurate','completed the task carefully','hardly'])expect(lesson('adjective-and-adverb-modifiers')).toContain(value);for(const value of ['two → comparative','fewer applicants','less time','Compare like with like'])expect(lesson('comparative-modifiers')).toContain(value);for(const value of ['Only the manager','nearly all the reports','Position is part of meaning'])expect(lesson('misplaced-modifiers')).toContain(value);for(const value of ['comma + stated actor','Several errors cannot review','the employee noticed'])expect(lesson('dangling-modifiers')).toContain(value)})
  it('provides a reusable CSE method, specific wrong-choice reasoning, memory tricks, and unchanged CTAs',()=>{expect(lesson('mixed-pronoun-modifier-problems')).toContain('Target → Function → Form → Position → Meaning');const blocks=pronounsModifiersLessonSpecs.flatMap((item)=>item.blocks);expect(blocks.filter((block)=>String(block.content.title??'').startsWith('Common mistake'))).toHaveLength(12);for(const block of blocks.filter((item)=>String(item.content.title??'').startsWith('Memory trick')))expect(String(block.content.text)).toContain('because');for(const item of pronounsModifiersLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
  it('uses accessible text-first visual boards without color-only meaning',()=>{const visuals=pronounsModifiersLessonSpecs.flatMap((item)=>item.blocks).flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(9);expect(visuals.length).toBeGreaterThanOrEqual(13);for(const visual of visuals){expect(visual.ariaLabel.length).toBeGreaterThan(40);expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20)}})
  it('preserves generators, recovery, assessments, Full Mock, prior systems, and scrolling architecture',()=>{for(const slug of ['pronoun-reference-agreement','pronoun-case','possessive-reflexive-pronoun','relative-pronoun-usage','adjective-adverb-modifier','comparative-modifier','misplaced-modifier','dangling-modifier','mixed-pronouns-modifiers']){expect(legacySource).toContain("'"+slug+"'");expect(generatorSource).toContain("'"+slug+"'");expect(assessmentSource).toContain("'"+slug+"'")};expect(recoverySource).toContain("topicSlug: 'pronouns-and-modifiers'");expect(mockSource).toContain('verbalAbilityBlueprintV1');for(const topic of ['vocabulary-and-word-meaning','synonyms-and-antonyms','context-clues','sentence-completion','grammar-and-correct-usage','subject-verb-agreement'])expect(previousRegistry).toContain(topic)})
})
