import { describe, expect, it } from 'vitest'
import { pronounsModifiersBankV1 } from '../src/worker/domain/pronouns-modifiers/pronouns-modifiers-bank'
import { adjectiveAdverbValid, antecedentRepresented, comparativeFormValid, danglingModifierResolved, modifierTargetValid, misplacedModifierDetected, possessiveFormValid, pronounCaseMatches, pronounModifierAnswerMatches, pronounNumberMatches, pronounPersonMatches, reconstructPronounModifierSentence, reflexiveAntecedentValid, relativePronounValid, sentenceRevisionValid } from '../src/worker/domain/pronouns-modifiers/pronouns-modifiers-rules'
import { uniquePronounModifierAnswer, uniquePronounModifierChoices, validatePronounsModifiersBank } from '../src/worker/domain/pronouns-modifiers/pronouns-modifiers-validation'
import { generateValidatedQuestion, getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty, GeneratorSlug } from '../src/worker/generators/generator.types'

const slugs = ['pronoun-reference-agreement', 'pronoun-case', 'possessive-reflexive-pronoun', 'relative-pronoun-usage', 'adjective-adverb-modifier', 'comparative-modifier', 'misplaced-modifier', 'dangling-modifier', 'mixed-pronouns-modifiers'] as const satisfies readonly GeneratorSlug[]
describe('Pronouns and Modifiers pure utilities', () => {
  it('keeps the 24-entry bank complete and internally consistent', () => { expect(pronounsModifiersBankV1).toHaveLength(24); expect(validatePronounsModifiersBank()).toEqual([]); expect(new Set(pronounsModifiersBankV1.map((entry) => entry.id)).size).toBe(24); expect(new Set(pronounsModifiersBankV1.map((entry) => entry.skill)).size).toBe(8); for (const skill of new Set(pronounsModifiersBankV1.map((entry) => entry.skill))) expect(new Set(pronounsModifiersBankV1.filter((entry) => entry.skill === skill).map((entry) => entry.difficulty))).toEqual(new Set(['easy', 'medium', 'hard'])) })
  it('validates antecedent number, person, case, possessive, and reflexive forms', () => { const reference = pronounsModifiersBankV1.find((entry) => entry.id === 'reference-employees-easy')!; expect(antecedentRepresented(reference)).toBe(true); expect(pronounNumberMatches(reference, 'plural')).toBe(true); expect(pronounPersonMatches(reference, 'third')).toBe(true); const object = pronounsModifiersBankV1.find((entry) => entry.id === 'case-object-medium')!; expect(pronounCaseMatches(object, 'object')).toBe(true); expect(possessiveFormValid(pronounsModifiersBankV1.find((entry) => entry.id === 'possessive-its-medium')!)).toBe(true); expect(reflexiveAntecedentValid(pronounsModifiersBankV1.find((entry) => entry.id === 'reflexive-herself-hard')!)).toBe(true) })
  it('validates relative pronouns, adjective/adverb forms, and comparisons', () => { expect(relativePronounValid(pronounsModifiersBankV1.find((entry) => entry.id === 'relative-whom-medium')!)).toBe(true); expect(adjectiveAdverbValid(pronounsModifiersBankV1.find((entry) => entry.id === 'modifier-degree-hard')!)).toBe(true); expect(comparativeFormValid(pronounsModifiersBankV1.find((entry) => entry.id === 'comparative-fewer-medium')!)).toBe(true) })
  it('validates modifier targets, misplaced and dangling revisions, and unique answers', () => { const misplaced = pronounsModifiersBankV1.find((entry) => entry.id === 'misplaced-form-medium')!; const dangling = pronounsModifiersBankV1.find((entry) => entry.id === 'dangling-reviewing-medium')!; expect(modifierTargetValid(misplaced)).toBe(true); expect(misplacedModifierDetected(misplaced)).toBe(true); expect(danglingModifierResolved(dangling)).toBe(true); expect(reconstructPronounModifierSentence(dangling, dangling.correctChoice)).toBe(dangling.completedSentence); expect(pronounModifierAnswerMatches(dangling, dangling.correctChoice)).toBe(true); expect(pronounsModifiersBankV1.every(sentenceRevisionValid)).toBe(true); expect(uniquePronounModifierChoices(['one', 'two', 'three', 'four'])).toBe(true); expect(uniquePronounModifierAnswer(['one', 'two', 'three', 'four'], 'two')).toBe(true) })
})
describe('Pronouns and Modifiers generator registry', () => {
  it.each(slugs)('registers %s version 1 for every difficulty', (slug) => { const generator = getGenerator(slug, 1); expect(generator).not.toBeNull(); expect(generator?.supportedDifficulties).toEqual(['easy', 'medium', 'hard']) })
  it('stress-validates 1,000 deterministic questions per generator (9,000 total)', () => { for (const slug of slugs) { const generator = getGenerator(slug, 1); if (generator === null) throw new Error(`Missing ${slug}`); for (let index = 0; index < 1_000; index += 1) { const difficulty: GeneratorDifficulty = (['easy', 'medium', 'hard'] as const)[index % 3] ?? 'easy'; const input = { seed: `pronouns-modifiers-${slug}-${index}`, difficulty }; const question = generator.generate(input); expect(generator.generate(input)).toEqual(question); const validation = generator.validate(question); if (!validation.valid) throw new Error(`${slug} seed ${index}: ${validation.reason ?? 'unknown'}`); expect(question.prompt).toContain('____'); expect(question.prompt).not.toMatch(/undefined|NaN|â/iu); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => choice.text.trim().toLowerCase())).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('pronoun_') === true && choice.derivation !== null)).toBe(true); expect(question.explanation.steps.join(' ')).toContain('primary rule') } } }, 120_000)
  it.each(slugs)('creates five unique immutable snapshots for %s', (slug) => { const signatures = new Set<string>(); const prompts = new Set<string>(); for (let position = 1; position <= 5; position += 1) { const difficulty: GeneratorDifficulty = position <= 2 ? 'easy' : position <= 4 ? 'medium' : 'hard'; const question = generateValidatedQuestion({ attemptSeed: `pronouns-attempt-${slug}`, generatorSlug: slug, generatorVersion: 1, difficulty, position, existingSignatures: signatures, existingPrompts: prompts }); signatures.add(question.metadata.canonicalSignature); prompts.add(question.prompt.trim().toLowerCase()) } expect(signatures.size).toBe(5); expect(prompts.size).toBe(5) })
})
