import { describe,expect,it } from 'vitest'
import { blocksFor,cscCollectionSource,fixedQuestion,generatedByLesson,implementingRulesSource,lessonSpecs,mixedQuestions,quizQuestions,statuteSource,subjectSlug,topicDescription,topicSlug,validateQuestions } from '../scripts/ra-6713-topic-content.mjs'
import { getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorSlug } from '../src/worker/generators/generator.types'
import { rollbackStatusChanges } from '../scripts/logical-reasoning-publisher-helpers.mjs'
const currentPerson=/\b(incumbent|current officeholder|candidate|named official|pending complaint|recent controversy)\b/iu
describe('RA 6713 curriculum and publisher contract',()=>{
 it('targets the existing General Information hierarchy and exact topic identity',()=>{expect(subjectSlug).toBe('general-information');expect(topicSlug).toBe('ra-6713-code-of-conduct');expect(topicDescription).toContain('Republic Act No. 6713')})
 it('declares twelve sequential lessons and nine generated practices',()=>{expect(lessonSpecs).toHaveLength(12);expect(lessonSpecs.map((item)=>item.position)).toEqual(Array.from({length:12},(_,index)=>index+1));expect(Object.keys(generatedByLesson)).toHaveLength(9);expect(lessonSpecs[0].lessonType).toBe('reading');expect(lessonSpecs.slice(1,11).every((item)=>item.lessonType==='practice')).toBe(true);expect(lessonSpecs[11].lessonType).toBe('quiz')})
 it('provides substantive source-bearing blocks without raw HTML',()=>{for(const spec of lessonSpecs){const blocks=blocksFor(spec.slug);expect(blocks.length).toBeGreaterThanOrEqual(9);expect(JSON.stringify(blocks)).toMatch(/Section|Rule/u);expect(JSON.stringify(blocks)).not.toMatch(/<\/?[a-z][^>]*>/iu)}expect(blocksFor(lessonSpecs[0].slug).length).toBeGreaterThanOrEqual(10);expect(blocksFor(lessonSpecs[0].slug).length).toBeLessThanOrEqual(14)})
 it('source-locks all 12 practice and 20 quiz questions with unambiguous scoring',()=>{expect(mixedQuestions).toHaveLength(12);expect(quizQuestions).toHaveLength(20);for(const [index,item] of [...mixedQuestions,...quizQuestions].entries()){expect(item.choices).toHaveLength(4);expect(new Set(item.choices.map((choice)=>choice.toLowerCase()))).toHaveLength(4);expect(item.correctIndex).toBe(0);expect(item.explanation).toContain('Section');expect(item.source.url).toBe(statuteSource.url);expect(item.source.provisionId).toBeTruthy();expect(item.source.paraphrasedRule).toBeTruthy();expect(JSON.stringify(item)).not.toMatch(currentPerson);const stored=fixedQuestion(item,index+1,index>=12);expect(stored.choices.filter((choice)=>choice.isCorrect)).toHaveLength(1);expect(stored.choices[0]?.isCorrect).toBe(true)}expect(validateQuestions('practice',mixedQuestions.map((item,index)=>fixedQuestion(item,index+1)),12)).toEqual([]);expect(validateQuestions('quiz',quizQuestions.map((item,index)=>fixedQuestion(item,index+1,true)),20)).toEqual([])})
 it('uses only official statute, implementing-rule, and CSC collection sources',()=>{expect(statuteSource.url).toMatch(/lawphil\.net/);expect(implementingRulesSource.url).toMatch(/csc\.gov\.ph/);expect(cscCollectionSource.url).toMatch(/csc\.gov\.ph/);expect(statuteSource.classification).toBe('primary_statute');expect(implementingRulesSource.classification).toBe('implementing_rules')})
 it('registers all ten version-one generators',()=>{const wanted:GeneratorSlug[]=['ra6713-policy-coverage-definitions','ra6713-norms-of-conduct','ra6713-public-facing-duties','ra6713-saln-disclosure','ra6713-conflict-divestment','ra6713-financial-material-interests','ra6713-outside-employment-information','ra6713-gifts-favors','ra6713-incentives-penalties','mixed-ra6713-ethics'];for(const slug of wanted)expect(getGenerator(slug,1)).not.toBeNull()})
 it('rolls status changes back in reverse order and continues after one rollback error',async()=>{const calls:string[]=[];await rollbackStatusChanges([()=>Promise.resolve().then(()=>{calls.push('first')}),()=>Promise.resolve().then(()=>{calls.push('second');throw new Error('expected')}),()=>Promise.resolve().then(()=>{calls.push('third')})]);expect(calls).toEqual(['third','second','first'])})
})