import { describe,expect,it } from 'vitest'
import { ra6713BankV1 } from '../src/worker/domain/ra-6713/ra-6713.bank'
import { dutyClassificationValid,normClassificationValid,penaltySourceValid,prohibitedActClassificationValid,ra6713SourceComplete,rejectsCurrentPersonContent,rejectsExternalLawMisattribution,validRa6713Reference } from '../src/worker/domain/ra-6713/ra-6713.rules'
import type { Ra6713SourceMetadata } from '../src/worker/domain/ra-6713/ra-6713.types'
import { validateRa6713Bank } from '../src/worker/domain/ra-6713/ra-6713.validation'
import { generateValidatedQuestion,getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty,GeneratorSlug } from '../src/worker/generators/generator.types'
const slugs=['ra6713-policy-coverage-definitions','ra6713-norms-of-conduct','ra6713-public-facing-duties','ra6713-saln-disclosure','ra6713-conflict-divestment','ra6713-financial-material-interests','ra6713-outside-employment-information','ra6713-gifts-favors','ra6713-incentives-penalties','mixed-ra6713-ethics'] as const satisfies readonly GeneratorSlug[]
const difficulties=['easy','medium','hard'] as const satisfies readonly GeneratorDifficulty[]
describe('source-locked RA 6713 bank',()=>{
 it('requires complete official metadata, valid provisions, classifications, and exact penalty verification',()=>{expect(validateRa6713Bank(ra6713BankV1)).toEqual([]);expect(ra6713BankV1).toHaveLength(33);expect(new Set(ra6713BankV1.map((entry)=>entry.id)).size).toBe(33);for(const entry of ra6713BankV1){expect(ra6713SourceComplete(entry.source)).toBe(true);expect(validRa6713Reference(entry.section,entry.rule)).toBe(true);expect(entry.paraphrase).toBe(entry.source.paraphrasedRule);expect(rejectsCurrentPersonContent(JSON.stringify(entry))).toBe(true);expect(rejectsExternalLawMisattribution(JSON.stringify(entry))).toBe(true);expect(normClassificationValid(entry)&&dutyClassificationValid(entry)&&prohibitedActClassificationValid(entry)&&penaltySourceValid(entry)).toBe(true)}})
 it('covers all eight statutory norms by official name',()=>{const names=ra6713BankV1.filter((entry)=>entry.category==='norms').map((entry)=>entry.concept);expect(names).toEqual(expect.arrayContaining(['commitment to public interest','professionalism','justness and sincerity','political neutrality','responsiveness to the public','nationalism and patriotism','commitment to democracy','simple living']))})
 it('rejects missing sources, invalid sections, current-person content, and other-law misattribution',()=>{expect(ra6713SourceComplete({...ra6713BankV1[0].source,section:''})).toBe(false);expect(validRa6713Reference('Section 99',null)).toBe(false);expect(rejectsCurrentPersonContent('An incumbent named official decides the result.')).toBe(false);expect(rejectsExternalLawMisattribution('The RA 3019 penalty is provided by RA 6713.')).toBe(false)})
})
describe('Dynamic RA 6713 Generator Engine v1',()=>{
 it('registers all ten generators for every difficulty',()=>{for(const slug of slugs)expect(getGenerator(slug,1)?.supportedDifficulties).toEqual(difficulties)})
 it('generates 1,000 deterministic source-verified questions per generator, 10,000 total',()=>{for(const slug of slugs){const generator=getGenerator(slug,1);expect(generator).not.toBeNull();if(generator===null)continue;for(let index=0;index<1_000;index+=1){const difficulty=difficulties[index%difficulties.length];const input={seed:`ra6713-stress-${slug}-${index}`,difficulty};const question=generator.generate(input);expect(generator.generate(input)).toEqual(question);expect(generator.validate(question)).toEqual({valid:true,reason:null});expect(question.choices).toHaveLength(4);expect(new Set(question.choices.map((choice)=>choice.text.trim().toLowerCase()))).toHaveLength(4);expect(question.choices.filter((choice)=>choice.isCorrect)).toHaveLength(1);expect(question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('ra6713_')===true&&choice.derivation!==null)).toBe(true);expect(ra6713SourceComplete(question.parameters.source as Ra6713SourceMetadata)).toBe(true);expect(question.explanation.steps.some((step)=>step.includes(String(question.parameters.section)))).toBe(true)}}},180_000)
 it('creates unique 2/2/1 attempts for all nine focused generators',()=>{for(const slug of slugs.slice(0,9)){const signatures=new Set<string>();const prompts=new Set<string>();const plan:GeneratorDifficulty[]=['easy','easy','medium','medium','hard'];const questions=plan.map((difficulty,index)=>{const question=generateValidatedQuestion({attemptSeed:`practice-${slug}`,generatorSlug:slug,generatorVersion:1,difficulty,position:index+1,existingSignatures:signatures,existingPrompts:prompts,maxRetries:50});signatures.add(question.metadata.canonicalSignature);prompts.add(question.prompt.trim().toLowerCase());return question});expect(questions).toHaveLength(5);expect(signatures.size).toBe(5);expect(prompts.size).toBe(5)}})
})