import { describe, expect, it } from 'vitest'
import { blocksFor, fixedQuestion, generatedByLesson, lessonSpecs, mixedQuestions, quizQuestions, subjectSlug, topicDescription, topicSlug, validateQuestions } from '../scripts/reading-comprehension-topic-content.mjs'
import { findUniqueBySlug, rollbackStatusChanges } from '../scripts/logical-reasoning-publisher-helpers.mjs'
import { getGenerator } from '../src/worker/generators/generator.registry'

describe('Reading Comprehension publisher content', () => {
  it('defines the tenth Verbal topic and exactly twelve ordered lessons', () => { expect(subjectSlug).toBe('verbal-ability'); expect(topicSlug).toBe('reading-comprehension'); expect(topicDescription).toBe('A structured course on identifying main ideas, supporting details, sequence, cause and effect, vocabulary in context, inference, tone, purpose, fact and opinion, and conclusions from short passages.'); expect(lessonSpecs).toHaveLength(12); expect(new Set(lessonSpecs.map((item) => item.slug)).size).toBe(12); expect(new Set(lessonSpecs.map((item) => item.position))).toEqual(new Set(Array.from({ length: 12 }, (_, index) => index + 1))); expect(lessonSpecs.map((item) => item.lessonType)).toEqual(['reading', ...Array.from({ length: 10 }, () => 'practice'), 'quiz']) })
  it('provides mobile-safe instructional blocks and nine registered practices', () => { for (const lesson of lessonSpecs) { const blocks = blocksFor(lesson.slug); expect(blocks.length).toBeGreaterThanOrEqual(9); expect(JSON.stringify(blocks)).not.toMatch(/<\/?[a-z][^>]*>/iu); for (const block of blocks) expect(JSON.stringify(block).length).toBeLessThan(1_500) } expect(blocksFor('understanding-reading-comprehension')).toHaveLength(12); expect(Object.keys(generatedByLesson)).toHaveLength(9); expect(new Set(Object.values(generatedByLesson)).size).toBe(9); for (const slug of Object.values(generatedByLesson)) expect(getGenerator(slug as Parameters<typeof getGenerator>[0], 1)).not.toBeNull() })
  it('defines eight fixed and fifteen quiz questions across multiple original passages', () => { const practice = mixedQuestions.map((item, index) => fixedQuestion(item, index + 1)); const quiz = quizQuestions.map((item, index) => fixedQuestion(item, index + 1, true)); expect(practice).toHaveLength(8); expect(quiz).toHaveLength(15); expect(validateQuestions('practice', practice, 8)).toEqual([]); expect(validateQuestions('quiz', quiz, 15)).toEqual([]); expect(new Set(practice.map((item) => item.prompt.split('\n\n')[0])).size).toBeGreaterThanOrEqual(3); expect(new Set(quiz.map((item) => item.prompt.split('\n\n')[0])).size).toBeGreaterThanOrEqual(5); for (const question of [...practice, ...quiz]) { const passageWords = (question.prompt.split('\n\n')[1] ?? '').trim().split(/\s+/u).filter(Boolean).length; expect(passageWords).toBeGreaterThanOrEqual(80); expect(passageWords).toBeLessThanOrEqual(250); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => choice.text.toLowerCase())).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.explanation).toContain('Evidence'); expect(question.explanation).toContain('Distractors model') } })
  it('rejects duplicate topics and rolls status changes back in reverse order', async () => { expect(() => findUniqueBySlug([{ id: 1, slug: topicSlug }, { id: 2, slug: topicSlug }], topicSlug, 'topic')).toThrow('Duplicate'); const order: number[] = []; await rollbackStatusChanges([() => { order.push(1); return Promise.resolve() }, () => { order.push(2); return Promise.resolve() }]); expect(order).toEqual([2, 1]) })
})
