import { describe, expect, it } from 'vitest'
import { findReadingPassage, readingComprehensionBankV1, readingPassagesV1 } from '../src/worker/domain/reading-comprehension/reading-comprehension-bank'
import { causeEffectValid, contextualSenseValid, detailsValid, evidenceMappingValid, factOpinionConclusionValid, inferenceSupportValid, mainIdeaValid, passageLengthValid, passageWordCount, purposeToneValid, sequenceValid } from '../src/worker/domain/reading-comprehension/reading-comprehension-rules'
import { uniqueReadingAnswer, uniqueReadingChoices, validateReadingComprehensionBank } from '../src/worker/domain/reading-comprehension/reading-comprehension-validation'
import { generateValidatedQuestion, getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty, GeneratorSlug } from '../src/worker/generators/generator.types'

const slugs = ['main-idea-comprehension', 'supporting-detail-comprehension', 'sequence-organization-comprehension', 'cause-effect-comprehension', 'vocabulary-in-context-comprehension', 'inference-comprehension', 'author-purpose-tone-comprehension', 'fact-opinion-conclusion-comprehension', 'mixed-reading-comprehension'] as const satisfies readonly GeneratorSlug[]
describe('Reading Comprehension pure utilities', () => {
  it('keeps twelve original passages and 24 skill entries complete', () => { expect(readingPassagesV1).toHaveLength(12); expect(readingComprehensionBankV1).toHaveLength(24); expect(validateReadingComprehensionBank()).toEqual([]); expect(new Set(readingPassagesV1.map((item) => item.id)).size).toBe(12); expect(new Set(readingComprehensionBankV1.map((item) => item.id)).size).toBe(24); expect(new Set(readingComprehensionBankV1.map((item) => item.skill)).size).toBe(8); for (const skill of new Set(readingComprehensionBankV1.map((item) => item.skill))) expect(new Set(readingComprehensionBankV1.filter((item) => item.skill === skill).map((item) => findReadingPassage(item.passageId)?.difficulty))).toEqual(new Set(['easy', 'medium', 'hard'])) })
  it('enforces passage length, coherence metadata, and exact evidence spans', () => { for (const passage of readingPassagesV1) { expect(passageLengthValid(passage), `${passage.id}: ${passageWordCount(passage)} words`).toBe(true); expect(mainIdeaValid(passage)).toBe(true); expect(detailsValid(passage)).toBe(true); expect(sequenceValid(passage)).toBe(true); expect(causeEffectValid(passage)).toBe(true); expect(contextualSenseValid(passage)).toBe(true); expect(inferenceSupportValid(passage)).toBe(true); expect(purposeToneValid(passage)).toBe(true); expect(factOpinionConclusionValid(passage)).toBe(true) } for (const entry of readingComprehensionBankV1) expect(evidenceMappingValid(findReadingPassage(entry.passageId)!, entry)).toBe(true) })
  it('validates contextual sense, inference breadth, purpose, tone, fact, opinion, and conclusion data', () => { const vocab = findReadingPassage('streamline-medium')!; expect(vocab.vocabularyTargets[0]?.sense).toBe('make a process simpler and more efficient'); const inference = findReadingPassage('sustain-hard')!; expect(inference.validInferences).toContain('Convenience affected whether interested participants could attend regularly.'); expect(inference.invalidOvergeneralizations[0]).toContain('guarantee'); const comparison = findReadingPassage('notice-methods-medium')!; expect(comparison.purpose).toBe('compare'); expect(comparison.tone).toBe('objective'); expect(comparison.opinions).toContain('Some employees consider email more convenient') })
  it('requires four unique choices and one supported answer', () => { expect(uniqueReadingChoices(['one', 'two', 'three', 'four'])).toBe(true); expect(uniqueReadingAnswer(['one', 'two', 'three', 'four'], 'two')).toBe(true) })
})
describe('Reading Comprehension generator registry', () => {
  it.each(slugs)('registers %s version 1 for every difficulty', (slug) => { const generator = getGenerator(slug, 1); expect(generator).not.toBeNull(); expect(generator?.supportedDifficulties).toEqual(['easy', 'medium', 'hard']) })
  it('stress-validates 1,000 deterministic questions per generator (9,000 total)', () => { for (const slug of slugs) { const generator = getGenerator(slug, 1); if (generator === null) throw new Error(`Missing ${slug}`); for (let index = 0; index < 1_000; index += 1) { const difficulty: GeneratorDifficulty = (['easy', 'medium', 'hard'] as const)[index % 3] ?? 'easy'; const input = { seed: `reading-comprehension-${slug}-${index}`, difficulty }; const question = generator.generate(input); expect(generator.generate(input)).toEqual(question); const validation = generator.validate(question); if (!validation.valid) throw new Error(`${slug} seed ${index}: ${validation.reason ?? 'unknown'}`); expect(question.prompt).toContain('Passage:'); expect(question.prompt).toContain('\n\nQuestion:'); expect(question.parameters.passageText).toEqual(expect.any(String)); expect(question.parameters.evidence).toEqual(expect.any(Array)); expect(question.prompt).not.toMatch(/undefined|NaN/u); expect(question.prompt).not.toContain('Ã'); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => choice.text.trim().toLowerCase())).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('reading_') === true && choice.derivation !== null)).toBe(true); expect(question.explanation.steps.some((step) => step.startsWith('Evidence:'))).toBe(true) } } }, 120_000)
  it.each(slugs)('creates five unique immutable passage-question snapshots for %s', (slug) => { const signatures = new Set<string>(); const prompts = new Set<string>(); for (let position = 1; position <= 5; position += 1) { const difficulty: GeneratorDifficulty = position <= 2 ? 'easy' : position <= 4 ? 'medium' : 'hard'; const question = generateValidatedQuestion({ attemptSeed: `reading-attempt-${slug}`, generatorSlug: slug, generatorVersion: 1, difficulty, position, existingSignatures: signatures, existingPrompts: prompts }); signatures.add(question.metadata.canonicalSignature); prompts.add(question.prompt.trim().toLowerCase()) } expect(signatures.size).toBe(5); expect(prompts.size).toBe(5) })
})
