import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { buildScopedStageArgs, classifyChangedFiles, inspectChangedFiles, parseStatusPorcelainZDetailed, selectPreflightReleaseScope, validateConcurrentReleaseScope, validateStagedScope } from '../scripts/lib/safe-release.mjs'

const temporaryDirectories:string[]=[]
afterEach(()=>{for(const directory of temporaryDirectories.splice(0))fs.rmSync(directory,{recursive:true,force:true})})
function repo(){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'safe-release-scope-'));temporaryDirectories.push(directory);const git=(args:string[])=>{const result=spawnSync('git',args,{cwd:directory,encoding:'utf8'});if(result.status!==0)throw new Error(result.stderr);return result.stdout};git(['init','-b','main']);git(['config','user.email','scope@example.com']);git(['config','user.name','Scope Test']);return{directory,git,write:(name:string,value:string|Buffer)=>{const file=path.join(directory,...name.split('/'));fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,value)},status:()=>parseStatusPorcelainZDetailed(git(['status','--porcelain=v1','-z','--untracked-files=all']))}}
function commitBase(fixture:ReturnType<typeof repo>){fixture.write('scripts/release.mjs','old');fixture.write('tests/release.test.ts','old');fixture.write('docs/remove.md','old');fixture.write('docs/rename-old.md','old');fixture.git(['add','--all']);fixture.git(['commit','-m','base'])}

describe('Safe Release scoped staging',()=>{
  it('stages only three approved files while leaving 42 unrelated design assets untouched',()=>{const f=repo();commitBase(f);f.write('scripts/release.mjs','new');f.write('tests/release.test.ts','new');f.write('tests/new-release.test.ts','new');for(let index=0;index<42;index+=1)f.write(`design-assets/pasawise/asset-${index}.svg`,`asset-${index}`);const scope=selectPreflightReleaseScope(f.status());expect(scope.approvedFiles).toEqual(['scripts/release.mjs','tests/new-release.test.ts','tests/release.test.ts']);expect(scope.ignoredUntrackedFiles).toHaveLength(42);f.git(buildScopedStageArgs(scope.approvedFiles));const staged=f.git(['diff','--cached','--name-only','--no-renames','-z']).split('\0').filter(Boolean);expect(validateStagedScope(scope.approvedFiles,staged)).toEqual({approvedCount:3,stagedCount:3});expect(f.git(['ls-files','--others','--exclude-standard','--','design-assets']).trim().split('\n')).toHaveLength(42);expect(fs.readFileSync(path.join(f.directory,'design-assets/pasawise/asset-0.svg'),'utf8')).toBe('asset-0')})
  it('blocks a preexisting staged file instead of committing another workstream',()=>{expect(()=>selectPreflightReleaseScope([{file:'scripts/release.mjs',status:' M',untracked:false,staged:false},{file:'notes/other.md',status:'A ',untracked:false,staged:true}])).toThrow('Preexisting staged files')})
  it('blocks a concurrent tracked runtime modification outside approved scope',()=>{expect(()=>validateConcurrentReleaseScope(['scripts/release.mjs'],[{file:'scripts/release.mjs',status:' M',untracked:false,staged:false},{file:'src/worker/index.ts',status:' M',untracked:false,staged:false}])).toThrow('Concurrent tracked or release-relevant changes')})
  it('leaves a benign untracked directory outside release scope',()=>{const entries=[{file:'scripts/release.mjs',status:' M',untracked:false,staged:false},{file:'design-assets/pasawise/logo.svg',status:'??',untracked:true,staged:false}];expect(selectPreflightReleaseScope(entries)).toEqual({approvedFiles:['scripts/release.mjs'],ignoredUntrackedFiles:['design-assets/pasawise/logo.svg']});expect(validateConcurrentReleaseScope(['scripts/release.mjs'],entries).ignoredUntrackedFiles).toEqual(['design-assets/pasawise/logo.svg'])})
  it('stages approved modified, new, deleted, and renamed paths',()=>{const f=repo();commitBase(f);f.write('scripts/release.mjs','new');f.write('tests/new-release.test.ts','new');fs.rmSync(path.join(f.directory,'docs/remove.md'));fs.renameSync(path.join(f.directory,'docs/rename-old.md'),path.join(f.directory,'docs/rename-new.md'));const scope=selectPreflightReleaseScope(f.status());f.git(buildScopedStageArgs(scope.approvedFiles));const staged=f.git(['diff','--cached','--name-only','--no-renames','-z']).split('\0').filter(Boolean);expect(validateStagedScope(scope.approvedFiles,staged).stagedCount).toBe(5);expect(staged.sort()).toEqual(['docs/remove.md','docs/rename-new.md','docs/rename-old.md','scripts/release.mjs','tests/new-release.test.ts'])})
  it('blocks when cached paths differ from approved scope',()=>{expect(()=>validateStagedScope(['a.ts','b.ts','c.ts'],['a.ts','b.ts','unexpected.ts'])).toThrow('Staged scope differs')})
  it('preserves secret, suspicious huge-file, and migration protections',()=>{const f=repo();f.write('src/secret.ts',`token='ghp_${'a'.repeat(30)}'`);f.write('.tmp/tool.exe',Buffer.alloc(101));const inspection=inspectChangedFiles(f.directory,['src/secret.ts','.tmp/tool.exe'],{maxBytes:100});expect(inspection.secretFindings).toEqual([expect.objectContaining({file:'src/secret.ts',kind:'GitHub token'})]);expect(inspection.largeFiles).toEqual([expect.objectContaining({file:'.tmp/tool.exe'})]);expect(inspection.suspiciousTemporaryFiles).toEqual([expect.objectContaining({file:'.tmp/tool.exe'})]);expect(classifyChangedFiles(['migrations/9999_forbidden.sql']).blockers).toEqual([expect.objectContaining({code:'migration_detected'})])})
})
