import {describe,expect,it} from 'vitest'
import {resolveTeachingPublisher,teachingPublisherRegistry} from '../scripts/lib/teaching-publisher-registry.mjs'
import {analyzeTeachingPlan,isIdempotentResult,normalizePublisherPlan,resolveTeachingCredentials,runTeachingReleasePipeline,sameValidationSnapshot,validateContentInspection,verifyCapabilityWithRetry} from '../scripts/lib/safe-teaching-release.mjs'
const plan=(overrides={})=>normalizePublisherPlan({topicSlug:'average',lessonCount:12,writesRequired:true,totals:{blocksCreated:0,blocksUpdated:3,blocksDeleted:0},unrelatedTopicsModified:0,...overrides})
describe('Automatic Teaching Release v1',()=>{
 it('resolves registry topics and aliases',()=>{expect(Object.keys(teachingPublisherRegistry)).toHaveLength(24);expect(resolveTeachingPublisher('ratio-and-proportion').name).toBe('ratio-proportion');expect(resolveTeachingPublisher('average').confirmation).toBe('publish-average-teaching-system-v1');expect(resolveTeachingPublisher('number-problems').confirmation).toBe('publish-number-problems-teaching-system-v1');expect(resolveTeachingPublisher('age-problems').confirmation).toBe('publish-age-problems-teaching-system-v1');expect(resolveTeachingPublisher('work-rate').confirmation).toBe('publish-work-rate-teaching-system-v1');expect(resolveTeachingPublisher('distance-speed-time').confirmation).toBe('publish-distance-speed-time-teaching-system-v1');expect(resolveTeachingPublisher('simple-interest').confirmation).toBe('publish-simple-interest-teaching-system-v1');expect(resolveTeachingPublisher('vocabulary-and-word-meaning').confirmation).toBe('publish-vocabulary-word-meaning-teaching-system-v1');expect(resolveTeachingPublisher('synonyms-and-antonyms').confirmation).toBe('publish-synonyms-antonyms-teaching-system-v1');expect(resolveTeachingPublisher('context-clues').confirmation).toBe('publish-context-clues-teaching-system-v1');expect(resolveTeachingPublisher('sentence-completion').confirmation).toBe('publish-sentence-completion-teaching-system-v1');expect(resolveTeachingPublisher('grammar-and-correct-usage').confirmation).toBe('publish-grammar-and-correct-usage-teaching-system-v1');expect(resolveTeachingPublisher('subject-verb-agreement').confirmation).toBe('publish-subject-verb-agreement-teaching-system-v1');expect(resolveTeachingPublisher('pronouns-and-modifiers').confirmation).toBe('publish-pronouns-and-modifiers-teaching-system-v1');expect(resolveTeachingPublisher('sentence-structure-and-error-identification').confirmation).toBe('publish-sentence-structure-and-error-identification-teaching-system-v1');expect(resolveTeachingPublisher('paragraphOrganization').confirmation).toBe('publish-paragraph-organization-teaching-system-v1');expect(resolveTeachingPublisher('readingComprehension').confirmation).toBe('publish-reading-comprehension-teaching-system-v1')})
 it('resolves Logical Reasoning Teaching System v1',()=>{expect(resolveTeachingPublisher('logicalReasoning').confirmation).toBe('publish-logical-reasoning-fundamentals-teaching-system-v1')})
 it('resolves Analogy and Classification Teaching System v1',()=>{expect(resolveTeachingPublisher('analogyClassification').confirmation).toBe('publish-analogy-and-classification-teaching-system-v1')})
 it('resolves Number Series Teaching System v1',()=>{expect(resolveTeachingPublisher('numberSeries').confirmation).toBe('publish-number-series-teaching-system-v1')})
 it('resolves Letter Series Teaching System v1',()=>{expect(resolveTeachingPublisher('letterSeries').confirmation).toBe('publish-letter-series-teaching-system-v1')})
 it('rejects unknown topics',()=>{expect(()=>resolveTeachingPublisher('unknown-topic')).toThrow('Unknown teaching topic')})
 it('allows zero deletions',()=>{expect(analyzeTeachingPlan(plan())).toMatchObject({allowed:true,approvalFingerprint:null})})
 it('allows only classified safe duplicates',()=>{const p=plan({deletionPlanFingerprint:'abc',deletions:[{learnerContentAssessment:'safe-duplicate'}],totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:1}});expect(analyzeTeachingPlan(p)).toEqual({allowed:true,reason:null,approvalFingerprint:'abc'})})
 it('requires evidence for equivalent replacements',()=>{const p=plan({deletionPlanFingerprint:'abc',deletions:[{learnerContentAssessment:'superseded-with-equivalent-content'}],totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:1}});expect(analyzeTeachingPlan(p).reason).toBe('missing_replacement_evidence')})
 it.each(['requires-human-review','unknown','potentially-valuable','unsafe'])('blocks %s deletions',(status)=>{const p=plan({deletionPlanFingerprint:'abc',deletions:[{learnerContentAssessment:status}],totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:1}});expect(analyzeTeachingPlan(p).reason).toBe('content_review_required')})
 it('blocks unclassified deletion totals',()=>{expect(analyzeTeachingPlan(plan({totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:2}})).reason).toBe('unclassified_deletions')})
 it('blocks unrelated topic mutation, warnings, and blockers',()=>{expect(analyzeTeachingPlan(plan({unrelatedTopicsModified:1})).reason).toBe('unrelated_topic_mutation');expect(analyzeTeachingPlan(plan({warnings:['x']})).allowed).toBe(false);expect(analyzeTeachingPlan(plan({blockers:['x']})).allowed).toBe(false)})
 it('detects TOCTOU fingerprint/count changes',()=>{const a=plan();expect(sameValidationSnapshot(a,a)).toBe(true);expect(sameValidationSnapshot(a,plan({deletionPlanFingerprint:'new'}))).toBe(false)})
 it('requires a truly write-free idempotent result',()=>{expect(isIdempotentResult({topicSlug:'average',updated:false,writeRequired:false,totals:{blocksCreated:0,blocksUpdated:0,blocksDeleted:0},unrelatedTopicsModified:0})).toBe(true);expect(isIdempotentResult({topicSlug:'average',updated:true,totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:0}})).toBe(false)})
 it('resolves standard and legacy credentials without exposing the password',()=>{const meta=resolveTeachingPublisher('average');expect(resolveTeachingCredentials(meta,{CSE_CONTENT_ADMIN_EMAIL:'admin@example.com',CSE_CONTENT_ADMIN_PASSWORD:'standard'})).toEqual({email:'admin@example.com',passwordEnv:'CSE_AVERAGE_ADMIN_PASSWORD',password:'standard'});expect(resolveTeachingCredentials(meta,{CSE_CONTENT_ADMIN_EMAIL:'admin@example.com',CSE_AVERAGE_ADMIN_PASSWORD:'legacy'}).password).toBe('legacy');expect(()=>resolveTeachingCredentials(meta,{})).toThrow('credentials are not configured')})
 it('validates a common production content-inspection result',()=>{expect(validateContentInspection({allMatch:true,lessonCount:12})).toMatchObject({allMatch:true});expect(()=>validateContentInspection({allMatch:false})).toThrow('did not match')})

 it('retries only transient missing capability responses before validation can continue',async()=>{let attempts=0;let sleeps=0;const result=await verifyCapabilityWithRetry(()=>{attempts+=1;if(attempts<3)throw new Error('404 NOT_FOUND capability');return{supported:true}},{attempts:5,delayMs:0,sleep:()=>{sleeps+=1}});expect(result).toEqual({supported:true});expect(attempts).toBe(3);expect(sleeps).toBe(2)})
 it('does not retry non-transient capability failures',async()=>{let attempts=0;await expect(verifyCapabilityWithRetry(()=>{attempts+=1;throw new Error('403 capability denied')},{attempts:5,delayMs:0,sleep:()=>undefined})).rejects.toThrow('403 capability denied');expect(attempts).toBe(1)})

 type JsonResult=Record<string,unknown>
 type PipelineOperations=Parameters<typeof runTeachingReleasePipeline>[0]
 const rawPlan=(overrides:JsonResult={}):JsonResult=>({topicSlug:'average',lessonCount:12,writesRequired:true,totals:{blocksCreated:0,blocksUpdated:3,blocksDeleted:0},unrelatedTopicsModified:0,...overrides})
 const canonical:JsonResult={topicSlug:'average',lessonCount:12,writeRequired:false,updated:false,totals:{blocksCreated:0,blocksUpdated:0,blocksDeleted:0},unrelatedTopicsModified:0}
 const firstWrite:JsonResult={topicSlug:'average',updated:true,totals:{blocksCreated:0,blocksUpdated:3,blocksDeleted:0},unrelatedTopicsModified:0}
 function next(values:JsonResult[]){const value=values.shift();if(value===undefined)throw new Error('mock response queue exhausted');return value}
 function pipeline(overrides:Partial<PipelineOperations>={}){const validations:JsonResult[]=[rawPlan(),rawPlan(),canonical];const publications:JsonResult[]=[firstWrite,canonical];const calls:string[]=[];const operations:PipelineOperations={safeRelease:()=>{calls.push('safe-release')},verifyCapability:()=>{calls.push('verify-capability');return{supported:true}},validate:()=>{calls.push('validate');return next(validations)},publish:(fingerprint)=>{calls.push(`publish:${fingerprint??'none'}`);return next(publications)},inspect:()=>{calls.push('inspect');return{allMatch:true}},...overrides};return{calls,operations}}


 it('runs release, validation, publish, post-validation, idempotency, and inspection in order',async()=>{const fixture=pipeline();const result=await runTeachingReleasePipeline(fixture.operations);expect(result.status).toBe('published');expect(fixture.calls).toEqual(['safe-release','verify-capability','validate','validate','publish:none','validate','publish:none','inspect']);expect(result.qa).toMatchObject({status:'skipped'})})
 it('stops on a missing deployed reconciliation capability before validate-only or publication',async()=>{let validated=false;let published=false;const fixture=pipeline();fixture.operations.verifyCapability=()=>{fixture.calls.push('verify-capability');throw new Error('404 NOT_FOUND reconciliation capability')};fixture.operations.validate=()=>{validated=true;return rawPlan()};fixture.operations.publish=()=>{published=true;return firstWrite};await expect(runTeachingReleasePipeline(fixture.operations)).rejects.toThrow('404 NOT_FOUND reconciliation capability');expect(fixture.calls).toEqual(['safe-release','verify-capability']);expect(validated).toBe(false);expect(published).toBe(false)})
 it('passes a stable safe-deletion fingerprint to both writes',async()=>{const deletion=rawPlan({deletionPlanFingerprint:'fp-1',deletions:[{learnerContentAssessment:'safe-duplicate'}],totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:1}});const validations=[deletion,deletion,canonical];const fingerprints:Array<string|null>=[];const fixture=pipeline({validate:()=>next(validations),publish:(value)=>{fingerprints.push(value);return fingerprints.length===1?firstWrite:canonical}});await runTeachingReleasePipeline(fixture.operations);expect(fingerprints).toEqual(['fp-1','fp-1'])})
 it('stops human-review deletions before write mode',async()=>{let published=false;const unsafe=rawPlan({deletionPlanFingerprint:'fp',deletions:[{learnerContentAssessment:'requires-human-review'}],totals:{blocksCreated:0,blocksUpdated:1,blocksDeleted:1}});const result=await runTeachingReleasePipeline(pipeline({validate:()=>unsafe,publish:()=>{published=true;return canonical}}).operations);expect(result.status).toBe('content-review-required');expect(published).toBe(false)})
 it('stops when the validation snapshot or fingerprint changes',async()=>{const validations=[rawPlan(),rawPlan({totals:{blocksCreated:0,blocksUpdated:4,blocksDeleted:0}})];await expect(runTeachingReleasePipeline(pipeline({validate:()=>next(validations)}).operations)).rejects.toThrow('snapshot changed')})

 it.each(['migration detected','DB repair detected','focused tests failed','Safe Release failed','deployment failed','health check failed','Git credentials unavailable','Cloudflare credentials unavailable'])('stops all content phases when Safe Release reports %s',async(message)=>{let validated=false;await expect(runTeachingReleasePipeline(pipeline({safeRelease:()=>{throw new Error(message)},validate:()=>{validated=true;return rawPlan()}}).operations)).rejects.toThrow(message);expect(validated).toBe(false)})

 it('propagates publisher validation failure before publication',async()=>{let published=false;await expect(runTeachingReleasePipeline(pipeline({validate:()=>{throw new Error('publisher validation failed')},publish:()=>{published=true;return canonical}}).operations)).rejects.toThrow('publisher validation failed');expect(published).toBe(false)})
 it('propagates publisher write failure',async()=>{await expect(runTeachingReleasePipeline(pipeline({publish:()=>{throw new Error('publisher write failed')}}).operations)).rejects.toThrow('publisher write failed')})
 it('blocks a post-publish plan that still requires writes',async()=>{const validations=[rawPlan(),rawPlan(),rawPlan()];await expect(runTeachingReleasePipeline(pipeline({validate:()=>next(validations)}).operations)).rejects.toThrow('still requires writes')})
 it('blocks unrelated-topic mutation reported by first publish',async()=>{await expect(runTeachingReleasePipeline(pipeline({publish:()=>({...firstWrite,unrelatedTopicsModified:1})}).operations)).rejects.toThrow('unrelated topic mutation')})
 it('blocks unrelated-topic mutation reported by post-validation',async()=>{const validations=[rawPlan(),rawPlan(),{...canonical,unrelatedTopicsModified:1}];await expect(runTeachingReleasePipeline(pipeline({validate:()=>next(validations)}).operations)).rejects.toThrow('Post-publish validation')})
 it('blocks a non-idempotent second publication',async()=>{const publications=[firstWrite,firstWrite];await expect(runTeachingReleasePipeline(pipeline({publish:()=>next(publications)}).operations)).rejects.toThrow('IDEMPOTENCY FAILURE')})
 it('blocks a failed production content inspection',async()=>{await expect(runTeachingReleasePipeline(pipeline({inspect:()=>({allMatch:false})}).operations)).rejects.toThrow('did not match')})
 it('runs optional read-only QA verification when supplied',async()=>{let qaRuns=0;const result=await runTeachingReleasePipeline(pipeline({qaVerify:()=>{qaRuns+=1;return{status:'passed',readOnly:true}}}).operations);expect(qaRuns).toBe(1);expect(result.qa).toEqual({status:'passed',readOnly:true})})
 it('returns already-canonical without any publisher write',async()=>{let writes=0;const result=await runTeachingReleasePipeline(pipeline({validate:()=>canonical,publish:()=>{writes+=1;return canonical}}).operations);expect(result.status).toBe('already-canonical');expect(writes).toBe(0)})
})