import { describe, expect, it } from 'vitest'
import { sentenceStructureErrorsLessonSpecs } from '../scripts/lib/sentence-structure-errors-teaching-system-content.mjs'
import legacySource from '../scripts/sentence-structure-errors-topic-content.mjs?raw'
import generatorSource from '../src/worker/generators/sentence-structure/sentence-structure-generators.ts?raw'
import assessmentSource from '../src/worker/domain/subject-assessment-blueprint.ts?raw'
import recoverySource from '../src/worker/domain/smart-recovery-fixed-question-manifest.ts?raw'
import mockSource from '../src/worker/domain/mock-exam-blueprint.ts?raw'
import registrySource from '../scripts/lib/teaching-publisher-registry.mjs?raw'
import lessonPageSource from '../src/react-app/pages/LessonPage.tsx?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(sentenceStructureErrorsLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Sentence Structure and Error Identification Teaching System v1',()=>{
 it('preserves the authoritative eighth Verbal topic, lesson order, activity types, and durations',()=>{expect(legacySource).toContain("topicSlug = 'sentence-structure-and-error-identification'");expect(sentenceStructureErrorsLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([['understanding-sentence-structure','reading',17],['subjects-predicates-phrases-clauses','practice',18],['simple-compound-complex-sentences','practice',18],['sentence-fragments','practice',17],['run-on-sentences-comma-splices','practice',18],['faulty-coordination-subordination','practice',18],['parallel-structure','practice',17],['unclear-illogical-sentence-construction','practice',19],['identifying-errors-sentence-parts','practice',19],['mixed-sentence-structure-error-problems','practice',20],['mixed-error-identification-practice','practice',20],['sentence-structure-error-identification-topic-quiz','quiz',25]])})
 it('uses valid deterministic canonical blocks with no guided-teaching duplication',()=>{expect(sentenceStructureErrorsLessonSpecs).toHaveLength(12);for(const item of sentenceStructureErrorsLessonSpecs){expect(item.blocks.length).toBeGreaterThanOrEqual(10);expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('teaches sentence anatomy, clause classification, sentence types, fragments, and boundaries from evidence',()=>{for(const value of ['finite verb','subject','predicate','independent clause'])expect(lesson('understanding-sentence-structure')).toContain(value);for(const value of ['phrase','dependent clause','Pair, then stand'])expect(lesson('subjects-predicates-phrases-clauses')).toContain(value);for(const value of ['compound predicate','compound-complex','Count clauses, not verbs'])expect(lesson('simple-compound-complex-sentences')).toContain(value);for(const value of ['Because the report was incomplete','dependent','main idea'])expect(lesson('sentence-fragments')).toContain(value);for(const value of ['fused sentence','comma splice','semicolon'])expect(lesson('run-on-sentences-comma-splices')).toContain(value)})
 it('teaches connector logic, parallel form, clarity, and exact labeled-error location',()=>{for(const value of ['Although','because...so','Name the relationship first'])expect(lesson('faulty-coordination-subordination')).toContain(value);for(const value of ['filing records','matching grammatical form','Same job, same shape'])expect(lesson('parallel-structure')).toContain(value);for(const value of ['Maria was selected','salary','like with like'])expect(lesson('unclear-illogical-sentence-construction')).toContain(value);for(const value of ['Part C','No error','Rule, location, repair'])expect(lesson('identifying-errors-sentence-parts')).toContain(value)})
 it('provides the reusable CSE method, specific mistakes, why-based memory, and unchanged practice CTAs',()=>{expect(lesson('mixed-sentence-structure-error-problems')).toContain('Read → Mark → Classify → Test → Eliminate → Verify');const blocks=sentenceStructureErrorsLessonSpecs.flatMap((item)=>item.blocks);expect(blocks.filter((block)=>String(block.content.title??'').startsWith('Common mistake'))).toHaveLength(12);for(const block of blocks.filter((item)=>String(item.content.title??'').startsWith('Memory trick')))expect(String(block.content.text)).toContain('because');for(const item of sentenceStructureErrorsLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
 it('uses accessible text-first VisualTeachingBoard data with explanations beyond color',()=>{const visuals=sentenceStructureErrorsLessonSpecs.flatMap((item)=>item.blocks).flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(visuals.length).toBeGreaterThanOrEqual(20);for(const visual of visuals){expect(visual.ariaLabel.length).toBeGreaterThan(40);expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20)}})
 it('preserves generators, recovery, assessments, Full Mock, previous systems, and scrolling architecture',()=>{for(const slug of ['subject-predicate-clause-identification','sentence-type-classification','sentence-fragment-detection','run-on-comma-splice-detection','coordination-subordination-error','parallel-structure-error','unclear-illogical-sentence','sentence-part-error-identification','mixed-sentence-structure-errors']){expect(legacySource).toContain("'"+slug+"'");expect(generatorSource).toContain("'"+slug+"'");expect(assessmentSource).toContain("'"+slug+"'")};expect(recoverySource).toContain("topicSlug: 'sentence-structure-and-error-identification'");expect(mockSource).toContain('verbalAbilityBlueprintV1');for(const topic of ['vocabulary-and-word-meaning','synonyms-and-antonyms','context-clues','sentence-completion','grammar-and-correct-usage','subject-verb-agreement','pronouns-and-modifiers'])expect(registrySource).toContain(topic);expect(lessonPageSource).toContain('lesson-app-shell')})
})
