import { describe, expect, it } from 'vitest'
import { sentenceStructureBankV1 } from '../src/worker/domain/sentence-structure/sentence-structure-bank'
import { clauseMetadataValid, classifySentenceType, commaSpliceDetected, connectorLogicValid, fragmentDetected, logicalComparisonValid, parallelFormValid, runOnDetected, segmentedErrorValid } from '../src/worker/domain/sentence-structure/sentence-structure-rules'
import { uniqueStructureAnswer, uniqueStructureChoices, validateSentenceStructureBank } from '../src/worker/domain/sentence-structure/sentence-structure-validation'
import { generateValidatedQuestion, getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty, GeneratorSlug } from '../src/worker/generators/generator.types'

const slugs = ['subject-predicate-clause-identification', 'sentence-type-classification', 'sentence-fragment-detection', 'run-on-comma-splice-detection', 'coordination-subordination-error', 'parallel-structure-error', 'unclear-illogical-sentence', 'sentence-part-error-identification', 'mixed-sentence-structure-errors'] as const satisfies readonly GeneratorSlug[]

describe('Sentence Structure pure utilities', () => {
  it('keeps the 24-entry bank complete and internally consistent', () => { expect(sentenceStructureBankV1).toHaveLength(24); expect(validateSentenceStructureBank()).toEqual([]); expect(new Set(sentenceStructureBankV1.map((entry) => entry.id)).size).toBe(24); expect(new Set(sentenceStructureBankV1.map((entry) => entry.skill)).size).toBe(8); for (const skill of new Set(sentenceStructureBankV1.map((entry) => entry.skill))) expect(new Set(sentenceStructureBankV1.filter((entry) => entry.skill === skill).map((entry) => entry.difficulty))).toEqual(new Set(['easy', 'medium', 'hard'])) })
  it('represents subjects, predicates, phrases, and independent/dependent clauses', () => { const entry = sentenceStructureBankV1.find((item) => item.id === 'parts-clause-hard')!; expect(entry.subject).toBe('the clerk'); expect(entry.predicate).toBe('stayed after closing'); expect(entry.phrases).toContain('after closing'); expect(entry.clauses.map((item) => item.kind)).toEqual(['dependent', 'independent']); expect(clauseMetadataValid(entry)).toBe(true); expect(classifySentenceType(entry)).toBe('complex') })
  it('independently detects fragments, fused sentences, and comma splices', () => { expect(fragmentDetected(sentenceStructureBankV1.find((item) => item.id === 'fragment-dependent-easy')!)).toBe(true); expect(runOnDetected(sentenceStructureBankV1.find((item) => item.id === 'runon-fused-easy')!)).toBe(true); expect(commaSpliceDetected(sentenceStructureBankV1.find((item) => item.id === 'runon-comma-medium')!)).toBe(true) })
  it('validates connectors, parallel forms, logical comparisons, and segmented errors', () => { expect(sentenceStructureBankV1.filter((item) => item.skill === 'coordination').every(connectorLogicValid)).toBe(true); expect(sentenceStructureBankV1.filter((item) => item.skill === 'parallel').every(parallelFormValid)).toBe(true); expect(logicalComparisonValid(sentenceStructureBankV1.find((item) => item.id === 'illogical-comparison-medium')!)).toBe(true); expect(sentenceStructureBankV1.filter((item) => item.skill === 'segmented_error').every(segmentedErrorValid)).toBe(true); expect(uniqueStructureChoices(['A', 'B', 'C', 'No error'])).toBe(true); expect(uniqueStructureAnswer(['A', 'B', 'C', 'No error'], 'C')).toBe(true) })
})

describe('Sentence Structure generator registry', () => {
  it.each(slugs)('registers %s version 1 for every difficulty', (slug) => { const generator = getGenerator(slug, 1); expect(generator).not.toBeNull(); expect(generator?.supportedDifficulties).toEqual(['easy', 'medium', 'hard']) })
  it('stress-validates 1,000 deterministic questions per generator (9,000 total)', () => { for (const slug of slugs) { const generator = getGenerator(slug, 1); if (generator === null) throw new Error(`Missing ${slug}`); for (let index = 0; index < 1_000; index += 1) { const difficulty: GeneratorDifficulty = (['easy', 'medium', 'hard'] as const)[index % 3] ?? 'easy'; const input = { seed: `sentence-structure-${slug}-${index}`, difficulty }; const question = generator.generate(input); expect(generator.generate(input)).toEqual(question); const validation = generator.validate(question); if (!validation.valid) throw new Error(`${slug} seed ${index}: ${validation.reason ?? 'unknown'}`); expect(question.prompt).not.toMatch(/undefined|NaN|Ã¢/iu); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => choice.text.trim().toLowerCase())).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('structure_') === true && choice.derivation !== null)).toBe(true); expect(question.explanation.steps.join(' ')).toContain('primary rule') } } }, 120_000)
  it.each(slugs)('creates five unique immutable snapshots for %s', (slug) => { const signatures = new Set<string>(); const prompts = new Set<string>(); for (let position = 1; position <= 5; position += 1) { const difficulty: GeneratorDifficulty = position <= 2 ? 'easy' : position <= 4 ? 'medium' : 'hard'; const question = generateValidatedQuestion({ attemptSeed: `structure-attempt-${slug}`, generatorSlug: slug, generatorVersion: 1, difficulty, position, existingSignatures: signatures, existingPrompts: prompts }); signatures.add(question.metadata.canonicalSignature); prompts.add(question.prompt.trim().toLowerCase()) } expect(signatures.size).toBe(5); expect(prompts.size).toBe(5) })
})
