import { describe, expect, it } from 'vitest'
import { sentenceCompletionLessonSpecs } from '../scripts/lib/sentence-completion-teaching-system-content.mjs'
import legacySource from '../scripts/sentence-completion-topic-content.mjs?raw'
import generatorSource from '../src/worker/generators/sentence-completion/sentence-completion-generators.ts?raw'
import assessmentSource from '../src/worker/domain/subject-assessment-blueprint.ts?raw'
import smartRecoverySource from '../src/worker/domain/smart-recovery-fixed-question-manifest.ts?raw'
import vocabularySource from '../scripts/lib/vocabulary-word-meaning-teaching-system-content.mjs?raw'
import synonymsSource from '../scripts/lib/synonyms-antonyms-teaching-system-content.mjs?raw'
import contextSource from '../scripts/lib/context-clues-teaching-system-content.mjs?raw'
import registrySource from '../scripts/lib/teaching-publisher-registry.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(sentenceCompletionLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Sentence Completion Teaching System v1',()=>{
 it('preserves the authoritative topic, twelve activities, order, types, and durations',()=>{expect(legacySource).toContain("topicSlug = 'sentence-completion'");expect(sentenceCompletionLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
 ['understanding-sentence-completion','reading',17],['grammar-fit','practice',15],['meaning-and-logic-fit','practice',16],['transition-words','practice',16],['cause-and-effect-relationships','practice',16],['contrast-and-comparison','practice',17],['parallel-ideas-and-structure','practice',17],['tone-and-formality','practice',16],['double-blank-sentences','practice',18],['mixed-sentence-completion-problems','practice',20],['mixed-sentence-completion-practice','practice',20],['sentence-completion-topic-quiz','quiz',25]])})
 it('uses valid deterministic blocks and preserves audited production counts',()=>{expect(sentenceCompletionLessonSpecs.map((item)=>item.blocks.length)).toEqual([12,10,10,10,10,10,10,10,10,10,10,10]);for(const item of sentenceCompletionLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('teaches prediction, whole-sentence reading, relationships, and one-blank method',()=>{const intro=lesson('understanding-sentence-completion');for(const value of ['meaning, grammar, sentence logic, tone','Although the weather','severe','Predict before choices','Read → Signal → Predict → Fit → Check','Continuation, contrast, cause/effect, comparison','Clearly is correct'])expect(intro).toContain(value)})
 it('integrates grammar, part of speech, word form, tense, agreement, and logical plausibility',()=>{const grammar=lesson('grammar-fit');for(const value of ['decisive','Promptly','after to','after had','list of requirements is'])expect(grammar).toContain(value);const logic=lesson('meaning-and-logic-fit');for(const value of ['dehydration','Drink is correct','Before submitting','Reviewed','grammatically correct word'])expect(logic).toContain(value)})
 it('teaches transitions, cause/effect, continuation, contrast, comparison, and sequence',()=>{const transitions=lesson('transition-words');for(const value of ['However','therefore','furthermore','consequently','for instance','punctuation'])expect(transitions).toContain(value);const cause=lesson('cause-and-effect-relationships');for(const value of ['road was flooded','Delayed','auditor could not','Verify is correct'])expect(cause).toContain(value);const contrast=lesson('contrast-and-comparison');for(const value of ['adaptable','Like his dependable older brother','Reliable','same or opposite direction'])expect(contrast).toContain(value)})
 it('teaches parallelism, collocation, tone, intensity, and formal public-service fit',()=>{const parallel=lesson('parallel-ideas-and-structure');for(const value of ['planning, checking','Submitting','make a decision','take responsibility','conduct an investigation'])expect(parallel).toContain(value);const tone=lesson('tone-and-formality');for(const value of ['stern','serious violations','Clear is the best concept','severe or extensive damage','minor'])expect(tone).toContain(value)})
 it('teaches paired double blanks and systematic mixed distractor elimination',()=>{const paired=lesson('double-blank-sentences');for(const value of ['Difficult / efficiently','easier blank','eliminate the entire pair','Enthusiastic'])expect(paired).toContain(value);const mixed=lesson('mixed-sentence-completion-problems');for(const value of ['grammar, logic, direction, tone, strength, and collocation','prevent or reduce misuse','hardly','not, never, hardly, rarely'])expect(mixed).toContain(value)})
 it('uses nine accessible text visuals, reasoned memory tricks, common mistakes, and unchanged CTAs',()=>{const blocks=sentenceCompletionLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(9);expect(visuals.length).toBeGreaterThanOrEqual(14);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20);expect(visual.ariaLabel.length).toBeGreaterThan(40)}expect(blocks.filter((block)=>block.content.title==='Common mistake'||block.content.title==='Common mistakes')).toHaveLength(12);for(const block of blocks.filter((item)=>String(item.content.title??'').startsWith('Memory trick')))expect(String(block.content.text)).toMatch(/because/iu);for(const item of sentenceCompletionLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
 it('preserves all generators and prior systems without duplicating their ownership',()=>{for(const slug of ['grammar-fit-completion','meaning-fit-completion','transition-word-completion','cause-effect-completion','contrast-comparison-completion','parallel-idea-completion','tone-formality-completion','double-blank-completion','mixed-sentence-completion']){expect(legacySource).toContain("'"+slug+"'");expect(generatorSource).toContain("'"+slug+"'");expect(assessmentSource).toContain("'"+slug+"'")}expect(smartRecoverySource).toContain("topicSlug: 'sentence-completion'");expect(legacySource).toContain("'mixed-sentence-completion-practice'");expect(legacySource).toContain("'sentence-completion-topic-quiz'");expect(vocabularySource).toContain("slug:'roots-and-base-words'");expect(synonymsSource).toContain("slug:'basic-synonyms'");expect(contextSource).toContain("slug:'definition-clues'");expect(JSON.stringify(sentenceCompletionLessonSpecs)).toContain('This topic owns the decision process');for(const key of ['vocabulary-and-word-meaning','synonyms-and-antonyms','context-clues','sentence-completion'])expect(registrySource).toContain(key)})
})
