import { describe, expect, it } from 'vitest'
import { simpleInterestLessonSpecs } from '../scripts/lib/simple-interest-teaching-system-content.mjs'
import legacySource from '../scripts/create-and-publish-simple-interest-topic.mjs?raw'
import distanceSource from '../scripts/lib/distance-speed-time-teaching-system-content.mjs?raw'
import workRateSource from '../scripts/lib/work-rate-teaching-system-content.mjs?raw'
import ageSource from '../scripts/lib/age-problems-teaching-system-content.mjs?raw'
import numberSource from '../scripts/lib/number-problems-teaching-system-content.mjs?raw'
import averageSource from '../scripts/lib/average-teaching-system-content.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(simpleInterestLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Simple Interest Teaching System v1',()=>{
 it('preserves all twelve authoritative activities, types, order, and durations',()=>{expect(simpleInterestLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
 ['understanding-simple-interest','reading',13],['finding-simple-interest','practice',11],['finding-the-principal','practice',11],['finding-the-interest-rate','practice',12],['finding-the-time','practice',12],['maturity-value','practice',11],['converting-time-for-interest-problems','practice',13],['comparing-simple-interest-options','practice',13],['loans-and-savings-applications','practice',14],['mixed-simple-interest-problems','practice',15],['mixed-simple-interest-practice','practice',16],['simple-interest-topic-quiz','quiz',18]])})
 it('uses valid deterministic canonical blocks without duplicate illustrated teaching',()=>{for(const item of simpleInterestLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('derives and applies simple interest from principal, rate, and time',()=>{const intro=lesson('understanding-simple-interest');for(const value of ['original principal','5%=0.05','₱500','I=P×r×t','A=P+I','same amount each year'])expect(intro).toContain(value);expect(lesson('finding-simple-interest')).toContain('15,000×0.06×3');expect(lesson('finding-simple-interest')).toContain('₱2,700')})
 it('solves principal, rate, time, and maturity value with correct inverse arithmetic',()=>{expect(lesson('finding-the-principal')).toContain('1,800÷0.15=₱12,000');expect(lesson('finding-the-principal')).toContain('11,200÷1.12=₱10,000');expect(lesson('finding-the-interest-rate')).toContain('0.06');expect(lesson('finding-the-interest-rate')).toContain('7.5%');expect(lesson('finding-the-time')).toContain('3 years');expect(lesson('finding-the-time')).toContain('1 year 6 months');expect(lesson('maturity-value')).toContain('₱16,800')})
 it('matches rate and time periods and follows only an explicitly stated day-count basis',()=>{const conversions=lesson('converting-time-for-interest-problems');for(const value of ['months÷12=years','9÷12=0.75','1% per month','73÷365=0.2','360 only when','365 only when','Do not assume 360 or 365'])expect(conversions).toContain(value)})
 it('covers comparisons, loans, savings, partial years, changing terms, and reasonableness',()=>{expect(lesson('comparing-simple-interest-options')).toContain('B earns ₱250 more');const applications=lesson('loans-and-savings-applications');expect(applications).toContain('₱34,200');expect(applications).toContain('₱28,000');expect(applications).toContain('8%');const mixed=lesson('mixed-simple-interest-problems');expect(mixed).toContain('₱1,920');expect(mixed).toContain('₱27,812.50');expect(mixed).toContain('Split only where the principal or rate changes');expect(lesson('simple-interest-topic-quiz')).toContain('doubling P, r, or t doubles simple interest')})
 it('explicitly teaches common mistakes, memory reasons, and verification',()=>{const blocks=simpleInterestLessonSpecs.flatMap((item)=>item.blocks);expect(blocks.filter((block)=>block.content.title==='Common mistake')).toHaveLength(12);for(const block of blocks.filter((item)=>String(item.content.title??'').startsWith('Memory trick')))expect(String(block.content.text)).toMatch(/because|why|since/iu);const all=JSON.stringify(blocks);for(const value of ['Do not treat 5% as 5','Do not give interest when the question asks for maturity value','Do not assume 360 or 365','substitut','reasonableness'])expect(all).toMatch(new RegExp(value,'iu'))})
 it('uses eight accessible visual boards with textual reasoning and unchanged practice CTAs',()=>{const blocks=simpleInterestLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(8);expect(visuals.length).toBeGreaterThanOrEqual(11);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20);expect(visual.ariaLabel.length).toBeGreaterThan(40)}for(const item of simpleInterestLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
 it('preserves generators, fixed practice, quiz, mappings, and unrelated canonical manifests',()=>{for(const slug of ['simple-interest','principal-from-interest','rate-from-interest','time-from-interest','maturity-value','interest-time-conversions','compare-interest-options','loan-savings-applications','mixed-simple-interest'])expect(legacySource).toContain("'"+slug+"'");expect(legacySource).toContain("spec.slug === 'mixed-simple-interest-practice'");expect(legacySource).toContain("spec.slug === 'simple-interest-topic-quiz'");expect(legacySource).toContain('passingScore: 70');expect(distanceSource).toContain("slug:'understanding-distance-speed-and-time'");expect(workRateSource).toContain("slug:'understanding-work-rates'");expect(ageSource).toContain("slug:'understanding-age-relationships'");expect(numberSource).toContain("slug:'translating-number-statements'");expect(averageSource).toContain("slug:'understanding-average'")})
})
