import { describe, expect, it } from 'vitest'

import { vocabularyBankV1 } from '../src/worker/domain/vocabulary/vocabulary-bank'
import { formatAffix } from '../src/worker/domain/vocabulary/vocabulary-format'
import { areConfusedPartners, classifyConnotation, decomposeWord, definitionMatches, familyForm, hasPartOfSpeech, hasSense, normalizeWord, sentenceIsUsable } from '../src/worker/domain/vocabulary/vocabulary-rules'
import { hasUniqueAnswer, hasUniqueVisibleChoices, validateVocabularyBank } from '../src/worker/domain/vocabulary/vocabulary-validation'
import { generateValidatedQuestion, getGenerator } from '../src/worker/generators/generator.registry'
import type { GeneratorDifficulty, GeneratorSlug } from '../src/worker/generators/generator.types'

const slugs = ['root-word-meaning', 'prefix-meaning', 'suffix-meaning', 'word-family-form', 'denotation-connotation', 'multiple-meaning-word', 'definition-example-match', 'commonly-confused-words', 'mixed-vocabulary-word-meaning'] as const satisfies readonly GeneratorSlug[]

describe('Vocabulary and Word Meaning pure utilities', () => {
  it('keeps the versioned curated bank internally consistent', () => { expect(vocabularyBankV1.length).toBeGreaterThanOrEqual(20); expect(validateVocabularyBank()).toEqual([]); expect(new Set(vocabularyBankV1.map((item) => item.normalized)).size).toBe(vocabularyBankV1.length); expect(vocabularyBankV1.every((item) => sentenceIsUsable(item.example, item.word))).toBe(true) })
  it('normalizes and validates roots, affixes, families, and parts of speech', () => { expect(normalizeWord('  Public   Service ')).toBe('public service'); expect(decomposeWord(vocabularyBankV1.find((item) => item.word === 'careless')!)).toEqual({ prefix: null, base: 'care', suffix: '-less' }); expect(formatAffix('re-', 'write', null)).toBe('re- + write'); expect(familyForm('decide', 'adjective')).toBe('decisive'); expect(hasPartOfSpeech('decision', 'noun')).toBe(true) })
  it('validates definitions, connotations, senses, confused pairs, and answer uniqueness', () => { expect(definitionMatches('temporary', 'lasting for a limited time')).toBe(true); expect(classifyConnotation('economical')).toBe('positive'); expect(hasSense('light', 'not heavy', 'The package is light enough to carry.')).toBe(true); expect(areConfusedPartners('affect', 'effect')).toBe(true); expect(hasUniqueVisibleChoices(['one', 'two', 'three', 'four'])).toBe(true); expect(hasUniqueAnswer(['one', 'two', 'three', 'four'], 'two')).toBe(true) })
})

describe('Vocabulary generator registry', () => {
  it.each(slugs)('registers %s version 1 for all difficulties', (slug) => { const generator = getGenerator(slug, 1); expect(generator).not.toBeNull(); expect(generator?.supportedDifficulties).toEqual(['easy', 'medium', 'hard']) })
  it('stress-validates 1,000 deterministic questions per generator', () => { for (const slug of slugs) { const generator = getGenerator(slug, 1); if (generator === null) throw new Error(`Missing ${slug}`); for (let index = 0; index < 1_000; index += 1) { const difficulty: GeneratorDifficulty = (['easy', 'medium', 'hard'] as const)[index % 3] ?? 'easy'; const input = { seed: `vocabulary-${slug}-${index}`, difficulty }; const question = generator.generate(input); expect(generator.generate(input)).toEqual(question); const validation = generator.validate(question); if (!validation.valid) throw new Error(`${slug} failed seed ${index}: ${validation.reason ?? 'unknown'}`); expect(question.choices).toHaveLength(4); expect(new Set(question.choices.map((choice) => normalizeWord(choice.text))).size).toBe(4); expect(question.choices.filter((choice) => choice.isCorrect)).toHaveLength(1); expect(question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('vocabulary_') === true && choice.derivation !== null)).toBe(true); expect(question.prompt).not.toMatch(/undefined|NaN/iu) } } }, 120_000)
  it.each(slugs)('creates five unique immutable snapshots for %s', (slug) => { const signatures = new Set<string>(); const prompts = new Set<string>(); for (let position = 1; position <= 5; position += 1) { const difficulty: GeneratorDifficulty = position <= 2 ? 'easy' : position <= 4 ? 'medium' : 'hard'; const question = generateValidatedQuestion({ attemptSeed: `vocabulary-attempt-${slug}`, generatorSlug: slug, generatorVersion: 1, difficulty, position, existingSignatures: signatures, existingPrompts: prompts }); signatures.add(question.metadata.canonicalSignature); prompts.add(normalizeWord(question.prompt)) } expect(signatures.size).toBe(5); expect(prompts.size).toBe(5) })
})
