import { describe, expect, it } from 'vitest'
import { vocabularyWordMeaningLessonSpecs } from '../scripts/lib/vocabulary-word-meaning-teaching-system-content.mjs'
import legacySource from '../scripts/vocabulary-word-meaning-topic-content.mjs?raw'
import generatorSource from '../src/worker/generators/vocabulary/vocabulary-generators.ts?raw'
import assessmentSource from '../src/worker/domain/subject-assessment-blueprint.ts?raw'
import smartRecoverySource from '../src/worker/domain/smart-recovery-skills.ts?raw'
import synonymsSource from '../scripts/synonyms-antonyms-topic-content.mjs?raw'
import contextCluesSource from '../scripts/context-clues-topic-content.mjs?raw'
import numericalRegistrySource from '../scripts/lib/teaching-publisher-registry.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(vocabularyWordMeaningLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Vocabulary and Word Meaning Teaching System v1',()=>{
 it('preserves all twelve authoritative activities, types, order, and durations',()=>{expect(vocabularyWordMeaningLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
 ['understanding-vocabulary-and-word-meaning','reading',16],['roots-and-base-words','practice',15],['prefixes-and-meaning','practice',15],['suffixes-and-meaning','practice',15],['word-families-and-parts-of-speech','practice',17],['denotation-and-connotation','practice',16],['multiple-meaning-words','practice',16],['matching-words-with-definitions-and-examples','practice',17],['commonly-confused-words','practice',17],['mixed-vocabulary-and-word-meaning','practice',20],['mixed-vocabulary-practice','practice',20],['vocabulary-and-word-meaning-topic-quiz','quiz',25]])})
 it('uses valid deterministic blocks and preserves all audited legacy counts',()=>{expect(vocabularyWordMeaningLessonSpecs.map((item)=>item.blocks.length)).toEqual([12,10,10,10,10,10,10,10,10,10,10,10]);for(const item of vocabularyWordMeaningLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('teaches direct meaning, context evidence, replacement, and an unknown-word strategy',()=>{const intro=lesson('understanding-vocabulary-and-word-meaning');for(const value of ['Meaning comes from both the word and its context','treacherous','dangerous or unsafe','Abundant means plentiful','Read → Clue → Replace → Check','Unknown-word strategy','addressed means dealt with'])expect(intro).toContain(value)})
 it('teaches roots, prefixes, suffixes, and word families without magic-rule claims',()=>{const roots=lesson('roots-and-base-words');for(const value of ['base word','root','bio=life','geo=earth','aud=hear','cred=believe','dict=say or speak'])expect(roots).toContain(value);const prefixes=lesson('prefixes-and-meaning');for(const value of ['un-=not','re-=again','pre-=before','mis-=wrongly','anti-=against','sub-=under','inter-=between','trans-=across','not automatic proof'])expect(prefixes).toContain(value);const suffixes=lesson('suffixes-and-meaning');for(const value of ['-less=without','-ful=having','-able=capable of','-tion=act/process/result','-ment=state/result','-ist=associated person','-ous=having a quality'])expect(suffixes).toContain(value);expect(lesson('word-families-and-parts-of-speech')).toContain('decide/decision/decisive/decisively')})
 it('distinguishes denotation, connotation, tone, intensity, and contextual senses',()=>{const denotation=lesson('denotation-and-connotation');for(const value of ['literal meaning','comfort, family, security, or belonging','confident','arrogant'])expect(denotation).toContain(value);const senses=lesson('multiple-meaning-words');expect(senses).toContain('edge of a river');expect(senses).toContain('financial institution');expect(senses).toContain('part of speech');const mixed=lesson('mixed-vocabulary-and-word-meaning');expect(mixed).toContain('annoyed → angry → furious');expect(mixed).toContain('commendable')})
 it('uses definition, example, inference, elimination, and confused-word reasoning accurately',()=>{const definitions=lesson('matching-words-with-definitions-and-examples');expect(definitions).toContain('meticulous');expect(definitions).toContain('very careful or precise');expect(definitions).toContain('Temporary means lasting for a limited time');const confused=lesson('commonly-confused-words');expect(confused).toContain('may affect');expect(confused).toContain('Advice is the noun');const mixed=lesson('mixed-vocabulary-and-word-meaning');expect(mixed).toContain('exhausted=extremely tired');for(const value of ['opposite','another context','first familiar option','grammatically wrong'])expect(mixed).toContain(value)})
 it('contains reasoned memory tricks, explicit mistakes, verification, and unchanged practice CTAs',()=>{const blocks=vocabularyWordMeaningLessonSpecs.flatMap((item)=>item.blocks);expect(blocks.filter((block)=>block.content.title==='Common mistake'||block.content.title==='Common mistakes')).toHaveLength(12);for(const block of blocks.filter((item)=>String(item.content.title??'').startsWith('Memory trick')))expect(String(block.content.text)).toMatch(/because/iu);for(const item of vocabularyWordMeaningLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA');expect(JSON.stringify(blocks)).toContain('Verification')})
 it('uses eight accessible text-focused visuals without duplicating separate Verbal topics',()=>{const blocks=vocabularyWordMeaningLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(8);expect(visuals.length).toBeGreaterThanOrEqual(12);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20);expect(visual.ariaLabel.length).toBeGreaterThan(40)}expect(lesson('vocabulary-and-word-meaning-topic-quiz')).toContain('separate Synonyms and Antonyms or Context Clues courses');expect(synonymsSource).toContain("topicSlug = 'synonyms-and-antonyms'");expect(contextCluesSource).toContain("topicSlug = 'context-clues'")})
 it('preserves generators, fixed practice, quiz, Smart Recovery, assessment, and completed Numerical systems',()=>{for(const slug of ['root-word-meaning','prefix-meaning','suffix-meaning','word-family-form','denotation-connotation','multiple-meaning-word','definition-example-match','commonly-confused-words','mixed-vocabulary-word-meaning']){expect(legacySource).toContain("'"+slug+"'");expect(generatorSource).toContain("'"+slug+"'");expect(assessmentSource).toContain("'"+slug+"'")}expect(legacySource).toContain("'mixed-vocabulary-practice'");expect(legacySource).toContain("'vocabulary-and-word-meaning-topic-quiz'");expect(smartRecoverySource).toContain('numericalAbilityBlueprintV1');for(const key of ['percentages','fractions','decimals','ratio-proportion','average','number-problems','age-problems','work-rate','distance-speed-time','simple-interest'])expect(numericalRegistrySource).toContain(key)})
})
