import { describe, expect, it } from 'vitest'
import { workRateLessonSpecs } from '../scripts/lib/work-rate-teaching-system-content.mjs'
import legacySource from '../scripts/create-and-publish-work-rate-topic.mjs?raw'
import ageSource from '../scripts/lib/age-problems-teaching-system-content.mjs?raw'
import numberSource from '../scripts/lib/number-problems-teaching-system-content.mjs?raw'
import averageSource from '../scripts/lib/average-teaching-system-content.mjs?raw'
import { validateLessonBlockContent } from '../src/worker/schemas/lesson-block.schemas'
const lesson=(slug:string)=>JSON.stringify(workRateLessonSpecs.find((item)=>item.slug===slug)?.blocks)
describe('Work and Rate Teaching System v1',()=>{
 it('preserves all twelve authoritative activities, types, order, and durations',()=>{expect(workRateLessonSpecs.map(({slug,lessonType,estimatedMinutes})=>[slug,lessonType,estimatedMinutes])).toEqual([
 ['understanding-work-rates','reading',12],['individual-work-rate','practice',11],['combined-work','practice',12],['one-worker-joins-later','practice',13],['one-worker-leaves-early','practice',13],['pipes-filling-a-tank','practice',12],['pipes-filling-and-draining','practice',13],['efficiency-and-different-work-rates','practice',13],['finding-an-unknown-work-time','practice',14],['mixed-work-and-rate-problems','practice',15],['mixed-work-and-rate-practice','practice',16],['work-and-rate-topic-quiz','quiz',18]])})
 it('uses valid deterministic canonical blocks without illustrated guided teaching',()=>{for(const item of workRateLessonSpecs){expect(item.blocks[0]).toMatchObject({blockType:'heading',content:{level:1,text:item.title}});expect(item.blocks.at(-1)?.blockType).toBe('summary');expect(item.blocks.some((block)=>block.blockType==='illustrated-guided-teaching')).toBe(false);for(const block of item.blocks)expect(()=>validateLessonBlockContent(block.blockType,block.content)).not.toThrow()}})
 it('derives the one-whole-job model, reciprocal rate, partial work, and remainder',()=>{const intro=lesson('understanding-work-rates');expect(intro).toContain('one complete task');expect(intro).toContain('rate=1/t');expect(intro).toContain('not a magic rule');const individual=lesson('individual-work-rate');expect(individual).toContain('3×1/8=3/8');expect(individual).toContain('1−3/8=5/8')})
 it('adds two- and three-worker rates, uses a responsive rate-table model, and checks reasonableness',()=>{const combined=lesson('combined-work');expect(combined).toContain('Worker, Time Alone, and Rate');expect(combined).toContain('1/6+2/6=1/2');expect(combined).toContain('3/24+2/24+1/24=6/24=1/4');expect(combined).toContain('(6+3)/2=4.5 hours is wrong');expect(combined).toContain('2×1/2=1 job');expect(combined).toContain('less than the faster worker');expect(combined).toContain('T=ab/(a+b)')})
 it('handles unknown workers and join/leave phases correctly',()=>{expect(lesson('finding-an-unknown-work-time')).toContain('1/4−1/6=3/12−2/12=1/12');expect(lesson('finding-an-unknown-work-time')).toContain('B alone needs 12 hours');expect(lesson('one-worker-joins-later')).toContain('18/7 hours');expect(lesson('one-worker-leaves-early')).toContain('A needs 4 more hours');expect(lesson('one-worker-leaves-early')).toContain('zero after leaving')})
 it('teaches pipes, signed rates, physical output, compatible units, identical workers, and worker-hour limits',()=>{expect(lesson('pipes-filling-a-tank')).toContain('5/12');const drain=lesson('pipes-filling-and-draining');expect(drain).toContain('drain=−1/12');expect(drain).toContain('Net=3/12−1/12=2/12=1/6');expect(drain).toContain('negative net rate');const individual=lesson('individual-work-rate');expect(individual).toContain('120÷4=30 units/hour');expect(individual).toContain('30×7=210 units');expect(individual).toContain('120 minutes=2 hours');expect(individual).toContain('converted to the same unit');const efficiency=lesson('efficiency-and-different-work-rates');expect(efficiency).toContain('3×1/12=1/4 job/hour');expect(efficiency).toContain('5×8=40 worker-days');expect(efficiency).toContain('equal productivity');expect(efficiency).toContain('8 hours/day');expect(efficiency).toContain('6 hours/day');expect(efficiency).toContain('worker-hours');expect(lesson('mixed-work-and-rate-problems')).toContain('100 items')})
 it('uses seven accessible visuals with reasoned memory rules, common mistakes, and CTAs',()=>{const blocks=workRateLessonSpecs.flatMap((item)=>item.blocks);const visuals=blocks.flatMap((block)=>block.content.visual===undefined?[]:[block.content.visual]);expect(new Set(visuals)).toHaveLength(7);expect(visuals.length).toBeGreaterThanOrEqual(10);for(const visual of visuals){expect(visual.transitions).toHaveLength(visual.stages.length-1);expect(visual.transitions.every((transition)=>transition.whatChanged&&transition.why&&transition.source)).toBe(true);expect(visual.memoryTip.reason.length).toBeGreaterThan(20)}expect(blocks.filter((block)=>block.content.title==='Common mistake')).toHaveLength(12);for(const item of workRateLessonSpecs.filter((entry)=>entry.lessonType==='practice'))expect(JSON.stringify(item.blocks)).toContain('Practice CTA')})
 it('preserves nine generators, fixed practice, quiz, Smart Recovery source ownership, and unrelated manifests',()=>{for(const slug of ['individual-work-rate','combined-work-rate','worker-joins-later','worker-leaves-early','pipes-filling','pipes-filling-draining','efficiency-work-rates','unknown-work-time','mixed-work-rate'])expect(legacySource).toContain(`'${slug}'`);expect(legacySource).toContain("validateFixedQuestions('Mixed Work and Rate Practice'");expect(legacySource).toContain("validateFixedQuestions('Work and Rate Topic Quiz'");expect(legacySource).toContain('passingScore: 70');expect(ageSource).toContain("slug:'understanding-age-relationships'");expect(numberSource).toContain("slug:'translating-number-statements'");expect(averageSource).toContain("slug:'understanding-average'")})
})