import { Link } from 'react-router'
import { LearnerTopbar } from '../components/LearnerTopbar'
import { useCseReadiness, type ReadinessViewState } from '../hooks/use-readiness'
import { confidenceLabel, readinessBandLabel } from '../lib/readiness-copy'

function ScoreGauge({ score }: { score: number }) {
  return <div className="readiness-gauge" style={{ '--readiness-score': `${score * 3.6}deg` } as React.CSSProperties} role="img" aria-label={`CSE Readiness Score: ${score} out of 100`}><div><strong>{score}</strong><span>out of 100</span></div></div>
}
export function ReadinessPageView({ state }: { state: ReadinessViewState }) {
  return <main className="page-shell readiness-page" data-testid="readiness-page">
    <LearnerTopbar as="header" showSignOut><Link className="button-link button-link--secondary" to="/dashboard">Dashboard</Link><Link className="button-link button-link--secondary" to="/mistake-notebook">Mistake Notebook</Link></LearnerTopbar>
    {state.status === 'loading' && <section className="readiness-state" aria-live="polite" aria-busy="true"><p>Calculating your readiness...</p></section>}
    {state.status === 'error' && <section className="readiness-state" role="alert"><h1>CSE Readiness could not be loaded</h1><p>{state.error}</p><button type="button" onClick={state.reload}>Try again</button></section>}
    {state.status === 'loaded' && <>
      <header className="readiness-hero"><div><p className="eyebrow">CSE Readiness</p><h1>{state.data.hasSufficientEvidence ? readinessBandLabel(state.data.readinessBand) : 'Not enough evidence for a reliable readiness estimate yet.'}</h1><p>{state.data.confidenceExplanation}</p><p className="readiness-confidence"><strong>Confidence:</strong> {confidenceLabel(state.data.confidence)}</p></div><ScoreGauge score={state.data.score} /></header>
      <section className="readiness-section" aria-labelledby="component-breakdown-title"><div className="readiness-section__heading"><p className="eyebrow">Explainable score</p><h2 id="component-breakdown-title">Component breakdown</h2></div><div className="readiness-component-grid">{state.data.components.map((component) => <article key={component.key} className="readiness-component"><div><h3>{component.title}</h3><strong>{component.contribution} / {component.maximum}</strong></div><div className="readiness-bar" role="progressbar" aria-label={`${component.title}: ${component.contribution} out of ${component.maximum}`} aria-valuemin={0} aria-valuemax={component.maximum} aria-valuenow={component.contribution}><span style={{ width: `${component.contribution / component.maximum * 100}%` }} /></div><p>{component.explanation}</p></article>)}</div></section>
      <section className="readiness-section" aria-labelledby="subject-readiness-title"><div className="readiness-section__heading"><p className="eyebrow">Four subject view</p><h2 id="subject-readiness-title">Subject readiness</h2></div><div className="readiness-subject-grid">{state.data.subjects.map((subject) => <article key={subject.slug} className="readiness-subject"><div><h3>{subject.title}</h3><span className="readiness-label">{subject.readinessLabel}</span></div>{subject.readinessPercent === null ? <p>No reliable percentage yet.</p> : <><strong>{subject.readinessPercent}%</strong><div className="readiness-bar" role="progressbar" aria-label={`${subject.title} readiness: ${subject.readinessPercent}%`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={subject.readinessPercent}><span style={{ width: `${subject.readinessPercent}%` }} /></div></>}<p className="meta-copy">Assessment: {subject.latestAssessmentScorePercent === null ? 'not submitted' : `${subject.latestAssessmentScorePercent}%`} · Strong skills: {subject.skillStatusCounts.strong} · Improving: {subject.skillStatusCounts.improving}</p></article>)}</div></section>
      <div className="readiness-signal-grid"><section className="readiness-section" aria-labelledby="positive-signals-title"><h2 id="positive-signals-title">What's helping</h2>{state.data.positiveSignals.length === 0 ? <p>Submit more work to reveal positive readiness signals.</p> : <ul>{state.data.positiveSignals.map((signal) => <li key={signal.title}><strong>{signal.title}</strong><span>{signal.detail}</span></li>)}</ul>}</section><section className="readiness-section" aria-labelledby="limiters-title"><h2 id="limiters-title">What's holding you back</h2>{state.data.limiters.length === 0 ? <p>No major limiter is visible in the current evidence.</p> : <ul>{state.data.limiters.map((signal) => <li key={signal.title}><strong>{signal.title}</strong><span>{signal.detail}</span></li>)}</ul>}</section></div>
      <section className="readiness-recommendation" aria-labelledby="readiness-next-title"><div><p className="eyebrow">Recommended next</p><h2 id="readiness-next-title">{state.data.recommendation.title}</h2><p>{state.data.recommendation.detail}</p></div><Link className="button-link" to={state.data.recommendation.route}>{state.data.recommendation.actionLabel}</Link></section>
      <section className="readiness-evidence-note"><h2>Evidence behind this estimate</h2><p>This estimate uses submitted generated practice, subject assessments, Smart Recovery skill evidence, and full mock results where available.</p><dl><div><dt>Mock attempts</dt><dd>{state.data.evidence.mockAttemptCount}</dd></div><div><dt>Subjects assessed</dt><dd>{state.data.evidence.subjectsAssessed} of 4</dd></div><div><dt>Observed skills</dt><dd>{state.data.evidence.observedSkillCount}</dd></div><div><dt>Recent practice questions</dt><dd>{state.data.evidence.recentPracticeQuestionCount}</dd></div></dl><p className="meta-copy">{state.data.disclaimer}</p></section>
    </>}
  </main>
}
export function ReadinessPage() { return <ReadinessPageView state={useCseReadiness()} /> }
