import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router'
import { fetchSubjectAssessmentAttempt, saveSubjectAssessmentChoice, submitSubjectAssessment, type SubjectAssessmentAttempt } from '../lib/api'

export function SubjectAssessmentAttemptPage() {
  const { attemptPublicId = '' } = useParams(); const navigate = useNavigate()
  const [data, setData] = useState<SubjectAssessmentAttempt | null>(null); const [index, setIndex] = useState(0); const [reviewing, setReviewing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { const controller = new AbortController(); fetchSubjectAssessmentAttempt(attemptPublicId, controller.signal).then(setData).catch((value: unknown) => { if (!controller.signal.aborted) setError(value instanceof Error ? value.message : 'Attempt could not be loaded.') }); return () => controller.abort() }, [attemptPublicId])
  async function choose(questionId: string, choiceId: string) { if (data === null) return; const previous = data; setData({ ...data, questions: data.questions.map((question) => question.publicId === questionId ? { ...question, selectedChoicePublicId: choiceId } : question), answeredCount: data.questions.filter((question) => question.publicId === questionId ? true : question.selectedChoicePublicId !== null).length }); setSaving(true); try { await saveSubjectAssessmentChoice(attemptPublicId, questionId, choiceId) } catch (value) { setData(previous); setError(value instanceof Error ? value.message : 'Answer could not be saved.') } finally { setSaving(false) } }
  async function submit() { if (data === null) return; const unanswered = data.totalCount - data.answeredCount; if (!window.confirm(`${unanswered > 0 ? `${unanswered} questions are unanswered. ` : ''}Submit this final assessment? Answers cannot be changed afterward.`)) return; try { await submitSubjectAssessment(attemptPublicId); await navigate(`/assessment-attempts/${attemptPublicId}/results`) } catch (value) { setError(value instanceof Error ? value.message : 'Assessment could not be submitted.') } }
  if (error !== null && data === null) return <main className="assessment-shell"><p className="form-error">{error}</p></main>; if (data === null) return <main className="assessment-shell"><p>Restoring your attempt…</p></main>
  if (reviewing) return <main className="assessment-shell"><h1>Review before submission</h1><p>{data.answeredCount} of {data.totalCount} answered.</p><div className="question-navigator">{data.questions.map((question, position) => <button className={question.selectedChoicePublicId === null ? 'unanswered' : 'answered'} key={question.publicId} onClick={() => { setIndex(position); setReviewing(false) }}>{position + 1}</button>)}</div><button type="button" onClick={() => void submit()}>Confirm and submit</button><button className="button-secondary" type="button" onClick={() => setReviewing(false)}>Return to questions</button></main>
  const question = data.questions[index]!; return <main className="assessment-shell"><header><p className="eyebrow">{data.assessment.title}</p><h1>Question {index + 1} of {data.totalCount}</h1><p>{data.answeredCount} answered {saving ? '· Saving…' : '· Saved'}</p></header>{error !== null && <p className="form-error">{error}</p>}<div className="question-navigator" aria-label="Question navigator">{data.questions.map((item, position) => <button aria-label={`Question ${position + 1}${item.selectedChoicePublicId === null ? ', unanswered' : ', answered'}`} className={`${position === index ? 'current' : ''} ${item.selectedChoicePublicId === null ? 'unanswered' : 'answered'}`} key={item.publicId} onClick={() => setIndex(position)}>{position + 1}</button>)}</div><section className="dashboard-card assessment-question"><h2>{question.prompt}</h2>{question.choices.map((choice) => <label className={`assessment-choice ${question.selectedChoicePublicId === choice.publicId ? 'selected' : ''}`} key={choice.publicId}><input type="radio" name={question.publicId} checked={question.selectedChoicePublicId === choice.publicId} onChange={() => void choose(question.publicId, choice.publicId)} />{choice.text}</label>)}</section><div className="assessment-actions"><button className="button-secondary" disabled={index === 0} onClick={() => setIndex((value) => value - 1)}>Previous</button>{index < data.totalCount - 1 ? <button onClick={() => setIndex((value) => value + 1)}>Next</button> : <button onClick={() => setReviewing(true)}>Review answers</button>}</div></main>
}
