import type { GeneratorDifficulty } from '../../generators/generator.types'
import type { PeaceHumanRightsCategory,PeaceHumanRightsConceptClass,PeaceHumanRightsEntry,PeaceHumanRightsMistakeType,PeaceHumanRightsSourceType } from './peace-human-rights.types'
type SourceKey='constitution'|'udhr'|'iccpr'|'icescr'|'ohchr'|'chr'|'unPeace'|'unMediation'
const sources:Record<SourceKey,{title:string;url:string;type:PeaceHumanRightsSourceType;institution:string;classification:'philippine'|'international'}>={
 constitution:{title:'1987 Constitution of the Republic of the Philippines',url:'https://lawphil.net/consti/cons1987.html',type:'constitution',institution:'Republic of the Philippines',classification:'philippine'},
 udhr:{title:'Universal Declaration of Human Rights',url:'https://www.un.org/en/about-us/universal-declaration-of-human-rights/',type:'declaration',institution:'United Nations General Assembly',classification:'international'},
 iccpr:{title:'International Covenant on Civil and Political Rights',url:'https://2covenants.ohchr.org/About-ICCPR.html',type:'treaty',institution:'United Nations',classification:'international'},
 icescr:{title:'International Covenant on Economic, Social and Cultural Rights',url:'https://2covenants.ohchr.org/About-ICESCR.html',type:'treaty',institution:'United Nations',classification:'international'},
 ohchr:{title:'What Are Human Rights?',url:'https://www.bangkok.ohchr.org/what-are-human-rights',type:'un_educational_material',institution:'Office of the UN High Commissioner for Human Rights',classification:'international'},
 chr:{title:'Commission on Human Rights Constitutional Mandate',url:'https://chr.gov.ph/about-us/',type:'constitutional_mandate',institution:'Commission on Human Rights of the Philippines',classification:'philippine'},
 unPeace:{title:'United Nations Peacekeeping Terminology',url:'https://peacekeeping.un.org/en/terminology',type:'un_educational_material',institution:'United Nations',classification:'international'},
 unMediation:{title:'United Nations Guidance for Effective Mediation',url:'https://dppa.dfs.un.org/en/united-nations-guidance-effective-mediation',type:'un_educational_material',institution:'UN Department of Political and Peacebuilding Affairs',classification:'international'},
}
const mistakes:Record<PeaceHumanRightsCategory,readonly PeaceHumanRightsMistakeType[]>={dignity_universality:['phr_rights_citizens_only','phr_rights_unlimited','phr_equality_identical'],civil_political:['phr_rights_unlimited','phr_nonviolence_inaction','phr_rights_citizens_only'],economic_social_cultural:['phr_escr_charity_only','phr_rights_unlimited','phr_treaty_body_domestic'],equality_nondiscrimination:['phr_equality_identical','phr_rights_citizens_only','phr_rights_unlimited'],rights_responsibilities:['phr_rights_unlimited','phr_nonviolence_inaction','phr_rights_citizens_only'],peace_conflict_nonviolence:['phr_conflict_is_violence','phr_peace_is_silence','phr_nonviolence_inaction'],conflict_prevention_resolution:['phr_conflict_is_violence','phr_nonviolence_inaction','phr_peace_is_silence'],peacebuilding:['phr_reconciliation_impunity','phr_peace_is_silence','phr_nonviolence_inaction'],institutions:['phr_chr_is_court','phr_treaty_body_domestic','phr_rights_unlimited']}
const wrongs:Record<PeaceHumanRightsCategory,readonly string[]>={dignity_universality:['Human rights belong only to citizens who have earned them.','Every right is unlimited in every circumstance.','Equality always requires identical treatment regardless of barriers.'],civil_political:['Freedom of expression protects every act without lawful limits.','Peaceful participation means remaining inactive and silent.','Civil and political rights belong only to citizens in every setting.'],economic_social_cultural:['Economic, social, and cultural rights are optional charity only.','Every listed service must be delivered immediately without regard to the applicable framework.','A treaty body is a domestic agency that administers every social program.'],equality_nondiscrimination:['Equality always means identical treatment in every circumstance.','Only citizens may receive non-discriminatory public service.','Equal protection removes every lawful distinction or limitation.'],rights_responsibilities:['Exercising a right means the rights of others never matter.','Responsible participation requires silence and inaction.','Only citizens have responsibilities toward the community.'],peace_conflict_nonviolence:['Every disagreement is itself violence.','Silence and the absence of complaint always prove peace.','Nonviolence requires passivity even when lawful help is needed.'],conflict_prevention_resolution:['Every disagreement must be treated as violent conflict.','A mediator imposes a binding outcome on unwilling parties.','Reporting a serious threat is contrary to peaceful resolution.'],peacebuilding:['Reconciliation removes the need for accountability.','Peacebuilding ends as soon as open violence stops.','Only security forces can participate in building peace.'],institutions:['The CHR is a criminal court that automatically convicts people.','A United Nations treaty body is a Philippine domestic court.','Every complaint belongs to the same institution and process.']}
function entry(id:string,category:PeaceHumanRightsCategory,conceptClass:PeaceHumanRightsConceptClass,difficulty:GeneratorDifficulty,concept:string,explanation:string,sourceKey:SourceKey,provisionId:string,exactTerms:readonly string[],misconception:string,scenario:string):PeaceHumanRightsEntry{const source=sources[sourceKey];return{id,category,conceptClass,concept,explanation,exactTerms,misconception,scenarioTemplates:[scenario],difficulty,distractors:wrongs[category].map((text,index)=>({text,mistakeType:mistakes[category][index] as PeaceHumanRightsMistakeType})),source:{sourceTitle:source.title,sourceUrl:source.url,sourceType:source.type,provisionId,institution:source.institution,classification:source.classification,verificationDate:'2026-08-04',contentVersion:'peace-human-rights-v1',paraphrasedRule:explanation},active:true}}
export const peaceHumanRightsBankV1:readonly PeaceHumanRightsEntry[]=[
 entry('dignity-constitutional','dignity_universality','dignity','easy','human dignity','The Constitution values the dignity of every human person and guarantees full respect for human rights.','constitution','Article II, Section 11',['dignity of every human person','full respect for human rights'],'Dignity is a favor distributed by government.','A public office designs a service around respect for every person.'),
 entry('universality-inherent','dignity_universality','universality','medium','universality and inherence','Human rights are inherent to all human beings without distinction; they are not rewards earned through employment, status, or popularity.','ohchr','OHCHR Principles, Universal and Inalienable',['inherent','universal','without discrimination'],'Rights apply only to citizens or popular groups.','A school applies a dignity-based policy to every learner.'),
 entry('indivisible-interdependent','dignity_universality','universality','hard','indivisibility and interdependence','Human rights are interrelated, interdependent, and indivisible, so realizing one right can support the enjoyment of others without making every right legally identical.','ohchr','OHCHR Principles, Interdependent and Indivisible',['interrelated','interdependent','indivisible'],'One category of rights always exists independently of all others.','Education access helps a resident participate meaningfully in public affairs.'),
 entry('due-process-equal-protection','civil_political','civil','easy','due process and equal protection','The Philippine Bill of Rights protects persons against deprivation of life, liberty, or property without due process and against denial of equal protection of the laws.','constitution','Article III, Section 1',['due process','equal protection'],'Due process guarantees the outcome a person prefers.','A public institution follows a fair process before making an adverse decision.'),
 entry('expression-assembly','civil_political','civil','medium','expression and peaceful assembly','The Constitution protects speech, expression, the press, peaceful assembly, and petition, while the word peaceful distinguishes protected assembly from violence.','constitution','Article III, Section 4',['freedom of speech','peaceably to assemble','petition the government'],'Expression and assembly have no constitutional or lawful limits.','Residents hold a peaceful meeting and submit a petition.'),
 entry('participation-public-affairs','civil_political','political','hard','participation in public affairs','The ICCPR recognizes participation in public affairs, voting, election, and equal access to public service subject to the Covenantâ€™s framework and lawful conditions.','iccpr','ICCPR Article 25',['public affairs','vote','public service'],'Political rights mean every preferred candidate or policy must prevail.','Eligible citizens participate through lawful public processes.'),
 entry('right-to-work','economic_social_cultural','economic','easy','work and just conditions','The ICESCR recognizes the right to work and just and favorable conditions; the right is broader than any single government employment program.','icescr','ICESCR Article 6',['right to work','freely chooses or accepts'],'A temporary program fully defines the right to work.','A workplace improves fair access and safe conditions.'),
 entry('education-right','economic_social_cultural','social','medium','education','The ICESCR recognizes education directed to full development of the human personality and dignity and to effective participation in a free society.','icescr','ICESCR Article 13',['right to education','human personality','sense of dignity'],'Education is optional charity with no rights dimension.','A school removes an unnecessary access barrier.'),
 entry('progressive-realization','economic_social_cultural','social','hard','progressive realization','ICESCR Article 2 requires States Parties to take steps, using the maximum of available resources, toward progressive realization by appropriate means; this does not mean that no present duties exist.','icescr','ICESCR Article 2',['take steps','maximum of available resources','progressively'],'Progressive realization excuses permanent inaction.','An agency adopts measurable steps toward broader service access.'),
 entry('equal-dignity','equality_nondiscrimination','equality','easy','equality in dignity and rights','The UDHR states that all human beings are born free and equal in dignity and rights.','udhr','UDHR Article 1',['free and equal','dignity and rights'],'Majority preference determines whose dignity counts.','A public counter treats every visitor with equal respect.'),
 entry('non-discrimination','equality_nondiscrimination','equality','medium','non-discrimination','The UDHR applies its rights and freedoms without distinction on the listed or comparable status grounds; popularity is not a basis for fewer rights.','udhr','UDHR Article 2',['without distinction','rights and freedoms'],'Unpopular groups have fewer rights.','A service rule is applied without unjust exclusion.'),
 entry('equality-not-identical','equality_nondiscrimination','equality','hard','equality and relevant differences','Equal protection does not mean every factual situation must receive mechanically identical treatment; distinctions require a legitimate, lawful basis rather than prejudice.','constitution','Article III, Section 1',['equal protection','lawful distinction'],'Fairness always means ignoring different access barriers.','A public service adjusts an access method while preserving equal standards.'),
 entry('respect-rights-others','rights_responsibilities','responsibility','easy','respect for the rights of others','The UDHR places each person in community and allows only lawful limitations directed to respect for othersâ€™ rights and the general welfare in a democratic society.','udhr','UDHR Article 29',['duties to the community','rights and freedoms of others'],'Rights depend on first proving good behavior.','A speaker criticizes policy without obstructing another personâ€™s lawful participation.'),
 entry('responsible-communication','rights_responsibilities','responsibility','medium','responsible exercise of expression','Responsible communication can combine protected expression with accuracy, respect for others, and lawful processes; responsibility does not require political conformity.','constitution','Article III, Section 4',['speech','expression','petition'],'Peaceful criticism is disloyal and must stop.','Employees raise a concern through a documented, nonviolent channel.'),
 entry('lawful-remedies','rights_responsibilities','responsibility','hard','lawful remedies and accountability','Rights may be asserted through appropriate institutions and lawful remedies; people need not engage in confrontation or unauthorized intervention.','constitution','Article III, Section 11',['access to courts','adequate legal assistance'],'A person should personally confront danger instead of seeking lawful help.','A resident records a concern through the proper assistance channel.'),
 entry('conflict-not-violence','peace_conflict_nonviolence','peace','easy','conflict and violence','Conflict is disagreement or incompatibility and does not automatically become violence; early communication can keep disputes from escalating.','unPeace','UN Terminology, Conflict prevention',['conflict prevention','escalating'],'Every disagreement is violence.','Coworkers disagree about scheduling and begin a structured discussion.'),
 entry('negative-positive-peace','peace_conflict_nonviolence','peace','medium','negative and positive peace','As an educational distinction, negative peace emphasizes absence of open violence, while positive peace adds conditions supporting justice, inclusion, cooperation, and sustainable peace.','unPeace','UN Terminology, Peacebuilding',['sustainable peace','necessary conditions'],'Silence proves that justice and inclusion already exist.','A community pairs calm conditions with inclusive problem solving.'),
 entry('nonviolence-active','peace_conflict_nonviolence','peace','hard','nonviolence and safe action','Nonviolent action can include dialogue, peaceful participation, de-escalation, and seeking lawful assistance; it does not require passivity in an unsafe situation.','constitution','Article II, Section 2',['policy of peace','justice','cooperation'],'Reporting threats is contrary to peace.','A person steps away from escalating danger and contacts proper authorities.'),
 entry('early-prevention','conflict_prevention_resolution','conflict_resolution','easy','early conflict prevention','Conflict prevention uses early warning, information, and analysis to keep tensions or disputes from escalating into violent conflict.','unPeace','UN Terminology, Conflict prevention',['early warning','prevent escalation'],'Prevention begins only after violence ends.','A workplace notices repeated misunderstandings and clarifies roles early.'),
 entry('negotiation-dialogue','conflict_prevention_resolution','conflict_resolution','medium','negotiation and dialogue','Negotiation lets parties address disagreement and seek a joint decision without giving an outside person authority to impose the result.','unMediation','UN Guidance, Negotiation',['negotiation','joint decision'],'Negotiation always produces a binding imposed decision.','Two teams discuss interests and possible scheduling changes.'),
 entry('mediation-role','conflict_prevention_resolution','conflict_resolution','hard','mediation','Mediation is a consent-based process in which an impartial third party assists communication and possible agreement rather than adjudicating or imposing a result.','unMediation','UN Guidance, Effective Mediation',['consent','impartiality','inclusivity'],'A mediator decides who wins and imposes punishment.','Coworkers voluntarily ask an impartial facilitator to help them communicate.'),
 entry('peacebuilding-long-term','peacebuilding','peacebuilding','easy','peacebuilding','Peacebuilding is a complex, long-term effort to reduce recurrence risk, strengthen conflict-management capacities, and create conditions for sustainable peace.','unPeace','UN Terminology, Peacebuilding',['long-term process','sustainable peace','reduce risk'],'Peacebuilding ends when open violence stops.','A community continues trust-building after an immediate dispute settles.'),
 entry('root-causes-inclusion','peacebuilding','peacebuilding','medium','root causes and inclusion','Peacebuilding addresses underlying conditions and strengthens inclusive, legitimate institutions rather than relying only on short-term crisis response.','unPeace','UN Terminology, Peacebuilding',['root causes','national capacities','legitimate'],'Community participation is irrelevant to peacebuilding.','Residents and institutions jointly address recurring access barriers.'),
 entry('reconciliation-accountability','peacebuilding','peacebuilding','hard','reconciliation and accountability','Reconciliation can support restored relationships and non-recurrence without erasing accountability or requiring anyone to forgive.','unPeace','UN Terminology, Sustainable peace',['reconciliation','justice','non-recurrence'],'Reconciliation requires impunity and compelled forgiveness.','A dialogue process preserves accountability and voluntary participation.'),
 entry('chr-mandate','institutions','institution','easy','Commission on Human Rights mandate','The CHR is an independent constitutional office with powers including investigation of human-rights violations involving civil and political rights, protection, monitoring, education, and recommendations; it is not a criminal court.','chr','Article XIII, Sections 17-18',['independent office','investigate','monitor','education'],'The CHR automatically convicts alleged offenders.','A person seeks information about the CHRâ€™s investigative and protective mandate.'),
 entry('ombudsman-accountability','institutions','institution','medium','Ombudsman accountability role','The Ombudsman may investigate acts or omissions of public officials that appear illegal, unjust, improper, or inefficient; this accountability role is distinct from the CHR mandate and judicial adjudication.','constitution','Article XI, Section 13',['investigate','public official','illegal, unjust, improper, or inefficient'],'Every human-rights concern belongs to one institution.','A complaint concerns allegedly improper performance by a public employee.'),
 entry('treaty-body-role','institutions','institution','hard','international treaty body','The Human Rights Committee established by the ICCPR is an international treaty body; it is not a Philippine criminal court or domestic prosecuting agency.','iccpr','ICCPR Article 28',['Human Rights Committee','treaty body'],'Treaty bodies are domestic courts that convict individuals.','A learner distinguishes international monitoring from domestic adjudication.'),
]
export function entriesForPeaceHumanRightsCategory(category:PeaceHumanRightsCategory):readonly PeaceHumanRightsEntry[]{return peaceHumanRightsBankV1.filter((entry)=>entry.active&&entry.category===category)}
export function findPeaceHumanRightsEntry(id:string):PeaceHumanRightsEntry|null{return peaceHumanRightsBankV1.find((entry)=>entry.id===id)??null}
