import type { PeaceHumanRightsEntry,PeaceHumanRightsSource } from './peace-human-rights.types'
const provisions=[/^Article [IVXLCDM]+, Section \d+$/u,/^UDHR Article (?:[1-9]|[12]\d|30)$/u,/^ICCPR Article (?:[1-9]|[12]\d|3[01])$/u,/^ICESCR Article (?:[1-9]|1[0-5])$/u,/^Article XIII, Sections 17-18$/u,/^UN (?:Terminology|Guidance), [A-Za-z][A-Za-z -]+$/u,/^OHCHR Principles, [A-Za-z][A-Za-z -]+$/u]
export function validPeaceHumanRightsProvision(value:string):boolean{return provisions.some((pattern)=>pattern.test(value))}
export function peaceHumanRightsSourceComplete(source:PeaceHumanRightsSource):boolean{return source.sourceTitle.length>0&&/^https:\/\//u.test(source.sourceUrl)&&validPeaceHumanRightsProvision(source.provisionId)&&source.institution.length>0&&source.verificationDate==='2026-08-04'&&source.contentVersion==='peace-human-rights-v1'&&source.paraphrasedRule.length>0}
export function rejectsCurrentPersonContent(value:string):boolean{return !/\b(incumbent|current officeholder|current candidate|President Marcos|Sara Duterte|named official|named victim|named perpetrator|pending case|recent controversy)\b/iu.test(value)}
export function rejectsPartisanOrActiveDispute(value:string):boolean{return !/\b(active political dispute|current armed conflict|partisan campaign|support the ruling party|oppose the opposition|alleged violation by)\b/iu.test(value)}
export function scenarioIsSafe(value:string):boolean{return !/\b(graphic|gory|sexual violence|child victimization|personally confront an armed|collect evidence secretly|retaliate|vigilante|torture details)\b/iu.test(value)}
export function rejectsUnsafeAdvice(value:string):boolean{return !/\b(must personally mediate danger|confront the attacker|ignore emergency services|take the law into your own hands)\b/iu.test(value)}
export function rejectsUnsupportedTreatyClaim(value:string):boolean{return !/\b(treaty bodies automatically convict|automatically overrides every domestic law|guarantees immediate delivery of every service|progressive realization means no present duty)\b/iu.test(value)}
export function institutionRoleValid(entry:PeaceHumanRightsEntry):boolean{return entry.category!=='institutions'||(!/\bCHR (?:convicts|prosecutes|sentences|acts as a criminal court)\b/iu.test(entry.explanation)&&!(/treaty bod/iu.test(entry.concept)&&/domestic (?:court|agency)/iu.test(entry.explanation)))}
export function categoryClassificationValid(entry:PeaceHumanRightsEntry):boolean{const allowed:Record<PeaceHumanRightsEntry['category'],readonly PeaceHumanRightsEntry['conceptClass'][]>= {dignity_universality:['dignity','universality'],civil_political:['civil','political'],economic_social_cultural:['economic','social','cultural'],equality_nondiscrimination:['equality'],rights_responsibilities:['responsibility'],peace_conflict_nonviolence:['peace'],conflict_prevention_resolution:['conflict_resolution'],peacebuilding:['peacebuilding'],institutions:['institution']};return allowed[entry.category].includes(entry.conceptClass)}
export function uniqueVisibleChoices(choices:readonly string[]):boolean{return choices.length===4&&choices.every((choice)=>choice.trim().length>0)&&new Set(choices.map((choice)=>choice.trim().toLowerCase())).size===4}
export function uniquePeaceHumanRightsAnswer(choices:readonly string[],answer:string):boolean{return choices.filter((choice)=>choice===answer).length===1}
