import type { AgreementEntry } from './subject-verb-agreement.types'

const entry = (value: AgreementEntry): AgreementEntry => value
const common = { tense: 'simple_present', nearerSubjectNumber: null, indefiniteClass: null, controllingNoun: null, collectiveAsUnit: null, invertedSubject: null, specialCase: null } as const
const wrongSingular = [{ text: 'submit', mistakeType: 'agreement_plural_for_singular' }, { text: 'submitted', mistakeType: 'agreement_plural_for_singular' }, { text: 'submitting', mistakeType: 'agreement_plural_for_singular' }] as const
const wrongAre = [{ text: 'is', mistakeType: 'agreement_singular_for_plural' }, { text: 'was', mistakeType: 'agreement_singular_for_plural' }, { text: 'be', mistakeType: 'agreement_singular_for_plural' }] as const

export const subjectVerbAgreementBankV1: readonly AgreementEntry[] = [
  entry({ ...common, id: 'basic-applicant-easy', skill: 'basic', sentenceTemplate: 'The applicant ____ the form.', grammaticalSubject: 'The applicant', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'submit', correctForm: 'submits', ruleFamily: 'basic', ruleDetail: 'A singular third-person subject takes submits.', completedSentence: 'The applicant submits the form.', difficulty: 'easy', distractors: wrongSingular, explanationRationale: 'Applicant is singular, so the simple-present verb is submits.' }),
  entry({ ...common, id: 'basic-applicants-medium', skill: 'basic', sentenceTemplate: 'The applicants ____ the form.', grammaticalSubject: 'The applicants', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'submit', correctForm: 'submit', ruleFamily: 'basic', ruleDetail: 'A plural subject takes the base verb submit.', completedSentence: 'The applicants submit the form.', difficulty: 'medium', distractors: [{ text: 'submits', mistakeType: 'agreement_singular_for_plural' }, { text: 'submitted', mistakeType: 'agreement_singular_for_plural' }, { text: 'submitting', mistakeType: 'agreement_singular_for_plural' }], explanationRationale: 'Applicants is plural, so it takes the base form submit.' }),
  entry({ ...common, id: 'basic-she-have-hard', skill: 'basic', sentenceTemplate: 'She ____ responsibility for the records.', grammaticalSubject: 'She', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'have', correctForm: 'has', ruleFamily: 'basic', ruleDetail: 'Third-person singular have changes to has.', completedSentence: 'She has responsibility for the records.', difficulty: 'hard', distractors: [{ text: 'have', mistakeType: 'agreement_plural_for_singular' }, { text: 'having', mistakeType: 'agreement_plural_for_singular' }, { text: 'had', mistakeType: 'agreement_plural_for_singular' }], explanationRationale: 'The singular pronoun she requires has in the simple present.' }),

  entry({ ...common, id: 'compound-manager-easy', skill: 'compound', sentenceTemplate: 'The manager and the clerk ____ present.', grammaticalSubject: 'The manager and the clerk', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'compound', ruleDetail: 'Two subjects joined by and normally take a plural verb.', completedSentence: 'The manager and the clerk are present.', difficulty: 'easy', distractors: [{ text: 'is', mistakeType: 'agreement_and_as_or' }, { text: 'was', mistakeType: 'agreement_and_as_or' }, { text: 'be', mistakeType: 'agreement_and_as_or' }], explanationRationale: 'Manager and clerk form a plural compound subject.' }),
  entry({ ...common, id: 'compound-every-medium', skill: 'compound', sentenceTemplate: 'Every desk and chair ____ labeled.', grammaticalSubject: 'Every desk and chair', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'compound', ruleDetail: 'Every before compound singular nouns requires singular agreement.', completedSentence: 'Every desk and chair is labeled.', difficulty: 'medium', distractors: [{ text: 'are', mistakeType: 'agreement_and_as_or' }, { text: 'were', mistakeType: 'agreement_and_as_or' }, { text: 'be', mistakeType: 'agreement_and_as_or' }], explanationRationale: 'Every distributes the statement to each desk and chair, so is is correct.' }),
  entry({ ...common, id: 'compound-tasks-hard', skill: 'compound', sentenceTemplate: 'Planning and filing ____ careful attention.', grammaticalSubject: 'Planning and filing', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'require', correctForm: 'require', ruleFamily: 'compound', ruleDetail: 'Two distinct activities joined by and take a plural verb.', completedSentence: 'Planning and filing require careful attention.', difficulty: 'hard', distractors: [{ text: 'requires', mistakeType: 'agreement_and_as_or' }, { text: 'required', mistakeType: 'agreement_and_as_or' }, { text: 'requiring', mistakeType: 'agreement_and_as_or' }], explanationRationale: 'Planning and filing name two distinct activities and require plural agreement.' }),

  entry({ ...common, id: 'proximity-singular-easy', skill: 'proximity', sentenceTemplate: 'Either the clerk or the manager ____ attending.', grammaticalSubject: 'Either the clerk or the manager', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'proximity', ruleDetail: 'With either/or, agree with the nearer subject manager.', nearerSubjectNumber: 'singular', completedSentence: 'Either the clerk or the manager is attending.', difficulty: 'easy', distractors: [{ text: 'are', mistakeType: 'agreement_wrong_proximity' }, { text: 'were', mistakeType: 'agreement_wrong_proximity' }, { text: 'be', mistakeType: 'agreement_wrong_proximity' }], explanationRationale: 'Manager is the nearer singular subject, so is is correct.' }),
  entry({ ...common, id: 'proximity-plural-medium', skill: 'proximity', sentenceTemplate: 'Either the manager or the clerks ____ attending.', grammaticalSubject: 'Either the manager or the clerks', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'proximity', ruleDetail: 'With either/or, agree with the nearer subject clerks.', nearerSubjectNumber: 'plural', completedSentence: 'Either the manager or the clerks are attending.', difficulty: 'medium', distractors: [{ text: 'is', mistakeType: 'agreement_wrong_proximity' }, { text: 'was', mistakeType: 'agreement_wrong_proximity' }, { text: 'be', mistakeType: 'agreement_wrong_proximity' }], explanationRationale: 'Clerks is the nearer plural subject, so are is correct.' }),
  entry({ ...common, id: 'proximity-neither-hard', skill: 'proximity', sentenceTemplate: 'Neither the folder nor the files ____ missing.', grammaticalSubject: 'Neither the folder nor the files', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'proximity', ruleDetail: 'With neither/nor, agree with the nearer subject files.', nearerSubjectNumber: 'plural', completedSentence: 'Neither the folder nor the files are missing.', difficulty: 'hard', distractors: [{ text: 'is', mistakeType: 'agreement_wrong_proximity' }, { text: 'was', mistakeType: 'agreement_wrong_proximity' }, { text: 'be', mistakeType: 'agreement_wrong_proximity' }], explanationRationale: 'Files is nearest the verb and is plural, so are is correct.' }),

  entry({ ...common, id: 'indefinite-each-easy', skill: 'indefinite', sentenceTemplate: 'Each of the reports ____ complete.', grammaticalSubject: 'Each', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'indefinite', ruleDetail: 'Each is a singular indefinite pronoun.', indefiniteClass: 'singular', controllingNoun: 'Each', completedSentence: 'Each of the reports is complete.', difficulty: 'easy', distractors: [{ text: 'are', mistakeType: 'agreement_indefinite_as_plural' }, { text: 'were', mistakeType: 'agreement_nearest_noun' }, { text: 'be', mistakeType: 'agreement_indefinite_as_plural' }], explanationRationale: 'Each, not reports, is the singular grammatical subject.' }),
  entry({ ...common, id: 'indefinite-several-medium', skill: 'indefinite', sentenceTemplate: 'Several ____ waiting for assistance.', grammaticalSubject: 'Several', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'indefinite', ruleDetail: 'Several is a plural indefinite pronoun.', indefiniteClass: 'plural', controllingNoun: 'Several', completedSentence: 'Several are waiting for assistance.', difficulty: 'medium', distractors: wrongAre, explanationRationale: 'Several is plural and therefore takes are.' }),
  entry({ ...common, id: 'indefinite-some-water-hard', skill: 'indefinite', sentenceTemplate: 'Some of the water ____ unavailable.', grammaticalSubject: 'Some of the water', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'indefinite', ruleDetail: 'Some agrees with the mass noun after of.', indefiniteClass: 'context', controllingNoun: 'water', completedSentence: 'Some of the water is unavailable.', difficulty: 'hard', distractors: [{ text: 'are', mistakeType: 'agreement_quantity_as_plural' }, { text: 'were', mistakeType: 'agreement_quantity_as_plural' }, { text: 'be', mistakeType: 'agreement_quantity_as_plural' }], explanationRationale: 'Water is a mass noun, so some of the water takes is.' }),

  entry({ ...common, id: 'collective-committee-easy', skill: 'collective_quantity', sentenceTemplate: 'The committee ____ meeting today as one body.', grammaticalSubject: 'The committee', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'collective_quantity', ruleDetail: 'A collective noun acting as one unit is singular.', collectiveAsUnit: true, controllingNoun: 'committee', completedSentence: 'The committee is meeting today as one body.', difficulty: 'easy', distractors: [{ text: 'are', mistakeType: 'agreement_collective_as_plural' }, { text: 'were', mistakeType: 'agreement_collective_as_plural' }, { text: 'be', mistakeType: 'agreement_collective_as_plural' }], explanationRationale: 'As one body makes the singular unit meaning explicit.' }),
  entry({ ...common, id: 'quantity-distance-medium', skill: 'collective_quantity', sentenceTemplate: 'Ten kilometers ____ a long distance to walk.', grammaticalSubject: 'Ten kilometers', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'collective_quantity', ruleDetail: 'A distance treated as one measurement takes a singular verb.', controllingNoun: 'distance', completedSentence: 'Ten kilometers is a long distance to walk.', difficulty: 'medium', distractors: [{ text: 'are', mistakeType: 'agreement_quantity_as_plural' }, { text: 'were', mistakeType: 'agreement_quantity_as_plural' }, { text: 'be', mistakeType: 'agreement_quantity_as_plural' }], explanationRationale: 'Ten kilometers is treated as one distance, so is is correct.' }),
  entry({ ...common, id: 'quantity-half-files-hard', skill: 'collective_quantity', sentenceTemplate: 'Half of the files ____ missing.', grammaticalSubject: 'Half of the files', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'collective_quantity', ruleDetail: 'A fraction agrees with the count noun after of.', controllingNoun: 'files', completedSentence: 'Half of the files are missing.', difficulty: 'hard', distractors: [{ text: 'is', mistakeType: 'agreement_quantity_as_plural' }, { text: 'was', mistakeType: 'agreement_quantity_as_plural' }, { text: 'be', mistakeType: 'agreement_quantity_as_plural' }], explanationRationale: 'Files is plural, so the fractional subject takes are.' }),

  entry({ ...common, id: 'intervening-list-easy', skill: 'intervening', sentenceTemplate: 'The list of requirements ____ complete.', grammaticalSubject: 'The list', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'intervening', ruleDetail: 'The of phrase does not change the singular subject list.', controllingNoun: 'list', completedSentence: 'The list of requirements is complete.', difficulty: 'easy', distractors: [{ text: 'are', mistakeType: 'agreement_nearest_noun' }, { text: 'were', mistakeType: 'agreement_nearest_noun' }, { text: 'be', mistakeType: 'agreement_nearest_noun' }], explanationRationale: 'List is the true subject; requirements belongs to an intervening phrase.' }),
  entry({ ...common, id: 'intervening-reports-medium', skill: 'intervening', sentenceTemplate: 'The reports in the cabinet ____ organized.', grammaticalSubject: 'The reports', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'intervening', ruleDetail: 'The prepositional phrase does not change the plural subject reports.', controllingNoun: 'reports', completedSentence: 'The reports in the cabinet are organized.', difficulty: 'medium', distractors: [{ text: 'is', mistakeType: 'agreement_nearest_noun' }, { text: 'was', mistakeType: 'agreement_nearest_noun' }, { text: 'be', mistakeType: 'agreement_nearest_noun' }], explanationRationale: 'Reports is plural; cabinet is not the subject.' }),
  entry({ ...common, id: 'intervening-along-hard', skill: 'intervening', sentenceTemplate: 'The manager, along with the clerks, ____ attending.', grammaticalSubject: 'The manager', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'intervening', ruleDetail: 'Along with does not create a compound subject.', controllingNoun: 'manager', completedSentence: 'The manager, along with the clerks, is attending.', difficulty: 'hard', distractors: [{ text: 'are', mistakeType: 'agreement_along_with_as_and' }, { text: 'were', mistakeType: 'agreement_along_with_as_and' }, { text: 'be', mistakeType: 'agreement_along_with_as_and' }], explanationRationale: 'Manager remains the singular subject despite the along with phrase.' }),

  entry({ ...common, id: 'inverted-one-easy', skill: 'inverted', sentenceTemplate: 'There ____ one file on the desk.', grammaticalSubject: 'one file', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'inverted', ruleDetail: 'In a there construction, the verb agrees with the delayed subject.', invertedSubject: 'one file', completedSentence: 'There is one file on the desk.', difficulty: 'easy', distractors: [{ text: 'are', mistakeType: 'agreement_always_there_is' }, { text: 'were', mistakeType: 'agreement_always_there_is' }, { text: 'be', mistakeType: 'agreement_always_there_is' }], explanationRationale: 'One file is the delayed singular subject, so is is correct.' }),
  entry({ ...common, id: 'inverted-several-medium', skill: 'inverted', sentenceTemplate: 'There ____ several files on the desk.', grammaticalSubject: 'several files', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'inverted', ruleDetail: 'The verb agrees with the delayed plural subject several files.', invertedSubject: 'several files', completedSentence: 'There are several files on the desk.', difficulty: 'medium', distractors: [{ text: 'is', mistakeType: 'agreement_always_there_is' }, { text: 'was', mistakeType: 'agreement_always_there_is' }, { text: 'be', mistakeType: 'agreement_always_there_is' }], explanationRationale: 'Several files is plural, so there are is required.' }),
  entry({ ...common, id: 'inverted-lies-hard', skill: 'inverted', sentenceTemplate: 'On the table ____ the report.', grammaticalSubject: 'the report', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'lie', correctForm: 'lies', ruleFamily: 'inverted', ruleDetail: 'The delayed singular subject report takes lies.', invertedSubject: 'the report', completedSentence: 'On the table lies the report.', difficulty: 'hard', distractors: [{ text: 'lie', mistakeType: 'agreement_nearest_noun' }, { text: 'lying', mistakeType: 'agreement_nearest_noun' }, { text: 'lay', mistakeType: 'agreement_nearest_noun' }], explanationRationale: 'Report is the delayed subject, not table, and takes lies.' }),

  entry({ ...common, id: 'special-news-easy', skill: 'special', sentenceTemplate: 'The news ____ encouraging.', grammaticalSubject: 'The news', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'special', ruleDetail: 'News ends in s but is singular.', specialCase: 'news_singular', completedSentence: 'The news is encouraging.', difficulty: 'easy', distractors: [{ text: 'are', mistakeType: 'agreement_final_s' }, { text: 'were', mistakeType: 'agreement_final_s' }, { text: 'be', mistakeType: 'agreement_final_s' }], explanationRationale: 'News is a well-established singular noun despite its final s.' }),
  entry({ ...common, id: 'special-scissors-medium', skill: 'special', sentenceTemplate: 'The scissors ____ on the desk.', grammaticalSubject: 'The scissors', subjectNumber: 'plural', subjectPerson: 'third', verbLemma: 'be', correctForm: 'are', ruleFamily: 'special', ruleDetail: 'Scissors is a plural-only noun.', specialCase: 'plural_only', completedSentence: 'The scissors are on the desk.', difficulty: 'medium', distractors: [{ text: 'is', mistakeType: 'agreement_final_s' }, { text: 'was', mistakeType: 'agreement_final_s' }, { text: 'be', mistakeType: 'agreement_final_s' }], explanationRationale: 'Scissors is plural unless introduced by the singular phrase a pair of.' }),
  entry({ ...common, id: 'special-number-hard', skill: 'special', sentenceTemplate: 'The number of pending files ____ increasing.', grammaticalSubject: 'The number', subjectNumber: 'singular', subjectPerson: 'third', verbLemma: 'be', correctForm: 'is', ruleFamily: 'special', ruleDetail: 'The number of takes a singular verb.', specialCase: 'the_number_of', completedSentence: 'The number of pending files is increasing.', difficulty: 'hard', distractors: [{ text: 'are', mistakeType: 'agreement_nearest_noun' }, { text: 'were', mistakeType: 'agreement_nearest_noun' }, { text: 'be', mistakeType: 'agreement_nearest_noun' }], explanationRationale: 'The singular head number controls agreement, not the plural noun files.' }),
]

export function findSubjectVerbAgreementEntry(id: string): AgreementEntry | null { return subjectVerbAgreementBankV1.find((item) => item.id === id) ?? null }
