import { entriesForPeaceHumanRightsCategory,findPeaceHumanRightsEntry,peaceHumanRightsBankV1 } from '../../domain/peace-human-rights/peace-human-rights.bank'
import { peaceHumanRightsDistractor,selectPeaceHumanRightsDistractors } from '../../domain/peace-human-rights/peace-human-rights.distractors'
import { formatPeaceHumanRightsReference,peaceHumanRightsCategoryLabel,peaceHumanRightsStableNumber } from '../../domain/peace-human-rights/peace-human-rights.format'
import { institutionRoleValid,peaceHumanRightsSourceComplete,rejectsCurrentPersonContent,rejectsPartisanOrActiveDispute,rejectsUnsafeAdvice,rejectsUnsupportedTreatyClaim,scenarioIsSafe,uniquePeaceHumanRightsAnswer,uniqueVisibleChoices } from '../../domain/peace-human-rights/peace-human-rights.rules'
import type { PeaceHumanRightsCategory,PeaceHumanRightsSource } from '../../domain/peace-human-rights/peace-human-rights.types'
import { validatePeaceHumanRightsEntry } from '../../domain/peace-human-rights/peace-human-rights.validation'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion,GeneratorDifficulty,GeneratorSlug,GeneratorValidationResult,QuestionGenerator } from '../generator.types'
const categoryBySlug={'human-dignity-universality':'dignity_universality','civil-political-rights':'civil_political','economic-social-cultural-rights':'economic_social_cultural','equality-nondiscrimination':'equality_nondiscrimination','rights-duties-responsibilities':'rights_responsibilities','peace-conflict-nonviolence':'peace_conflict_nonviolence','conflict-prevention-resolution':'conflict_prevention_resolution','peacebuilding-concepts':'peacebuilding','human-rights-institutions':'institutions'} as const satisfies Partial<Record<GeneratorSlug,PeaceHumanRightsCategory>>
const slugs=[...Object.keys(categoryBySlug),'mixed-peace-human-rights'] as GeneratorSlug[]
const frames=[(concept:string,scenario:string)=>`Which source-verified statement accurately explains ${concept}? ${scenario}`,(concept:string,scenario:string)=>`${scenario} Which statement best applies the concept of ${concept}?`,(concept:string,scenario:string)=>`Select the accurate statement about ${concept} in this neutral scenario: ${scenario}`,(concept:string,scenario:string)=>`Which choice preserves the authoritative source and safety limits for ${concept}? ${scenario}`]
function pool(slug:GeneratorSlug,difficulty:GeneratorDifficulty){const category=slug==='mixed-peace-human-rights'?undefined:categoryBySlug[slug as keyof typeof categoryBySlug];const entries=(category===undefined?peaceHumanRightsBankV1:entriesForPeaceHumanRightsCategory(category)).filter((entry)=>entry.difficulty===difficulty);return entries.flatMap((entry)=>frames.map((frame,variant)=>({entry,variant,prompt:frame(entry.concept,entry.scenarioTemplates[0]??'A neutral public-service scenario is presented.')})))}
function build(slug:GeneratorSlug,input:{seed:string;difficulty:GeneratorDifficulty}):GeneratedQuestion{const random=createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`);const scenario=random.pick(pool(slug,input.difficulty));const entry=scenario.entry;const distractors=selectPeaceHumanRightsDistractors(entry.explanation,entry.distractors.map((item)=>peaceHumanRightsDistractor(item.text,item.mistakeType)));const choices=random.shuffle([{text:entry.explanation,isCorrect:true,distractorType:null,mistakeType:null,derivation:null,qualityScore:1,numericValue:peaceHumanRightsStableNumber(entry.explanation)},...distractors.map((item)=>({text:item.text,isCorrect:false,distractorType:item.mistakeType,mistakeType:item.mistakeType,derivation:{operation:item.mistakeType,inputs:[peaceHumanRightsStableNumber(item.text)]},qualityScore:item.qualityScore,numericValue:peaceHumanRightsStableNumber(item.text)}))]);return{generatorSlug:slug,generatorVersion:1,difficulty:input.difficulty,seed:input.seed,prompt:scenario.prompt,parameters:{entryId:entry.id,category:entry.category,conceptClass:entry.conceptClass,provisionId:entry.source.provisionId,institution:entry.source.institution,source:{...entry.source},scenarioTemplates:[...entry.scenarioTemplates],recomputedCorrect:entry.explanation,scenarioSignature:`${entry.id}|${scenario.variant}`},choices,explanation:{title:'Source-verified peace and human-rights review',steps:[`The tested area is ${peaceHumanRightsCategoryLabel(entry.category)}.`,entry.explanation,`Authoritative source: ${formatPeaceHumanRightsReference(entry.source)}.`,`Misconception rejected: ${entry.misconception}`,'This educational review is not legal advice or official CSC examination material. Official constitutional, treaty, and institutional materials control.'],finalAnswer:entry.explanation},metadata:{answerKind:'text',unit:null,canonicalSignature:`${slug}|${entry.id}|${scenario.variant}`}}}
function validate(question:GeneratedQuestion):GeneratorValidationResult{const id=question.parameters.entryId;const entry=typeof id==='string'?findPeaceHumanRightsEntry(id):null;const answer=question.parameters.recomputedCorrect;const source=question.parameters.source as PeaceHumanRightsSource|undefined;const serialized=`${question.prompt} ${question.choices.map((choice)=>choice.text).join(' ')}`;const choices=question.choices.map((choice)=>choice.text);const valid=entry!==null&&validatePeaceHumanRightsEntry(entry).length===0&&typeof answer==='string'&&source!==undefined&&peaceHumanRightsSourceComplete(source)&&JSON.stringify(source)===JSON.stringify(entry.source)&&question.parameters.provisionId===entry.source.provisionId&&question.parameters.institution===entry.source.institution&&institutionRoleValid(entry)&&rejectsCurrentPersonContent(serialized)&&rejectsPartisanOrActiveDispute(serialized)&&scenarioIsSafe(serialized)&&rejectsUnsafeAdvice(serialized)&&rejectsUnsupportedTreatyClaim(serialized)&&uniqueVisibleChoices(choices)&&uniquePeaceHumanRightsAnswer(choices,answer)&&question.choices.filter((choice)=>choice.isCorrect).length===1&&question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('phr_')===true&&choice.derivation!==null)&&question.explanation.steps.some((step)=>step.includes(entry.source.provisionId)&&step.includes(entry.source.institution));return{valid,reason:valid?null:'Peace and human-rights validation failed.'}}
const make=(slug:GeneratorSlug):QuestionGenerator=>({slug,version:1,title:slug.replaceAll('-',' '),supportedDifficulties:['easy','medium','hard'],generate:(input)=>build(slug,input),validate})
export const peaceHumanRightsGenerators=slugs.map(make)
