import type { QueueState } from './ordering-ranking.types'

function assertRank(rank: number, total: number): void { if (!Number.isInteger(rank) || !Number.isInteger(total) || total < 1 || rank < 1 || rank > total) throw new Error('Rank must be an integer within the total.') }
export function oppositeRank(total: number, rank: number): number { assertRank(rank, total); return total - rank + 1 }
export function totalFromTwoRanks(first: number, second: number): number { if (!Number.isInteger(first) || !Number.isInteger(second) || first < 1 || second < 1) throw new Error('Ranks must be positive integers.'); return first + second - 1 }
export function rankFromPeopleBefore(count: number): number { if (!Number.isInteger(count) || count < 0) throw new Error('Count must be nonnegative.'); return count + 1 }
export function rankFromPeopleAfter(total: number, count: number): number { if (!Number.isInteger(count) || count < 0 || count >= total) throw new Error('People after must fit the line.'); return total - count }
export function movePosition(rank: number, places: number, direction: 'left' | 'right', total: number): number { assertRank(rank, total); if (!Number.isInteger(places) || places < 0) throw new Error('Movement must be nonnegative.'); const next = rank + (direction === 'right' ? places : -places); assertRank(next, total); return next }
export function overtake(rank: number, people: number, total: number): number { return movePosition(rank, people, 'left', total) }
export function overtakenBy(rank: number, people: number, total: number): number { return movePosition(rank, people, 'right', total) }
export function swapPositions(first: number, second: number, total: number): readonly [number, number] { assertRank(first, total); assertRank(second, total); if (first === second) throw new Error('Swap positions must differ.'); return [second, first] }
export function middlePositions(total: number): readonly number[] { if (!Number.isInteger(total) || total < 1) throw new Error('Total must be positive.'); return total % 2 === 1 ? [(total + 1) / 2] : [total / 2, total / 2 + 1] }
export function peopleBetween(first: number, second: number): number { if (!Number.isInteger(first) || !Number.isInteger(second) || first < 1 || second < 1 || first === second) throw new Error('Positions must be distinct positive integers.'); return Math.abs(first - second) - 1 }
export function updateQueue(state: QueueState, change: { kind: 'leave-front' | 'join-ahead' | 'leave-behind' | 'join-back'; count: number }): QueueState { assertRank(state.rankFromFront, state.total); if (!Number.isInteger(change.count) || change.count < 0) throw new Error('Queue change must be nonnegative.'); if (change.kind === 'leave-front') { if (change.count >= state.rankFromFront) throw new Error('Named person would leave the queue.'); return { total: state.total - change.count, rankFromFront: state.rankFromFront - change.count } } if (change.kind === 'join-ahead') return { total: state.total + change.count, rankFromFront: state.rankFromFront + change.count }; if (change.kind === 'leave-behind') { if (change.count > state.total - state.rankFromFront) throw new Error('Too many people leave behind.'); return { total: state.total - change.count, rankFromFront: state.rankFromFront } }; return { total: state.total + change.count, rankFromFront: state.rankFromFront } }
