import type { OrderEdge } from './ordering-ranking.types'
import { normalizeRankingAnswer } from './ordering-ranking-format'

export function hasUniqueRankingChoices(choices: readonly string[]): boolean { return choices.length === 4 && new Set(choices.map(normalizeRankingAnswer)).size === 4 }
export function hasExactlyOneRankingAnswer(choices: readonly string[], correct: string): boolean { return choices.map(normalizeRankingAnswer).filter((choice) => choice === normalizeRankingAnswer(correct)).length === 1 }
export function orderClosure(nodes: readonly string[], edges: readonly OrderEdge[]): ReadonlyMap<string, ReadonlySet<string>> { const graph = new Map(nodes.map((node) => [node, new Set<string>()])); for (const edge of edges) { if (!graph.has(edge.higher) || !graph.has(edge.lower) || edge.higher === edge.lower) throw new Error('Invalid comparative edge.'); graph.get(edge.higher)?.add(edge.lower) } for (const via of nodes) for (const from of nodes) if (graph.get(from)?.has(via) === true) for (const to of graph.get(via) ?? []) graph.get(from)?.add(to); for (const node of nodes) if (graph.get(node)?.has(node) === true) throw new Error('Comparative clues contain a cycle.'); return graph }
export function hasComparisonCycle(nodes: readonly string[], edges: readonly OrderEdge[]): boolean { try { orderClosure(nodes, edges); return false } catch { return true } }
export function compareUniquely(nodes: readonly string[], edges: readonly OrderEdge[], first: string, second: string): 'higher' | 'lower' | null { const closure = orderClosure(nodes, edges); if (closure.get(first)?.has(second) === true) return 'higher'; if (closure.get(second)?.has(first) === true) return 'lower'; return null }
export function uniqueTotalOrder(nodes: readonly string[], edges: readonly OrderEdge[]): string[] | null { const closure = orderClosure(nodes, edges); const sorted = [...nodes].sort((a, b) => (closure.get(a)?.has(b) === true ? -1 : closure.get(b)?.has(a) === true ? 1 : 0)); return sorted.every((node, index) => sorted.slice(index + 1).every((lower) => closure.get(node)?.has(lower) === true)) ? sorted : null }
