import type { GeneratedMockExamQuestion, MockExamBlueprint } from '../domain/mock-exam-blueprint'

export interface MockExamRow { id:number; public_id:string; course_id:number; course_slug:string; title:string; slug:string; description:string; simulation_label:string; position:number; passing_score:number; question_count:number; timed_duration_minutes:number; maximum_attempts:number|null; show_explanations:0|1; current_blueprint_version:number; status:'draft'|'published'; source_url:string; created_at:string; updated_at:string }
export interface MockAttemptRow { id:number; public_id:string; mock_exam_id:number; blueprint_id:number; user_id:number; attempt_seed:string; attempt_number:number; mode:'timed'|'untimed'; status:'instructions'|'in_progress'|'submitted'|'expired'|'abandoned'; total_points:number; earned_points:number; score_percent:number|null; passed:0|1|null; created_at:string; started_at:string|null; deadline_at:string|null; submitted_at:string|null; duration_seconds:number|null; auto_submitted:0|1; title:string; slug:string; passing_score:number; timed_duration_minutes:number; show_explanations:0|1; blueprint_version:number; course_id:number; course_slug:string }
export interface MockQuestionRow { snapshot_id:number; snapshot_public_id:string; source_position:number; subject_slug:string; subject_title:string; subject_position:number; topic_slug:string; topic_title:string; topic_position:number; generator_slug:string; generator_version:number; difficulty:'easy'|'medium'|'hard'; prompt:string; explanation_json:string; parameters_json:string; metadata_json:string; marked_for_review:0|1; choice_id:number; choice_public_id:string; choice_text:string; is_correct:0|1; choice_position:number }
export interface MockAnswerRow { snapshot_id:number; selected_choice_id:number|null; selected_choice_text_snapshot:string|null; correct_choice_text_snapshot:string|null; is_correct:0|1|null; points_awarded:number; answered_at:string|null }

const mockSelect = `m.id,m.public_id,m.course_id,c.slug AS course_slug,m.title,m.slug,m.description,m.simulation_label,m.position,m.passing_score,m.question_count,m.timed_duration_minutes,m.maximum_attempts,m.show_explanations,m.current_blueprint_version,m.status,m.source_url,m.created_at,m.updated_at`
export async function findMockBySlug(db:D1Database,slug:string){ return db.prepare(`SELECT ${mockSelect} FROM mock_examinations m INNER JOIN courses c ON c.id=m.course_id WHERE m.slug=?1 LIMIT 1`).bind(slug).first<MockExamRow>() }
export async function findPublishedMockForCourse(db:D1Database,courseId:number){ return db.prepare(`SELECT ${mockSelect} FROM mock_examinations m INNER JOIN courses c ON c.id=m.course_id WHERE m.course_id=?1 AND m.status='published' AND c.status='published' LIMIT 1`).bind(courseId).first<MockExamRow>() }

export async function upsertMock(db:D1Database,input:{publicId:string;courseId:number;title:string;slug:string;description:string;simulationLabel:string;position:number;passingScore:number;questionCount:number;timedDurationMinutes:number;maximumAttempts:number|null;showExplanations:boolean;blueprintVersion:number;status:'draft'|'published';sourceUrl:string}){
  await db.prepare(`INSERT INTO mock_examinations(public_id,course_id,title,slug,description,simulation_label,position,passing_score,question_count,timed_duration_minutes,maximum_attempts,show_explanations,current_blueprint_version,status,source_url) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15) ON CONFLICT(slug) DO UPDATE SET course_id=excluded.course_id,title=excluded.title,description=excluded.description,simulation_label=excluded.simulation_label,position=excluded.position,passing_score=excluded.passing_score,question_count=excluded.question_count,timed_duration_minutes=excluded.timed_duration_minutes,maximum_attempts=excluded.maximum_attempts,show_explanations=excluded.show_explanations,current_blueprint_version=excluded.current_blueprint_version,status=excluded.status,source_url=excluded.source_url,updated_at=CURRENT_TIMESTAMP`).bind(input.publicId,input.courseId,input.title,input.slug,input.description,input.simulationLabel,input.position,input.passingScore,input.questionCount,input.timedDurationMinutes,input.maximumAttempts,input.showExplanations?1:0,input.blueprintVersion,input.status,input.sourceUrl).run()
  return findMockBySlug(db,input.slug)
}

export async function replaceMockBlueprint(db:D1Database,mockId:number,blueprint:MockExamBlueprint,refs:Map<string,{subjectId:number;assessmentId:number;topics:Map<string,number>}>){
  const statements:D1PreparedStatement[]=[db.prepare(`INSERT INTO mock_exam_blueprints(mock_exam_id,version,label,total_questions,passing_score_percent,timed_duration_minutes,easy_count,medium_count,hard_count) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9) ON CONFLICT(mock_exam_id,version) DO UPDATE SET label=excluded.label,total_questions=excluded.total_questions,passing_score_percent=excluded.passing_score_percent,timed_duration_minutes=excluded.timed_duration_minutes,easy_count=excluded.easy_count,medium_count=excluded.medium_count,hard_count=excluded.hard_count`).bind(mockId,blueprint.version,blueprint.label,blueprint.totalQuestions,blueprint.passingScorePercent,blueprint.timedDurationMinutes,blueprint.difficulty.easy,blueprint.difficulty.medium,blueprint.difficulty.hard),db.prepare(`DELETE FROM mock_exam_blueprint_subjects WHERE blueprint_id=(SELECT id FROM mock_exam_blueprints WHERE mock_exam_id=?1 AND version=?2)`).bind(mockId,blueprint.version)]
  for(const subject of blueprint.subjects){const ref=refs.get(subject.subjectSlug);if(ref===undefined)throw new Error(`Missing subject reference ${subject.subjectSlug}.`);statements.push(db.prepare(`INSERT INTO mock_exam_blueprint_subjects(blueprint_id,subject_id,subject_assessment_id,subject_slug,subject_title,position,question_count,easy_count,medium_count,hard_count) VALUES((SELECT id FROM mock_exam_blueprints WHERE mock_exam_id=?1 AND version=?2),?3,?4,?5,?6,?7,?8,?9,?10,?11)`).bind(mockId,blueprint.version,ref.subjectId,ref.assessmentId,subject.subjectSlug,subject.subjectTitle,subject.position,subject.count,subject.difficulty.easy,subject.difficulty.medium,subject.difficulty.hard));for(const topic of subject.topics){const topicId=ref.topics.get(topic.topicSlug);if(topicId===undefined)throw new Error(`Missing topic reference ${topic.topicSlug}.`);statements.push(db.prepare(`INSERT INTO mock_exam_blueprint_topics(blueprint_subject_id,topic_id,topic_slug,topic_title,position,question_count,easy_count,medium_count,hard_count) VALUES((SELECT s.id FROM mock_exam_blueprint_subjects s INNER JOIN mock_exam_blueprints b ON b.id=s.blueprint_id WHERE b.mock_exam_id=?1 AND b.version=?2 AND s.subject_slug=?3),?4,?5,?6,?7,?8,?9,?10,?11)`).bind(mockId,blueprint.version,subject.subjectSlug,topicId,topic.topicSlug,topic.topicTitle,topic.position,topic.count,topic.difficulty.easy,topic.difficulty.medium,topic.difficulty.hard));for(const generator of topic.generators) statements.push(db.prepare(`INSERT INTO mock_exam_blueprint_generators(blueprint_topic_id,generator_slug,generator_version,rotation_position,selection_weight) VALUES((SELECT t.id FROM mock_exam_blueprint_topics t INNER JOIN mock_exam_blueprint_subjects s ON s.id=t.blueprint_subject_id INNER JOIN mock_exam_blueprints b ON b.id=s.blueprint_id WHERE b.mock_exam_id=?1 AND b.version=?2 AND s.subject_slug=?3 AND t.topic_slug=?4),?5,?6,?7,?8)`).bind(mockId,blueprint.version,subject.subjectSlug,topic.topicSlug,generator.slug,generator.version,generator.rotationPosition,generator.selectionWeight))}}
  await db.batch(statements)
}

const attemptSelect=`a.id,a.public_id,a.mock_exam_id,a.blueprint_id,a.user_id,a.attempt_seed,a.attempt_number,a.mode,a.status,a.total_points,a.earned_points,a.score_percent,a.passed,a.created_at,a.started_at,a.deadline_at,a.submitted_at,a.duration_seconds,a.auto_submitted,m.title,m.slug,m.passing_score,m.timed_duration_minutes,m.show_explanations,b.version AS blueprint_version,m.course_id,c.slug AS course_slug`
export async function findMockAttempt(db:D1Database,publicId:string){return db.prepare(`SELECT ${attemptSelect} FROM mock_exam_attempts a INNER JOIN mock_examinations m ON m.id=a.mock_exam_id INNER JOIN mock_exam_blueprints b ON b.id=a.blueprint_id INNER JOIN courses c ON c.id=m.course_id WHERE a.public_id=?1 LIMIT 1`).bind(publicId).first<MockAttemptRow>()}
export async function findActiveMockAttempt(db:D1Database,mockId:number,userId:number){return db.prepare(`SELECT ${attemptSelect} FROM mock_exam_attempts a INNER JOIN mock_examinations m ON m.id=a.mock_exam_id INNER JOIN mock_exam_blueprints b ON b.id=a.blueprint_id INNER JOIN courses c ON c.id=m.course_id WHERE a.mock_exam_id=?1 AND a.user_id=?2 AND a.status IN('instructions','in_progress') LIMIT 1`).bind(mockId,userId).first<MockAttemptRow>()}
export async function nextMockAttemptNumber(db:D1Database,mockId:number,userId:number){const row=await db.prepare('SELECT COALESCE(MAX(attempt_number),0) AS n FROM mock_exam_attempts WHERE mock_exam_id=?1 AND user_id=?2').bind(mockId,userId).first<{n:number}>();return (row?.n??0)+1}
export async function blueprintId(db:D1Database,mockId:number,version:number){const row=await db.prepare('SELECT id FROM mock_exam_blueprints WHERE mock_exam_id=?1 AND version=?2').bind(mockId,version).first<{id:number}>();return row?.id??null}

export async function createMockAttemptWithSnapshots(db:D1Database,input:{publicId:string;mockId:number;blueprintId:number;userId:number;seed:string;attemptNumber:number;mode:'timed'|'untimed';questions:GeneratedMockExamQuestion[]}){
  const statements:D1PreparedStatement[]=[db.prepare(`INSERT INTO mock_exam_attempts(public_id,mock_exam_id,blueprint_id,user_id,attempt_seed,attempt_number,mode,total_points) VALUES(?1,?2,?3,?4,?5,?6,?7,?8)`).bind(input.publicId,input.mockId,input.blueprintId,input.userId,input.seed,input.attemptNumber,input.mode,input.questions.length)]
  for(const item of input.questions){const snapshotId=`mock-question-${crypto.randomUUID()}`;statements.push(db.prepare(`INSERT INTO mock_exam_question_snapshots(public_id,attempt_id,source_position,subject_slug,subject_title,subject_position,topic_slug,topic_title,topic_position,generator_slug,generator_version,seed,difficulty,prompt,explanation_json,parameters_json,metadata_json) VALUES(?1,(SELECT id FROM mock_exam_attempts WHERE public_id=?2),?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17)`).bind(snapshotId,input.publicId,item.position,item.subjectSlug,item.subjectTitle,item.subjectPosition,item.topicSlug,item.topicTitle,item.topicPosition,item.question.generatorSlug,item.question.generatorVersion,item.question.seed,item.question.difficulty,item.question.prompt,JSON.stringify(item.question.explanation),JSON.stringify(item.question.parameters),JSON.stringify(item.question.metadata)));item.question.choices.forEach((choice,index)=>statements.push(db.prepare(`INSERT INTO mock_exam_question_choices(public_id,snapshot_id,choice_text,is_correct,position,distractor_type) VALUES(?1,(SELECT id FROM mock_exam_question_snapshots WHERE public_id=?2),?3,?4,?5,?6)`).bind(`mock-choice-${crypto.randomUUID()}`,snapshotId,choice.text,choice.isCorrect?1:0,index+1,choice.distractorType)))}
  await db.batch(statements);return findMockAttempt(db,input.publicId)
}

export async function getMockQuestions(db:D1Database,attemptId:number){const rows=await db.prepare(`SELECT s.id AS snapshot_id,s.public_id AS snapshot_public_id,s.source_position,s.subject_slug,s.subject_title,s.subject_position,s.topic_slug,s.topic_title,s.topic_position,s.generator_slug,s.generator_version,s.difficulty,s.prompt,s.explanation_json,s.parameters_json,s.metadata_json,s.marked_for_review,c.id AS choice_id,c.public_id AS choice_public_id,c.choice_text,c.is_correct,c.position AS choice_position FROM mock_exam_question_snapshots s INNER JOIN mock_exam_question_choices c ON c.snapshot_id=s.id WHERE s.attempt_id=?1 ORDER BY s.source_position,c.position`).bind(attemptId).all<MockQuestionRow>();return rows.results}
export async function getMockAnswers(db:D1Database,attemptId:number){const rows=await db.prepare(`SELECT snapshot_id,selected_choice_id,selected_choice_text_snapshot,correct_choice_text_snapshot,is_correct,points_awarded,answered_at FROM mock_exam_answers WHERE attempt_id=?1`).bind(attemptId).all<MockAnswerRow>();return rows.results}
export async function findMockSnapshot(db:D1Database,attemptId:number,publicId:string){return db.prepare('SELECT id FROM mock_exam_question_snapshots WHERE attempt_id=?1 AND public_id=?2').bind(attemptId,publicId).first<{id:number}>()}
export async function findMockChoice(db:D1Database,snapshotId:number,publicId:string){return db.prepare('SELECT id FROM mock_exam_question_choices WHERE snapshot_id=?1 AND public_id=?2').bind(snapshotId,publicId).first<{id:number}>()}
export async function saveMockAnswerRow(db:D1Database,attemptId:number,snapshotId:number,choiceId:number){await db.prepare(`INSERT INTO mock_exam_answers(attempt_id,snapshot_id,selected_choice_id,selected_choice_text_snapshot,answered_at) VALUES(?1,?2,?3,(SELECT choice_text FROM mock_exam_question_choices WHERE id=?3),CURRENT_TIMESTAMP) ON CONFLICT(attempt_id,snapshot_id) DO UPDATE SET selected_choice_id=excluded.selected_choice_id,selected_choice_text_snapshot=excluded.selected_choice_text_snapshot,correct_choice_text_snapshot=NULL,is_correct=NULL,points_awarded=0,answered_at=CURRENT_TIMESTAMP`).bind(attemptId,snapshotId,choiceId).run()}
export async function markMockSnapshot(db:D1Database,attemptId:number,snapshotId:number,marked:boolean){await db.prepare('UPDATE mock_exam_question_snapshots SET marked_for_review=?3 WHERE attempt_id=?1 AND id=?2').bind(attemptId,snapshotId,marked?1:0).run()}
export async function startMockRows(db:D1Database,attemptId:number,mode:'timed'|'untimed',minutes:number,now:Date){const started=now.toISOString();const deadline=mode==='timed'?new Date(now.getTime()+minutes*60_000).toISOString():null;await db.prepare(`UPDATE mock_exam_attempts SET status='in_progress',started_at=?2,deadline_at=?3 WHERE id=?1 AND status='instructions'`).bind(attemptId,started,deadline).run();return {startedAt:started,deadlineAt:deadline}}

export async function submitMockRows(db:D1Database,input:{attempt:MockAttemptRow;earned:number;percentage:number;passed:boolean;auto:boolean;expired:boolean;scores:Array<{snapshotId:number;choiceId:number|null;correct:boolean}>;subjectResults:Array<{slug:string;title:string;position:number;total:number;correct:number;incorrect:number;unanswered:number;percentage:number;status:string}>;topicResults:Array<{slug:string;title:string;position:number;total:number;correct:number;incorrect:number;unanswered:number;percentage:number;status:string;subjectSlug:string}>;now:Date}){
 const statements:D1PreparedStatement[]=[];for(const score of input.scores)statements.push(db.prepare(`INSERT INTO mock_exam_answers(attempt_id,snapshot_id,selected_choice_id,selected_choice_text_snapshot,correct_choice_text_snapshot,is_correct,points_awarded,answered_at) VALUES(?1,?2,?3,(SELECT choice_text FROM mock_exam_question_choices WHERE id=?3),(SELECT choice_text FROM mock_exam_question_choices WHERE snapshot_id=?2 AND is_correct=1 LIMIT 1),?4,?5,CURRENT_TIMESTAMP) ON CONFLICT(attempt_id,snapshot_id) DO UPDATE SET correct_choice_text_snapshot=excluded.correct_choice_text_snapshot,is_correct=excluded.is_correct,points_awarded=excluded.points_awarded`).bind(input.attempt.id,score.snapshotId,score.choiceId,score.correct?1:0,score.correct?1:0));for(const item of input.subjectResults)statements.push(db.prepare(`INSERT OR REPLACE INTO mock_exam_subject_results(attempt_id,subject_slug,subject_title,position,total_count,correct_count,incorrect_count,unanswered_count,percentage,status) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)`).bind(input.attempt.id,item.slug,item.title,item.position,item.total,item.correct,item.incorrect,item.unanswered,item.percentage,item.status));for(const item of input.topicResults)statements.push(db.prepare(`INSERT OR REPLACE INTO mock_exam_topic_results(attempt_id,subject_slug,topic_slug,topic_title,position,total_count,correct_count,incorrect_count,unanswered_count,percentage,status) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)`).bind(input.attempt.id,item.subjectSlug,item.slug,item.title,item.position,item.total,item.correct,item.incorrect,item.unanswered,item.percentage,item.status));const submitted=input.now.toISOString();const duration=input.attempt.started_at===null?0:Math.max(0,Math.floor((input.now.getTime()-Date.parse(input.attempt.started_at))/1000));statements.push(db.prepare(`UPDATE mock_exam_attempts SET status=?2,earned_points=?3,score_percent=?4,passed=?5,submitted_at=COALESCE(submitted_at,?6),duration_seconds=?7,auto_submitted=?8 WHERE id=?1 AND status='in_progress'`).bind(input.attempt.id,input.expired?'expired':'submitted',input.earned,input.percentage,input.passed?1:0,submitted,duration,input.auto?1:0));await db.batch(statements)
}
