import type { SynonymAntonymEntry } from './synonyms-antonyms.types'

type Input = Omit<SynonymAntonymEntry, 'normalized' | 'difficulty' | 'usageNote'> & { difficulty?: SynonymAntonymEntry['difficulty']; usageNote?: string }
const entry = (input: Input): SynonymAntonymEntry => ({ ...input, normalized: input.word.trim().toLowerCase(), difficulty: input.difficulty ?? 'easy', usageNote: input.usageNote ?? 'Use this relation only for the stated common sense.' })
const neutral = 'neutral' as const

export const synonymsAntonymsBankV1 = [
  entry({ word: 'assist', meaning: 'give help', senseId: 'help-v', partOfSpeech: 'verb', synonyms: ['help'], antonyms: ['hinder'], intensity: 2, connotation: neutral, formality: 'formal', example: 'Staff will assist visitors at the counter.' }),
  entry({ word: 'help', meaning: 'give assistance', senseId: 'help-v', partOfSpeech: 'verb', synonyms: ['assist'], antonyms: ['hinder'], intensity: 2, connotation: 'positive', formality: 'neutral', example: 'Please help the visitor complete the form.' }),
  entry({ word: 'begin', meaning: 'start an action', senseId: 'start-v', partOfSpeech: 'verb', synonyms: ['start', 'commence'], antonyms: ['end'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The meeting will begin at nine.' }),
  entry({ word: 'start', meaning: 'begin an action', senseId: 'start-v', partOfSpeech: 'verb', synonyms: ['begin'], antonyms: ['end'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The program will start after registration.' }),
  entry({ word: 'commence', meaning: 'begin formally', senseId: 'start-v', partOfSpeech: 'verb', synonyms: ['begin'], antonyms: ['terminate'], intensity: 2, connotation: neutral, formality: 'formal', example: 'The examination will commence at eight.' }),
  entry({ word: 'rapid', meaning: 'moving or happening quickly', senseId: 'fast-adj', partOfSpeech: 'adjective', synonyms: ['fast'], antonyms: ['slow'], intensity: 3, connotation: neutral, formality: 'formal', example: 'The office reported rapid improvement.' }),
  entry({ word: 'fast', meaning: 'moving quickly', senseId: 'fast-adj', partOfSpeech: 'adjective', synonyms: ['rapid'], antonyms: ['slow'], intensity: 3, connotation: neutral, formality: 'neutral', example: 'The team made fast progress.' }),
  entry({ word: 'permit', meaning: 'allow an action', senseId: 'allow-v', partOfSpeech: 'verb', synonyms: ['allow'], antonyms: ['prohibit'], intensity: 2, connotation: neutral, formality: 'formal', example: 'The rules permit one valid identification card.' }),
  entry({ word: 'allow', meaning: 'give permission', senseId: 'allow-v', partOfSpeech: 'verb', synonyms: ['permit'], antonyms: ['prohibit'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The office will allow online submission.' }),
  entry({ word: 'purchase', meaning: 'buy something', senseId: 'buy-v', partOfSpeech: 'verb', synonyms: ['buy'], antonyms: ['sell'], intensity: 2, connotation: neutral, formality: 'formal', example: 'The unit will purchase new folders.' }),
  entry({ word: 'buy', meaning: 'obtain by paying', senseId: 'buy-v', partOfSpeech: 'verb', synonyms: ['purchase'], antonyms: ['sell'], intensity: 2, connotation: neutral, formality: 'informal', example: 'We need to buy paper today.' }),
  entry({ word: 'reply', meaning: 'give an answer', senseId: 'respond-v', partOfSpeech: 'verb', synonyms: ['respond'], antonyms: ['ignore'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'Please reply before Friday.' }),
  entry({ word: 'respond', meaning: 'give an answer', senseId: 'respond-v', partOfSpeech: 'verb', synonyms: ['reply'], antonyms: ['ignore'], intensity: 2, connotation: neutral, formality: 'formal', example: 'The agency will respond in writing.' }),
  entry({ word: 'accurate', meaning: 'correct in detail', senseId: 'correct-adj', partOfSpeech: 'adjective', synonyms: ['correct'], antonyms: ['incorrect'], intensity: 2, connotation: 'positive', formality: 'neutral', example: 'Submit an accurate inventory count.' }),
  entry({ word: 'correct', meaning: 'free from error', senseId: 'correct-adj', partOfSpeech: 'adjective', synonyms: ['accurate'], antonyms: ['incorrect'], intensity: 2, connotation: 'positive', formality: 'neutral', example: 'Write the correct reference number.' }),
  entry({ word: 'scarce', meaning: 'available in too small an amount', senseId: 'amount-adj', partOfSpeech: 'adjective', synonyms: ['limited'], antonyms: ['abundant'], intensity: 3, connotation: 'negative', formality: 'neutral', example: 'Office space became scarce.' }),
  entry({ word: 'abundant', meaning: 'available in a large amount', senseId: 'amount-adj', partOfSpeech: 'adjective', synonyms: ['plentiful'], antonyms: ['scarce'], intensity: 3, connotation: 'positive', formality: 'formal', example: 'The school has abundant learning materials.' }),
  entry({ word: 'expand', meaning: 'become larger', senseId: 'size-v', partOfSpeech: 'verb', synonyms: ['enlarge'], antonyms: ['contract'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The office will expand its service area.' }),
  entry({ word: 'contract', meaning: 'become smaller', senseId: 'size-v', partOfSpeech: 'verb', synonyms: ['shrink'], antonyms: ['expand'], intensity: 2, connotation: neutral, formality: 'formal', example: 'The material may contract in cold weather.' }),
  entry({ word: 'temporary', meaning: 'lasting for a limited time', senseId: 'duration-adj', partOfSpeech: 'adjective', synonyms: ['short-term'], antonyms: ['permanent'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The office uses a temporary entrance.' }),
  entry({ word: 'permanent', meaning: 'intended to last', senseId: 'duration-adj', partOfSpeech: 'adjective', synonyms: ['lasting'], antonyms: ['temporary'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The archive needs a permanent location.' }),
  entry({ word: 'brief', meaning: 'short in duration or length', senseId: 'length-adj', partOfSpeech: 'adjective', synonyms: ['concise'], antonyms: ['lengthy'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The supervisor issued a brief instruction.' }),
  entry({ word: 'concise', meaning: 'short and clear', senseId: 'length-adj', partOfSpeech: 'adjective', synonyms: ['brief'], antonyms: ['wordy'], intensity: 2, connotation: 'positive', formality: 'formal', example: 'The report was concise and clear.' }),
  entry({ word: 'clear', meaning: 'easy to understand', senseId: 'clarity-adj', partOfSpeech: 'adjective', synonyms: ['plain'], antonyms: ['confusing'], intensity: 2, connotation: 'positive', formality: 'neutral', example: 'The instructions were clear.' }),
  entry({ word: 'stable', meaning: 'not changing unexpectedly', senseId: 'change-adj', partOfSpeech: 'adjective', synonyms: ['steady'], antonyms: ['unstable'], intensity: 2, connotation: 'positive', formality: 'neutral', example: 'Attendance remained stable this month.' }),
  entry({ word: 'warm', meaning: 'moderately hot', senseId: 'heat-adj', partOfSpeech: 'adjective', synonyms: ['mildly hot'], antonyms: ['cool'], intensity: 2, connotation: neutral, formality: 'neutral', example: 'The room became warm after noon.' }),
  entry({ word: 'hot', meaning: 'having high heat', senseId: 'heat-adj', partOfSpeech: 'adjective', synonyms: ['very warm'], antonyms: ['cold'], intensity: 4, connotation: neutral, formality: 'neutral', example: 'The equipment felt hot after use.' }),
  entry({ word: 'furious', meaning: 'extremely angry', senseId: 'anger-adj', partOfSpeech: 'adjective', synonyms: ['enraged'], antonyms: ['calm'], intensity: 5, connotation: 'negative', formality: 'neutral', example: 'The customer was furious about the repeated error.' }),
  entry({ word: 'angry', meaning: 'feeling displeasure', senseId: 'anger-adj', partOfSpeech: 'adjective', synonyms: ['upset'], antonyms: ['calm'], intensity: 3, connotation: 'negative', formality: 'neutral', example: 'The caller sounded angry about the delay.' }),
  entry({ word: 'confident', meaning: 'sure of one’s ability', senseId: 'self-view-adj', partOfSpeech: 'adjective', synonyms: ['self-assured'], antonyms: ['uncertain'], intensity: 3, connotation: 'positive', formality: 'neutral', example: 'The prepared speaker sounded confident.' }),
  entry({ word: 'arrogant', meaning: 'showing excessive self-importance', senseId: 'self-view-adj', partOfSpeech: 'adjective', synonyms: ['conceited'], antonyms: ['humble'], intensity: 4, connotation: 'negative', formality: 'neutral', example: 'The arrogant reply dismissed every suggestion.' }),
  entry({ word: 'economical', meaning: 'using resources carefully', senseId: 'cost-adj', partOfSpeech: 'adjective', synonyms: ['efficient'], antonyms: ['wasteful'], intensity: 2, connotation: 'positive', formality: 'neutral', example: 'Double-sided printing is economical.' }),
  entry({ word: 'cheap', meaning: 'low in price or quality', senseId: 'cost-adj', partOfSpeech: 'adjective', synonyms: ['inexpensive'], antonyms: ['costly'], intensity: 2, connotation: 'negative', formality: 'neutral', example: 'The cheap folder tore quickly.' }),
  entry({ word: 'inquire', meaning: 'ask for information', senseId: 'ask-v', partOfSpeech: 'verb', synonyms: ['ask'], antonyms: ['answer'], intensity: 2, connotation: neutral, formality: 'formal', example: 'Applicants may inquire at the help desk.' }),
  entry({ word: 'ask', meaning: 'request information', senseId: 'ask-v', partOfSpeech: 'verb', synonyms: ['inquire'], antonyms: ['answer'], intensity: 2, connotation: neutral, formality: 'informal', example: 'You can ask the clerk for help.' }),
  entry({ word: 'terminate', meaning: 'bring to an end', senseId: 'end-v', partOfSpeech: 'verb', synonyms: ['end'], antonyms: ['commence'], intensity: 3, connotation: neutral, formality: 'formal', example: 'The notice may terminate the temporary arrangement.' }),
  entry({ word: 'end', meaning: 'bring to a close', senseId: 'end-v', partOfSpeech: 'verb', synonyms: ['terminate'], antonyms: ['begin'], intensity: 2, connotation: neutral, formality: 'informal', example: 'The meeting will end at noon.' }),
] as const satisfies readonly SynonymAntonymEntry[]

export function findSynonymAntonymEntry(word: string): SynonymAntonymEntry | null { const normalized = word.trim().toLowerCase(); return synonymsAntonymsBankV1.find((item) => item.normalized === normalized) ?? null }
