import { entriesForCategory, findConstitutionEntry, philippineConstitutionBankV1 } from '../../domain/philippine-constitution/philippine-constitution-bank'
import { constitutionDistractor, selectConstitutionDistractors } from '../../domain/philippine-constitution/philippine-constitution-distractors'
import { constitutionCategoryLabel, constitutionNumericValue, formatConstitutionReference } from '../../domain/philippine-constitution/philippine-constitution-format'
import { institutionRoleMatches, rejectsCurrentPoliticalContent, sourceMetadataComplete, uniqueAnswer, uniqueVisibleChoices } from '../../domain/philippine-constitution/philippine-constitution-rules'
import { validateConstitutionEntry } from '../../domain/philippine-constitution/philippine-constitution-validation'
import type { ConstitutionCategory } from '../../domain/philippine-constitution/philippine-constitution.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const categoryBySlug = { 'constitution-structure-principles':'structure_principles', 'bill-of-rights':'bill_of_rights', 'citizenship-suffrage':'citizenship_suffrage', 'legislative-department':'legislative', 'executive-department':'executive', 'judicial-department':'judicial', 'constitutional-commissions':'constitutional_commissions', 'public-officer-accountability':'accountability', 'local-government-economy-amendments':'local_economy_amendments' } as const satisfies Partial<Record<GeneratorSlug,ConstitutionCategory>>
const slugs = [...Object.keys(categoryBySlug), 'mixed-philippine-constitution'] as GeneratorSlug[]
const frames = [(concept:string)=>`Which statement correctly describes ${concept} under the 1987 Philippine Constitution?`,(concept:string)=>`Which statement is consistent with the constitutional rule on ${concept}?`,(concept:string)=>`Select the accurate basic constitutional statement about ${concept}.`,(concept:string)=>`Which choice preserves the constitutional distinction concerning ${concept}?`]
function pool(slug:GeneratorSlug,difficulty:GeneratorDifficulty){const category=slug==='mixed-philippine-constitution'?undefined:categoryBySlug[slug as keyof typeof categoryBySlug];const entries=(category===undefined?philippineConstitutionBankV1:entriesForCategory(category)).filter((entry)=>entry.difficulty===difficulty);return entries.flatMap((entry)=>frames.map((frame,variant)=>({entry,variant,prompt:frame(entry.concept)})))}
function build(slug:GeneratorSlug,input:{seed:string;difficulty:GeneratorDifficulty}):GeneratedQuestion{const random=createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`);const scenario=random.pick(pool(slug,input.difficulty));const entry=scenario.entry;const distractors=selectConstitutionDistractors(entry.paraphrase,entry.distractors.map((item)=>constitutionDistractor(item.text,item.mistakeType)));const choices=random.shuffle([{text:entry.paraphrase,isCorrect:true,distractorType:null,mistakeType:null,derivation:null,qualityScore:1,numericValue:constitutionNumericValue(entry.paraphrase)},...distractors.map((item)=>({text:item.text,isCorrect:false,distractorType:item.mistakeType,mistakeType:item.mistakeType,derivation:{operation:item.mistakeType,inputs:[constitutionNumericValue(item.text)]},qualityScore:item.qualityScore,numericValue:constitutionNumericValue(item.text)}))]);return{generatorSlug:slug,generatorVersion:1,difficulty:input.difficulty,seed:input.seed,prompt:scenario.prompt,parameters:{entryId:entry.id,category:entry.category,article:entry.article,section:entry.section,source:{...entry.source},exactTerms:[...entry.exactTerms],recomputedCorrect:entry.paraphrase,scenarioSignature:`${entry.id}|${scenario.variant}`},choices,explanation:{title:'Philippine Constitution solution',steps:[`The tested area is ${constitutionCategoryLabel(entry.category)}.`,entry.paraphrase,`Authoritative source: ${formatConstitutionReference(entry.source)}.`,`Common misconception: ${entry.misconception}`,'This educational review is not legal advice or official CSC examination material.'],finalAnswer:entry.paraphrase},metadata:{answerKind:'text',unit:null,canonicalSignature:`${slug}|${entry.id}|${scenario.variant}`}}}
function validate(question:GeneratedQuestion):GeneratorValidationResult{const id=question.parameters.entryId;const entry=typeof id==='string'?findConstitutionEntry(id):null;const answer=question.parameters.recomputedCorrect;const choices=question.choices.map((choice)=>choice.text);const valid=entry!==null&&validateConstitutionEntry(entry).length===0&&typeof answer==='string'&&institutionRoleMatches(entry,answer)&&sourceMetadataComplete(entry.source)&&question.parameters.article===entry.article&&question.parameters.section===entry.section&&JSON.stringify(question.parameters.source)===JSON.stringify(entry.source)&&rejectsCurrentPoliticalContent(`${question.prompt} ${choices.join(' ')}`)&&uniqueVisibleChoices(choices)&&uniqueAnswer(choices,answer)&&question.choices.filter((choice)=>choice.isCorrect).length===1&&question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('constitution_')===true&&choice.derivation!==null)&&question.explanation.steps.some((step)=>step.includes(entry.article)&&step.includes(entry.section));return{valid,reason:valid?null:'Philippine Constitution validation failed.'}}
const make=(slug:GeneratorSlug):QuestionGenerator=>({slug,version:1,title:slug.replaceAll('-',' '),supportedDifficulties:['easy','medium','hard'],generate:(input)=>build(slug,input),validate})
export const philippineConstitutionGenerators=slugs.map(make)