import type { PronounCase, PronounModifierEntry, PronounNumber, PronounPerson } from './pronouns-modifiers.types'

const possessiveForms = new Set(['my', 'mine', 'your', 'yours', 'his', 'her', 'hers', 'its', 'our', 'ours', 'their', 'theirs'])
const reflexiveForms = new Set(['myself', 'yourself', 'himself', 'herself', 'itself', 'ourselves', 'yourselves', 'themselves'])
export function normalizePronounModifierText(value: string): string { return value.trim().toLowerCase().replaceAll(/\s+/gu, ' ') }
export function reconstructPronounModifierSentence(entry: PronounModifierEntry, choice: string): string { return entry.sentenceTemplate.replace('____', choice) }
export function antecedentRepresented(entry: PronounModifierEntry): boolean { return ['reference_agreement', 'case', 'possessive_reflexive', 'relative'].includes(entry.skill) ? entry.antecedent !== null && entry.antecedentKind !== 'not_applicable' : true }
export function pronounNumberMatches(entry: PronounModifierEntry, number: PronounNumber): boolean { return entry.antecedentNumber === number }
export function pronounPersonMatches(entry: PronounModifierEntry, person: PronounPerson): boolean { return entry.antecedentPerson === person }
export function pronounCaseMatches(entry: PronounModifierEntry, pronounCase: PronounCase): boolean { return entry.pronounCase === pronounCase }
export function possessiveFormValid(entry: PronounModifierEntry): boolean { return entry.pronounType !== 'possessive' || possessiveForms.has(normalizePronounModifierText(entry.correctChoice)) }
export function reflexiveAntecedentValid(entry: PronounModifierEntry): boolean { return entry.pronounType !== 'reflexive' || entry.antecedent !== null && reflexiveForms.has(normalizePronounModifierText(entry.correctChoice)) }
export function relativePronounValid(entry: PronounModifierEntry): boolean { if (entry.skill !== 'relative') return true; const choice = normalizePronounModifierText(entry.correctChoice); if (entry.relativeRole === 'possessive') return choice === 'whose'; if (entry.antecedentKind === 'person' && entry.relativeRole === 'subject') return choice === 'who'; if (entry.antecedentKind === 'person' && entry.relativeRole === 'object') return choice === 'whom'; if (entry.antecedentKind === 'thing' && entry.nonrestrictive === true) return choice === 'which'; return entry.antecedentKind === 'thing' && ['that', 'which'].includes(choice) }
export function adjectiveAdverbValid(entry: PronounModifierEntry): boolean { return entry.skill !== 'adjective_adverb' || entry.modifiedTarget !== null && ['adjective', 'adverb'].includes(entry.modifierType) }
export function modifierTargetValid(entry: PronounModifierEntry): boolean { return ['adjective_adverb', 'comparative', 'misplaced', 'dangling'].includes(entry.skill) ? entry.modifiedTarget !== null && entry.modifierPlacement === 'clear' : true }
export function comparativeFormValid(entry: PronounModifierEntry): boolean { if (entry.skill !== 'comparative') return true; const choice = normalizePronounModifierText(entry.correctChoice); return entry.modifierType === 'comparative' && !/more \w+(?:er)\b|most \w+(?:est)\b/iu.test(choice) }
export function misplacedModifierDetected(entry: PronounModifierEntry): boolean { return entry.skill !== 'misplaced' || entry.modifierType === 'misplaced' && entry.modifierPlacement === 'clear' && entry.modifiedTarget !== null }
export function danglingModifierResolved(entry: PronounModifierEntry): boolean { return entry.skill !== 'dangling' || entry.modifierType === 'dangling' && entry.impliedActor !== null && entry.mainClauseSubject !== null && normalizePronounModifierText(entry.impliedActor) === normalizePronounModifierText(entry.mainClauseSubject) }
export function sentenceRevisionValid(entry: PronounModifierEntry): boolean { const sentence = reconstructPronounModifierSentence(entry, entry.correctChoice); return sentence === entry.completedSentence && sentence.length >= 24 && /[.!?]$/u.test(sentence) && !sentence.includes('____') }
export function pronounModifierAnswerMatches(entry: PronounModifierEntry, choice: string): boolean { return normalizePronounModifierText(choice) === normalizePronounModifierText(entry.correctChoice) && reconstructPronounModifierSentence(entry, choice) === entry.completedSentence }
