import type { PronounModifierEntry } from './pronouns-modifiers.types'

const make = (value: PronounModifierEntry): PronounModifierEntry => value
const none = { antecedent: null, antecedentNumber: 'not_applicable', antecedentPerson: 'not_applicable', antecedentKind: 'not_applicable', pronounType: 'not_applicable', pronounCase: 'not_applicable', modifierType: 'not_applicable', modifiedTarget: null, modifierPlacement: 'not_applicable', relativeRole: 'not_applicable', nonrestrictive: null, impliedActor: null, mainClauseSubject: null } as const

export const pronounsModifiersBankV1: readonly PronounModifierEntry[] = [
  make({ ...none, id: 'reference-employees-easy', skill: 'reference_agreement', sentenceTemplate: 'The employees submitted ____ forms.', antecedent: 'employees', antecedentNumber: 'plural', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'possessive', pronounCase: 'possessive', correctChoice: 'their', ruleFamily: 'reference_agreement', ruleDetail: 'A plural third-person antecedent takes their.', completedSentence: 'The employees submitted their forms.', difficulty: 'easy', distractors: [{ text: 'his', mistakeType: 'pronoun_number_mismatch' }, { text: 'our', mistakeType: 'pronoun_person_shift' }, { text: 'theirs', mistakeType: 'pronoun_case_error' }], explanationRationale: 'Employees is plural and third person, so their clearly agrees.' }),
  make({ ...none, id: 'reference-clerks-medium', skill: 'reference_agreement', sentenceTemplate: 'The clerks completed ____ assigned tasks.', antecedent: 'clerks', antecedentNumber: 'plural', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'possessive', pronounCase: 'possessive', correctChoice: 'their', ruleFamily: 'reference_agreement', ruleDetail: 'The plural antecedent clerks requires their.', completedSentence: 'The clerks completed their assigned tasks.', difficulty: 'medium', distractors: [{ text: 'his', mistakeType: 'pronoun_number_mismatch' }, { text: 'your', mistakeType: 'pronoun_person_shift' }, { text: 'them', mistakeType: 'pronoun_case_error' }], explanationRationale: 'Their matches the plural third-person antecedent clerks.' }),
  make({ ...none, id: 'reference-clear-hard', skill: 'reference_agreement', sentenceTemplate: 'Choose the clearest revision: ____', antecedent: 'Rosa', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'personal', pronounCase: 'subject', correctChoice: 'When Rosa spoke to Ana, Rosa clarified the schedule.', ruleFamily: 'reference_agreement', ruleDetail: 'Repeat the intended noun when she could refer to two people.', completedSentence: 'Choose the clearest revision: When Rosa spoke to Ana, Rosa clarified the schedule.', difficulty: 'hard', distractors: [{ text: 'When Rosa spoke to Ana, she clarified the schedule.', mistakeType: 'pronoun_ambiguous_reference' }, { text: 'When she spoke to Ana, she clarified the schedule.', mistakeType: 'pronoun_ambiguous_reference' }, { text: 'Rosa spoke to Ana because she clarified the schedule.', mistakeType: 'pronoun_ambiguous_reference' }], explanationRationale: 'Repeating Rosa removes the otherwise unclear reference of she.' }),

  make({ ...none, id: 'case-subject-easy', skill: 'case', sentenceTemplate: 'She and ____ attended the meeting.', antecedent: 'speaker', antecedentNumber: 'singular', antecedentPerson: 'first', antecedentKind: 'person', pronounType: 'personal', pronounCase: 'subject', correctChoice: 'I', ruleFamily: 'case', ruleDetail: 'A pronoun used as part of the subject takes subject case.', completedSentence: 'She and I attended the meeting.', difficulty: 'easy', distractors: [{ text: 'me', mistakeType: 'pronoun_case_error' }, { text: 'myself', mistakeType: 'pronoun_unnecessary_reflexive' }, { text: 'mine', mistakeType: 'pronoun_case_error' }], explanationRationale: 'I is a subject pronoun and shares the subject role with she.' }),
  make({ ...none, id: 'case-object-medium', skill: 'case', sentenceTemplate: 'The supervisor called him and ____.', antecedent: 'speaker', antecedentNumber: 'singular', antecedentPerson: 'first', antecedentKind: 'person', pronounType: 'personal', pronounCase: 'object', correctChoice: 'me', ruleFamily: 'case', ruleDetail: 'The object of called takes object case.', completedSentence: 'The supervisor called him and me.', difficulty: 'medium', distractors: [{ text: 'I', mistakeType: 'pronoun_case_error' }, { text: 'myself', mistakeType: 'pronoun_unnecessary_reflexive' }, { text: 'mine', mistakeType: 'pronoun_case_error' }], explanationRationale: 'Me is the object form required after called.' }),
  make({ ...none, id: 'case-whom-hard', skill: 'case', sentenceTemplate: '____ did the manager call?', antecedent: 'person called', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'relative', pronounCase: 'object', correctChoice: 'Whom', ruleFamily: 'case', ruleDetail: 'The person receives the action of call, so formal object case is whom.', completedSentence: 'Whom did the manager call?', difficulty: 'hard', distractors: [{ text: 'Who', mistakeType: 'pronoun_case_error' }, { text: 'Whose', mistakeType: 'pronoun_wrong_relative' }, { text: 'Which', mistakeType: 'pronoun_wrong_relative' }], explanationRationale: 'Whom functions as the object of call in this formal question.' }),

  make({ ...none, id: 'possessive-theirs-easy', skill: 'possessive_reflexive', sentenceTemplate: 'The folder beside the printer is ____.', antecedent: 'employees', antecedentNumber: 'plural', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'possessive', pronounCase: 'possessive', correctChoice: 'theirs', ruleFamily: 'possessive_reflexive', ruleDetail: 'A standalone possessive pronoun is theirs.', completedSentence: 'The folder beside the printer is theirs.', difficulty: 'easy', distractors: [{ text: 'their', mistakeType: 'pronoun_case_error' }, { text: "they're", mistakeType: 'pronoun_possessive_contraction' }, { text: 'them', mistakeType: 'pronoun_case_error' }], explanationRationale: 'Theirs stands alone after is and shows plural possession.' }),
  make({ ...none, id: 'possessive-its-medium', skill: 'possessive_reflexive', sentenceTemplate: 'The office changed ____ schedule.', antecedent: 'office', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'thing', pronounType: 'possessive', pronounCase: 'possessive', correctChoice: 'its', ruleFamily: 'possessive_reflexive', ruleDetail: 'Its is possessive; it’s means it is.', completedSentence: 'The office changed its schedule.', difficulty: 'medium', distractors: [{ text: "it's", mistakeType: 'pronoun_possessive_contraction' }, { text: 'it', mistakeType: 'pronoun_case_error' }, { text: 'itself', mistakeType: 'pronoun_unnecessary_reflexive' }], explanationRationale: 'Its is the possessive determiner modifying schedule.' }),
  make({ ...none, id: 'reflexive-herself-hard', skill: 'possessive_reflexive', sentenceTemplate: 'The manager ____ approved the request.', antecedent: 'manager', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'reflexive', pronounCase: 'reflexive', correctChoice: 'herself', ruleFamily: 'possessive_reflexive', ruleDetail: 'Herself may emphasize the matching singular subject manager.', completedSentence: 'The manager herself approved the request.', difficulty: 'hard', distractors: [{ text: 'her', mistakeType: 'pronoun_case_error' }, { text: 'hers', mistakeType: 'pronoun_case_error' }, { text: 'theirselves', mistakeType: 'pronoun_unnecessary_reflexive' }], explanationRationale: 'Herself is the standard emphatic reflexive matching manager.' }),

  make({ ...none, id: 'relative-who-easy', skill: 'relative', sentenceTemplate: 'The employee ____ prepared the report is absent.', antecedent: 'employee', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'relative', pronounCase: 'subject', relativeRole: 'subject', nonrestrictive: false, correctChoice: 'who', ruleFamily: 'relative', ruleDetail: 'Who introduces a clause and serves as its subject for a person.', completedSentence: 'The employee who prepared the report is absent.', difficulty: 'easy', distractors: [{ text: 'whom', mistakeType: 'pronoun_wrong_relative' }, { text: 'which', mistakeType: 'pronoun_wrong_relative' }, { text: "who's", mistakeType: 'pronoun_wrong_relative' }], explanationRationale: 'Who refers to employee and performs prepared.' }),
  make({ ...none, id: 'relative-whom-medium', skill: 'relative', sentenceTemplate: 'The person ____ the manager called arrived.', antecedent: 'person', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'relative', pronounCase: 'object', relativeRole: 'object', nonrestrictive: false, correctChoice: 'whom', ruleFamily: 'relative', ruleDetail: 'Whom is the object of called in formal usage.', completedSentence: 'The person whom the manager called arrived.', difficulty: 'medium', distractors: [{ text: 'who', mistakeType: 'pronoun_wrong_relative' }, { text: 'which', mistakeType: 'pronoun_wrong_relative' }, { text: 'whose', mistakeType: 'pronoun_wrong_relative' }], explanationRationale: 'The manager called the person, making whom the object.' }),
  make({ ...none, id: 'relative-whose-hard', skill: 'relative', sentenceTemplate: 'The clerk ____ desk is near the door is new.', antecedent: 'clerk', antecedentNumber: 'singular', antecedentPerson: 'third', antecedentKind: 'person', pronounType: 'relative', pronounCase: 'possessive', relativeRole: 'possessive', nonrestrictive: false, correctChoice: 'whose', ruleFamily: 'relative', ruleDetail: 'Whose expresses possession by the clerk.', completedSentence: 'The clerk whose desk is near the door is new.', difficulty: 'hard', distractors: [{ text: "who's", mistakeType: 'pronoun_possessive_contraction' }, { text: 'whom', mistakeType: 'pronoun_wrong_relative' }, { text: 'which', mistakeType: 'pronoun_wrong_relative' }], explanationRationale: 'Whose correctly connects the clerk with the clerk’s desk.' }),

  make({ ...none, id: 'modifier-adverb-easy', skill: 'adjective_adverb', sentenceTemplate: 'She completed the task ____.', correctChoice: 'carefully', modifierType: 'adverb', modifiedTarget: 'completed', modifierPlacement: 'clear', ruleFamily: 'adjective_adverb', ruleDetail: 'An adverb modifies the action completed.', completedSentence: 'She completed the task carefully.', difficulty: 'easy', distractors: [{ text: 'careful', mistakeType: 'pronoun_adjective_adverb' }, { text: 'care', mistakeType: 'pronoun_adjective_adverb' }, { text: 'carefulness', mistakeType: 'pronoun_adjective_adverb' }], explanationRationale: 'Carefully is the adverb that describes how she completed the task.' }),
  make({ ...none, id: 'modifier-linking-medium', skill: 'adjective_adverb', sentenceTemplate: 'The final report is ____.', correctChoice: 'accurate', modifierType: 'adjective', modifiedTarget: 'report', modifierPlacement: 'clear', ruleFamily: 'adjective_adverb', ruleDetail: 'A linking verb connects the subject with an adjective.', completedSentence: 'The final report is accurate.', difficulty: 'medium', distractors: [{ text: 'accurately', mistakeType: 'pronoun_adjective_adverb' }, { text: 'accuracy', mistakeType: 'pronoun_adjective_adverb' }, { text: 'accurateness', mistakeType: 'pronoun_adjective_adverb' }], explanationRationale: 'Accurate describes report after the linking verb is.' }),
  make({ ...none, id: 'modifier-degree-hard', skill: 'adjective_adverb', sentenceTemplate: 'The instructions were ____ clear.', correctChoice: 'surprisingly', modifierType: 'adverb', modifiedTarget: 'clear', modifierPlacement: 'clear', ruleFamily: 'adjective_adverb', ruleDetail: 'An adverb modifies the adjective clear.', completedSentence: 'The instructions were surprisingly clear.', difficulty: 'hard', distractors: [{ text: 'surprising', mistakeType: 'pronoun_adjective_adverb' }, { text: 'surprise', mistakeType: 'pronoun_adjective_adverb' }, { text: 'surprised', mistakeType: 'pronoun_adjective_adverb' }], explanationRationale: 'Surprisingly is an adverb modifying the adjective clear.' }),

  make({ ...none, id: 'comparative-efficient-easy', skill: 'comparative', sentenceTemplate: 'This method is ____ than the old one.', correctChoice: 'more efficient', modifierType: 'comparative', modifiedTarget: 'method', modifierPlacement: 'clear', ruleFamily: 'comparative', ruleDetail: 'Efficient forms its comparative with more.', completedSentence: 'This method is more efficient than the old one.', difficulty: 'easy', distractors: [{ text: 'more efficienter', mistakeType: 'pronoun_double_comparison' }, { text: 'most efficient', mistakeType: 'pronoun_double_comparison' }, { text: 'efficient', mistakeType: 'pronoun_double_comparison' }], explanationRationale: 'More efficient is the standard comparative for two methods.' }),
  make({ ...none, id: 'comparative-fewer-medium', skill: 'comparative', sentenceTemplate: '____ applicants attended the afternoon session.', correctChoice: 'Fewer', modifierType: 'comparative', modifiedTarget: 'applicants', modifierPlacement: 'clear', ruleFamily: 'comparative', ruleDetail: 'Fewer modifies plural count nouns.', completedSentence: 'Fewer applicants attended the afternoon session.', difficulty: 'medium', distractors: [{ text: 'Less', mistakeType: 'pronoun_fewer_less' }, { text: 'Lesser', mistakeType: 'pronoun_fewer_less' }, { text: 'Fewest of', mistakeType: 'pronoun_double_comparison' }], explanationRationale: 'Applicants can be counted, so fewer is correct.' }),
  make({ ...none, id: 'comparative-quickly-hard', skill: 'comparative', sentenceTemplate: 'She completed the task ____ than before.', correctChoice: 'more quickly', modifierType: 'comparative', modifiedTarget: 'completed', modifierPlacement: 'clear', ruleFamily: 'comparative', ruleDetail: 'The adverb quickly forms its comparative with more.', completedSentence: 'She completed the task more quickly than before.', difficulty: 'hard', distractors: [{ text: 'more quicker', mistakeType: 'pronoun_double_comparison' }, { text: 'quickest', mistakeType: 'pronoun_double_comparison' }, { text: 'quick', mistakeType: 'pronoun_adjective_adverb' }], explanationRationale: 'More quickly correctly compares how the task was completed.' }),

  make({ ...none, id: 'misplaced-nearly-easy', skill: 'misplaced', sentenceTemplate: 'Choose the sentence meaning that almost all reports were filed: ____', correctChoice: 'She filed nearly all the reports.', modifierType: 'misplaced', modifiedTarget: 'all the reports', modifierPlacement: 'clear', ruleFamily: 'misplaced', ruleDetail: 'Place nearly next to all the reports.', completedSentence: 'Choose the sentence meaning that almost all reports were filed: She filed nearly all the reports.', difficulty: 'easy', distractors: [{ text: 'She nearly filed all the reports.', mistakeType: 'pronoun_wrong_modifier_target' }, { text: 'Nearly she filed all the reports.', mistakeType: 'pronoun_wrong_modifier_target' }, { text: 'She filed all nearly the reports.', mistakeType: 'pronoun_wrong_modifier_target' }], explanationRationale: 'Nearly directly modifies all and produces the intended quantity meaning.' }),
  make({ ...none, id: 'misplaced-form-medium', skill: 'misplaced', sentenceTemplate: 'Choose the clearest revision: ____', correctChoice: 'The employee submitted the form with missing information to the clerk.', modifierType: 'misplaced', modifiedTarget: 'form', modifierPlacement: 'clear', ruleFamily: 'misplaced', ruleDetail: 'Place with missing information next to form.', completedSentence: 'Choose the clearest revision: The employee submitted the form with missing information to the clerk.', difficulty: 'medium', distractors: [{ text: 'The employee submitted the form to the clerk with missing information.', mistakeType: 'pronoun_wrong_modifier_target' }, { text: 'With missing information, the clerk received the employee.', mistakeType: 'pronoun_wrong_modifier_target' }, { text: 'The employee with missing information submitted the form to the clerk.', mistakeType: 'pronoun_wrong_modifier_target' }], explanationRationale: 'The revised placement makes form, not clerk or employee, the target.' }),
  make({ ...none, id: 'misplaced-only-hard', skill: 'misplaced', sentenceTemplate: 'Choose the sentence meaning that no one except the manager approved the request: ____', correctChoice: 'Only the manager approved the request.', modifierType: 'misplaced', modifiedTarget: 'manager', modifierPlacement: 'clear', ruleFamily: 'misplaced', ruleDetail: 'Place only immediately before manager.', completedSentence: 'Choose the sentence meaning that no one except the manager approved the request: Only the manager approved the request.', difficulty: 'hard', distractors: [{ text: 'The manager only approved the request.', mistakeType: 'pronoun_wrong_modifier_target' }, { text: 'The manager approved only the request.', mistakeType: 'pronoun_wrong_modifier_target' }, { text: 'The manager approved the only request.', mistakeType: 'pronoun_wrong_modifier_target' }], explanationRationale: 'Only directly before manager limits who performed the approval.' }),

  make({ ...none, id: 'dangling-walking-easy', skill: 'dangling', sentenceTemplate: 'Choose the logical office-arrival revision: ____', correctChoice: 'Walking into the office, the employee noticed the open window.', modifierType: 'dangling', modifiedTarget: 'employee', modifierPlacement: 'clear', impliedActor: 'employee', mainClauseSubject: 'employee', ruleFamily: 'dangling', ruleDetail: 'The main-clause subject must be the person walking.', completedSentence: 'Choose the logical office-arrival revision: Walking into the office, the employee noticed the open window.', difficulty: 'easy', distractors: [{ text: 'Walking into the office, the open window was noticed.', mistakeType: 'pronoun_dangling_modifier' }, { text: 'Walking into the office, there was an open window.', mistakeType: 'pronoun_dangling_modifier' }, { text: 'Walking into the office, the rain began.', mistakeType: 'pronoun_dangling_modifier' }], explanationRationale: 'Employee is explicitly the actor who walks into the office.' }),
  make({ ...none, id: 'dangling-reviewing-medium', skill: 'dangling', sentenceTemplate: 'Choose the logical report-review revision: ____', correctChoice: 'After reviewing the report, the supervisor found several errors.', modifierType: 'dangling', modifiedTarget: 'supervisor', modifierPlacement: 'clear', impliedActor: 'supervisor', mainClauseSubject: 'supervisor', ruleFamily: 'dangling', ruleDetail: 'The reviewer must be the main-clause subject.', completedSentence: 'Choose the logical report-review revision: After reviewing the report, the supervisor found several errors.', difficulty: 'medium', distractors: [{ text: 'After reviewing the report, several errors were found.', mistakeType: 'pronoun_dangling_modifier' }, { text: 'After reviewing the report, it contained several errors.', mistakeType: 'pronoun_dangling_modifier' }, { text: 'After reviewing the report, the errors surprised everyone.', mistakeType: 'pronoun_dangling_modifier' }], explanationRationale: 'Supervisor logically performs both reviewing and finding.' }),
  make({ ...none, id: 'dangling-checking-hard', skill: 'dangling', sentenceTemplate: 'Choose the logical record-checking revision: ____', correctChoice: 'Having checked every entry, the clerk submitted the record.', modifierType: 'dangling', modifiedTarget: 'clerk', modifierPlacement: 'clear', impliedActor: 'clerk', mainClauseSubject: 'clerk', ruleFamily: 'dangling', ruleDetail: 'The checker must appear as the main-clause subject.', completedSentence: 'Choose the logical record-checking revision: Having checked every entry, the clerk submitted the record.', difficulty: 'hard', distractors: [{ text: 'Having checked every entry, the record was submitted.', mistakeType: 'pronoun_dangling_modifier' }, { text: 'Having checked every entry, submission followed.', mistakeType: 'pronoun_dangling_modifier' }, { text: 'Having checked every entry, the office received the record.', mistakeType: 'pronoun_dangling_modifier' }], explanationRationale: 'Clerk is the stated actor of both checking and submitting.' }),
]

export function findPronounsModifiersEntry(id: string): PronounModifierEntry | null { return pronounsModifiersBankV1.find((entry) => entry.id === id) ?? null }
