import { findReadingComprehensionEntry, findReadingPassage, readingComprehensionBankV1 } from '../../domain/reading-comprehension/reading-comprehension-bank'
import { readingDistractor, selectReadingDistractors } from '../../domain/reading-comprehension/reading-comprehension-distractors'
import { formatPassagePrompt, readingNumericValue, readingSkillLabel } from '../../domain/reading-comprehension/reading-comprehension-format'
import { causeEffectValid, contextualSenseValid, detailsValid, evidenceMappingValid, factOpinionConclusionValid, inferenceSupportValid, mainIdeaValid, passageLengthValid, purposeToneValid, readingAnswerMatches, sequenceValid } from '../../domain/reading-comprehension/reading-comprehension-rules'
import { uniqueReadingAnswer, uniqueReadingChoices } from '../../domain/reading-comprehension/reading-comprehension-validation'
import type { ReadingSkill } from '../../domain/reading-comprehension/reading-comprehension.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const slugs = ['main-idea-comprehension', 'supporting-detail-comprehension', 'sequence-organization-comprehension', 'cause-effect-comprehension', 'vocabulary-in-context-comprehension', 'inference-comprehension', 'author-purpose-tone-comprehension', 'fact-opinion-conclusion-comprehension', 'mixed-reading-comprehension'] as const satisfies readonly GeneratorSlug[]
const skills = ['main_idea', 'supporting_detail', 'sequence_organization', 'cause_effect', 'vocabulary_context', 'inference', 'purpose_tone', 'fact_opinion_conclusion'] as const satisfies readonly ReadingSkill[]
const frames = [(passage: string) => passage, (passage: string, skill: string) => `Read carefully and apply ${skill}.\n\n${passage}`, (passage: string) => `Use only evidence from this original passage.\n\n${passage}`] as const
function pool(slug: GeneratorSlug, difficulty: GeneratorDifficulty) { const index = slugs.indexOf(slug as (typeof slugs)[number]); const entries = (index === 8 ? readingComprehensionBankV1 : readingComprehensionBankV1.filter((entry) => entry.skill === skills[index])).filter((entry) => findReadingPassage(entry.passageId)?.difficulty === difficulty); return entries.flatMap((entry) => { const passage = findReadingPassage(entry.passageId)!; const formatted = formatPassagePrompt(passage, entry.question); return frames.map((frame, variant) => ({ entry, passage, variant, prompt: frame(formatted, readingSkillLabel(entry.skill)) })) }) }
function build(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`); const scenario = random.pick(pool(slug, input.difficulty)); const { entry, passage } = scenario; const distractors = selectReadingDistractors(entry.correctChoice, entry.distractors.map((item) => readingDistractor(item.text, item.mistakeType))); const choices = random.shuffle([{ text: entry.correctChoice, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: readingNumericValue(entry.correctChoice) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [readingNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: readingNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: 1, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: { entryId: entry.id, passageId: passage.id, passageTitle: passage.title, passageText: passage.text, evidence: entry.evidence.map((item) => ({ ...item })), skill: entry.skill, recomputedCorrect: entry.correctChoice, scenarioSignature: `${entry.id}|${scenario.variant}` }, choices, explanation: { title: 'Reading Comprehension solution', steps: [`The primary reading skill is ${readingSkillLabel(entry.skill)}.`, `The answer must be supported by the passage "${passage.title}."`, ...entry.evidence.map((item) => `Evidence: "${item.text}" ${item.supports}`), entry.explanationRationale], finalAnswer: entry.correctChoice }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${entry.id}|${scenario.variant}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const id = question.parameters.entryId; const answer = question.parameters.recomputedCorrect; const entry = typeof id === 'string' ? findReadingComprehensionEntry(id) : null; const passage = entry === null ? null : findReadingPassage(entry.passageId); const choices = question.choices.map((choice) => choice.text); const valid = entry !== null && passage !== null && typeof answer === 'string' && answer === entry.correctChoice && question.parameters.passageText === passage.text && question.prompt.includes(passage.text) && passageLengthValid(passage) && mainIdeaValid(passage) && detailsValid(passage) && sequenceValid(passage) && causeEffectValid(passage) && contextualSenseValid(passage) && inferenceSupportValid(passage) && purposeToneValid(passage) && factOpinionConclusionValid(passage) && evidenceMappingValid(passage, entry) && readingAnswerMatches(entry, answer) && uniqueReadingChoices(choices) && uniqueReadingAnswer(choices, answer) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('reading_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Reading-comprehension validation failed.' } }
const make = (slug: GeneratorSlug): QuestionGenerator => ({ slug, version: 1, title: slug.replaceAll('-', ' '), supportedDifficulties: ['easy', 'medium', 'hard'], generate: (input) => build(slug, input), validate })
export const readingComprehensionGenerators = slugs.map(make)
