import { findParagraphOrganizationEntry, paragraphOrganizationBankV1 } from '../../domain/paragraph-organization/paragraph-organization-bank'
import { paragraphDistractor, selectParagraphDistractors } from '../../domain/paragraph-organization/paragraph-organization-distractors'
import { displaySentenceNodes, paragraphNumericValue, paragraphSkillLabel } from '../../domain/paragraph-organization/paragraph-organization-format'
import { causeEffectValid, comparisonPairsValid, chronologyValid, hierarchyValid, openingClosingValid, referenceLinksValid, supportRelationsValid, topicSentenceValid, transitionLinksValid } from '../../domain/paragraph-organization/paragraph-organization-rules'
import { hasUniqueParagraphOrder } from '../../domain/paragraph-organization/paragraph-organization-solver'
import { uniqueParagraphAnswer, uniqueParagraphChoices } from '../../domain/paragraph-organization/paragraph-organization-validation'
import type { ParagraphSkill } from '../../domain/paragraph-organization/paragraph-organization.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const slugs = ['topic-sentence-identification', 'supporting-detail-order', 'chronological-paragraph-order', 'cause-effect-paragraph-order', 'comparison-contrast-order', 'general-specific-order', 'transition-link-order', 'opening-closing-sentence', 'mixed-paragraph-organization'] as const satisfies readonly GeneratorSlug[]
const skills = ['topic_sentence', 'supporting_detail', 'chronological', 'cause_effect', 'comparison_contrast', 'general_specific', 'transition_link', 'opening_closing'] as const satisfies readonly ParagraphSkill[]
const frames = [(stem: string, nodes: string) => `${stem} ${nodes}`, (stem: string, nodes: string) => `Organize the four labeled sentences. ${stem} ${nodes}`, (stem: string, nodes: string, skill: string) => `Apply ${skill}. ${stem} ${nodes}`] as const
function pool(slug: GeneratorSlug, difficulty: GeneratorDifficulty) { const index = slugs.indexOf(slug as (typeof slugs)[number]); const entries = (index === 8 ? paragraphOrganizationBankV1 : paragraphOrganizationBankV1.filter((entry) => entry.skill === skills[index])).filter((entry) => entry.difficulty === difficulty); return entries.flatMap((entry) => frames.map((frame, variant) => ({ entry, variant, prompt: frame(entry.promptStem, displaySentenceNodes(entry.nodes), paragraphSkillLabel(entry.skill)) }))) }
function build(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`); const scenario = random.pick(pool(slug, input.difficulty)); const entry = scenario.entry; const distractors = selectParagraphDistractors(entry.correctChoice, entry.distractors.map((item) => paragraphDistractor(item.text, item.mistakeType))); const choices = random.shuffle([{ text: entry.correctChoice, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: paragraphNumericValue(entry.correctChoice) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [paragraphNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: paragraphNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: 1, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: { entryId: entry.id, skill: entry.skill, organizationType: entry.organizationType, correctOrder: [...entry.correctOrder], recomputedCorrect: entry.correctChoice, scenarioSignature: `${entry.id}|${scenario.variant}` }, choices, explanation: { title: 'Paragraph Organization solution', steps: [`The primary pattern is ${paragraphSkillLabel(entry.skill)}.`, `Start with ${entry.openingSentenceId}, then satisfy the stored sentence dependencies.`, `The reference and transition links lead to ${entry.correctOrder.join('-')}.`, entry.explanationRationale, `The supported answer is "${entry.correctChoice}".`], finalAnswer: entry.correctChoice }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${entry.id}|${scenario.variant}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const id = question.parameters.entryId; const answer = question.parameters.recomputedCorrect; const entry = typeof id === 'string' ? findParagraphOrganizationEntry(id) : null; const choices = question.choices.map((choice) => choice.text); const valid = entry !== null && typeof answer === 'string' && answer === entry.correctChoice && hasUniqueParagraphOrder(entry.nodes, entry.dependencies, entry.correctOrder) && topicSentenceValid(entry) && supportRelationsValid(entry) && chronologyValid(entry) && causeEffectValid(entry) && comparisonPairsValid(entry) && hierarchyValid(entry) && referenceLinksValid(entry) && transitionLinksValid(entry) && openingClosingValid(entry) && uniqueParagraphChoices(choices) && uniqueParagraphAnswer(choices, answer) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('paragraph_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Paragraph-organization validation failed.' } }
const make = (slug: GeneratorSlug): QuestionGenerator => ({ slug, version: 1, title: slug.replaceAll('-', ' '), supportedDifficulties: ['easy', 'medium', 'hard'], generate: (input) => build(slug, input), validate })
export const paragraphOrganizationGenerators = slugs.map(make)
