import { findSubjectVerbAgreementEntry, subjectVerbAgreementBankV1 } from '../../domain/subject-verb-agreement/subject-verb-agreement-bank'
import { agreementDistractor, selectAgreementDistractors } from '../../domain/subject-verb-agreement/subject-verb-agreement-distractors'
import { agreementNumericValue, agreementSkillLabel } from '../../domain/subject-verb-agreement/subject-verb-agreement-format'
import { agreementAnswerMatches, agreementSentenceValid, collectiveQuantityValid, compoundSubjectValid, indefinitePronounValid, invertedSubjectValid, proximityAgreementValid, specialCaseValid, interveningPhraseValid, verbFormValid } from '../../domain/subject-verb-agreement/subject-verb-agreement-rules'
import { uniqueAgreementAnswer, uniqueAgreementChoices } from '../../domain/subject-verb-agreement/subject-verb-agreement-validation'
import type { AgreementSkill } from '../../domain/subject-verb-agreement/subject-verb-agreement.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const slugs = ['basic-subject-verb-agreement', 'compound-subject-agreement', 'either-or-neither-nor-agreement', 'indefinite-pronoun-agreement', 'collective-quantity-agreement', 'intervening-phrase-agreement', 'inverted-sentence-agreement', 'special-case-agreement', 'mixed-subject-verb-agreement'] as const satisfies readonly GeneratorSlug[]
const skills = ['basic', 'compound', 'proximity', 'indefinite', 'collective_quantity', 'intervening', 'inverted', 'special'] as const satisfies readonly AgreementSkill[]
const frames = [(template: string) => `Choose the verb that agrees with the true subject: "${template}"`, (template: string) => `Which verb completes this sentence correctly? "${template}"`, (template: string, skill: string) => `Apply ${skill}: "${template}"`] as const
function pool(slug: GeneratorSlug, difficulty: GeneratorDifficulty) { const index = slugs.indexOf(slug as (typeof slugs)[number]); const entries = (index === 8 ? subjectVerbAgreementBankV1 : subjectVerbAgreementBankV1.filter((item) => item.skill === skills[index])).filter((item) => item.difficulty === difficulty); return entries.flatMap((item) => frames.map((frame, variant) => ({ item, variant, prompt: frame(item.sentenceTemplate, agreementSkillLabel(item.skill)) }))) }
function build(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`); const scenario = random.pick(pool(slug, input.difficulty)); const entry = scenario.item; const distractors = selectAgreementDistractors(entry.correctForm, entry.distractors.map((item) => agreementDistractor(item.text, item.mistakeType))); const choices = random.shuffle([{ text: entry.correctForm, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: agreementNumericValue(entry.correctForm) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [agreementNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: agreementNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: 1, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: { entryId: entry.id, skill: entry.skill, grammaticalSubject: entry.grammaticalSubject, subjectNumber: entry.subjectNumber, verbLemma: entry.verbLemma, recomputedCorrect: entry.correctForm, scenarioSignature: `${entry.id}|${scenario.variant}` }, choices, explanation: { title: 'Subject–Verb Agreement solution', steps: [`The grammatical subject is "${entry.grammaticalSubject}."`, `It is ${entry.subjectNumber} and requires agreement under ${agreementSkillLabel(entry.skill)}.`, entry.ruleDetail, entry.explanationRationale, `The completed sentence is: "${entry.completedSentence}"`], finalAnswer: entry.correctForm }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${entry.id}|${scenario.variant}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const id = question.parameters.entryId; const answer = question.parameters.recomputedCorrect; const entry = typeof id === 'string' ? findSubjectVerbAgreementEntry(id) : null; const choices = question.choices.map((choice) => choice.text); const valid = entry !== null && typeof answer === 'string' && answer === entry.correctForm && verbFormValid(entry) && agreementSentenceValid(entry) && agreementAnswerMatches(entry, answer) && compoundSubjectValid(entry) && proximityAgreementValid(entry) && indefinitePronounValid(entry) && collectiveQuantityValid(entry) && interveningPhraseValid(entry) && invertedSubjectValid(entry) && specialCaseValid(entry) && uniqueAgreementChoices(choices) && uniqueAgreementAnswer(choices, answer) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('agreement_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Subject–verb agreement validation failed.' } }
const make = (slug: GeneratorSlug): QuestionGenerator => ({ slug, version: 1, title: slug.replaceAll('-', ' '), supportedDifficulties: ['easy', 'medium', 'hard'], generate: (input) => build(slug, input), validate })
export const subjectVerbAgreementGenerators = slugs.map(make)
