import { findGrammarUsageEntry, grammarUsageBankV1 } from '../../domain/grammar-usage/grammar-usage-bank'
import { grammarDistractor, selectGrammarDistractors } from '../../domain/grammar-usage/grammar-usage-distractors'
import { grammarNumericValue, grammarSkillLabel } from '../../domain/grammar-usage/grammar-usage-format'
import { articleDeterminerValid, commonUsageValid, comparisonValid, conjunctionRelationshipValid, correlativePairValid, countabilityValid, prepositionPatternValid, semanticRuleMatch, sentenceCorrectnessValid, timeMarkerCompatible } from '../../domain/grammar-usage/grammar-usage-rules'
import { uniqueGrammarAnswer, uniqueGrammarChoices } from '../../domain/grammar-usage/grammar-usage-validation'
import type { GrammarUsageSkill } from '../../domain/grammar-usage/grammar-usage.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const slugs = ['part-of-speech-usage', 'verb-tense-consistency', 'article-determiner-usage', 'preposition-usage', 'conjunction-usage', 'comparative-superlative-usage', 'commonly-misused-expression', 'correct-sentence-usage', 'mixed-grammar-usage'] as const satisfies readonly GeneratorSlug[]
const skills = ['part_of_speech', 'verb_tense', 'article_determiner', 'preposition', 'conjunction', 'comparison', 'misused_expression', 'correct_sentence'] as const satisfies readonly GrammarUsageSkill[]
const promptFrames = [(template: string) => `Choose the standard-English answer: "${template}"`, (template: string) => `Which option applies the grammar rule correctly? "${template}"`, (template: string, skill: string) => `Apply ${skill} rules to this item: "${template}"`] as const
function scenarioPool(slug: GeneratorSlug, difficulty: GeneratorDifficulty) { const index = slugs.indexOf(slug as (typeof slugs)[number]); const entries = (index === 8 ? grammarUsageBankV1 : grammarUsageBankV1.filter((entry) => entry.skill === skills[index])).filter((entry) => entry.difficulty === difficulty); return entries.flatMap((entry) => promptFrames.map((frame, variant) => ({ entry, variant, prompt: frame(entry.sentenceTemplate, grammarSkillLabel(entry.skill)) }))) }
function build(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`); const scenario = random.pick(scenarioPool(slug, input.difficulty)); const entry = scenario.entry; const distractors = selectGrammarDistractors(entry.correctChoice, entry.distractors.map((item) => grammarDistractor(item.text, item.mistakeType))); const choices = random.shuffle([{ text: entry.correctChoice, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: grammarNumericValue(entry.correctChoice) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [grammarNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: grammarNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: 1, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: { entryId: entry.id, skill: entry.skill, targetRule: entry.targetRule, recomputedCorrect: entry.correctChoice, scenarioSignature: `${entry.id}|${scenario.variant}` }, choices, explanation: { title: 'Grammar and Correct Usage solution', steps: [`The primary rule is ${grammarSkillLabel(entry.skill)}.`, entry.targetRule, entry.explanationRationale, `The correct standard form is: "${entry.completedSentence}"`, 'Each rejected option represents a documented grammar or usage mistake.'], finalAnswer: entry.correctChoice }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${entry.id}|${scenario.variant}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const entryId = question.parameters.entryId; const answer = question.parameters.recomputedCorrect; const entry = typeof entryId === 'string' ? findGrammarUsageEntry(entryId) : null; const choices = question.choices.map((choice) => choice.text); const valid = entry !== null && typeof answer === 'string' && answer === entry.correctChoice && sentenceCorrectnessValid(entry) && semanticRuleMatch(entry, answer) && timeMarkerCompatible(entry) && articleDeterminerValid(entry) && countabilityValid(entry) && prepositionPatternValid(entry) && conjunctionRelationshipValid(entry) && correlativePairValid(entry) && comparisonValid(entry) && commonUsageValid(entry) && uniqueGrammarChoices(choices) && uniqueGrammarAnswer(choices, answer) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('grammar_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Grammar usage validation failed.' } }
const make = (slug: GeneratorSlug): QuestionGenerator => ({ slug, version: 1, title: slug.replaceAll('-', ' '), supportedDifficulties: ['easy', 'medium', 'hard'], generate: (input) => build(slug, input), validate })
export const grammarUsageGenerators = slugs.map(make)
