import { synonymsAntonymsBankV1 } from '../../domain/synonyms-antonyms/synonyms-antonyms-bank'
import { selectSynonymAntonymDistractors, synonymAntonymDistractor } from '../../domain/synonyms-antonyms/synonyms-antonyms-distractors'
import { relationNumericValue } from '../../domain/synonyms-antonyms/synonyms-antonyms-format'
import { validateSynonymAntonymScenario, uniqueCorrectAnswer, uniqueVisibleChoices } from '../../domain/synonyms-antonyms/synonyms-antonyms-validation'
import type { SynonymAntonymMistakeType, SynonymAntonymScenario } from '../../domain/synonyms-antonyms/synonyms-antonyms.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const version = 1
const supportedDifficulties = ['easy', 'medium', 'hard'] as const
const wrong = (text: string, mistake: SynonymAntonymMistakeType) => [text, mistake] as const
const makeScenario = (prompt: string, correct: string, targetWord: string, signature: string, rule: string, distractors: readonly (readonly [string, SynonymAntonymMistakeType])[]): SynonymAntonymScenario => ({ prompt, correct, targetWord, signature, explanation: [rule, `The correct answer is “${correct}.”`], distractors: distractors.map(([text, mistake]) => ({ text, mistake })) })

const synonymData = [
  ['assist', 'help', 'hinder', 'Staff will assist visitors at the counter.'], ['begin', 'start', 'end', 'The meeting will begin at nine.'], ['rapid', 'fast', 'slow', 'The office reported rapid improvement.'], ['permit', 'allow', 'prohibit', 'The rules permit one valid identification card.'], ['purchase', 'buy', 'sell', 'The unit will purchase new folders.'], ['reply', 'respond', 'ignore', 'Please reply before Friday.'], ['accurate', 'correct', 'incorrect', 'Submit an accurate inventory count.'], ['brief', 'concise', 'lengthy', 'The supervisor issued a brief instruction.'],
] as const
const antonymData = [
  ['scarce', 'abundant', 'limited'], ['expand', 'contract', 'enlarge'], ['temporary', 'permanent', 'short-term'], ['accurate', 'incorrect', 'correct'], ['permit', 'prohibit', 'allow'], ['begin', 'end', 'start'], ['clear', 'confusing', 'plain'], ['stable', 'unstable', 'steady'],
] as const

function basicSynonyms(): SynonymAntonymScenario[] { return synonymData.map(([target, answer, opposite], index) => makeScenario(`Which word is closest in meaning to “${target}”?`, answer, target, `basic-synonym|${target}`, `${answer} preserves the common sense and grammatical role of ${target}.`, [wrong(opposite, 'synant_wrong_relationship'), wrong(antonymData[(index + 2) % antonymData.length]![0], 'synant_related_not_equivalent'), wrong(`${answer}ing`, 'synant_wrong_part_of_speech')])) }
function basicAntonyms(): SynonymAntonymScenario[] { return antonymData.map(([target, answer, synonym], index) => makeScenario(`Which word is opposite in meaning to “${target}”?`, answer, target, `basic-antonym|${target}`, `${answer} expresses the direct contextual opposite of ${target}.`, [wrong(synonym, 'synant_wrong_relationship'), wrong(synonymData[(index + 3) % synonymData.length]![0], 'synant_related_not_equivalent'), wrong(`${answer}ly`, 'synant_wrong_part_of_speech')])) }
function contextSynonyms(): SynonymAntonymScenario[] { return synonymData.map(([target, answer, opposite, sentence], index) => makeScenario(`In “${sentence}” which word best replaces “${target}”?`, answer, target, `context-synonym|${target}`, `The sentence selects the shared sense of ${target} and ${answer}.`, [wrong(opposite, 'synant_wrong_relationship'), wrong(index % 2 === 0 ? 'address' : 'record', 'synant_wrong_sense'), wrong(`${answer}ly`, 'synant_wrong_part_of_speech')])) }
function contextAntonyms(): SynonymAntonymScenario[] { const contexts = [['clear', 'confusing', 'The instructions were clear.'], ['stable', 'unstable', 'Attendance remained stable this month.'], ['brief', 'lengthy', 'The supervisor issued a brief instruction.'], ['expand', 'contract', 'The office will expand its service area.'], ['temporary', 'permanent', 'The office uses a temporary entrance.'], ['accurate', 'incorrect', 'Submit an accurate inventory count.'], ['permit', 'prohibit', 'The rules permit one valid identification card.'], ['begin', 'end', 'The meeting will begin at nine.']] as const; return contexts.map(([target, answer, sentence], index) => makeScenario(`In “${sentence}” which word best reverses the meaning of “${target}”?`, answer, target, `context-antonym|${target}`, `The context requires the direct opposite ${answer} while preserving grammatical role.`, [wrong(synonymData[index]![1], 'synant_wrong_relationship'), wrong(index % 2 === 0 ? 'furious' : 'economical', 'synant_related_not_equivalent'), wrong(`${answer}ly`, 'synant_wrong_part_of_speech')])) }
function intensityScenarios(): SynonymAntonymScenario[] { const rows = [['angry', 'furious', 'Which word is stronger than “angry”?', 'upset', 'calm'], ['warm', 'hot', 'Which word expresses greater heat than “warm”?', 'mild', 'cool'], ['furious', 'angry', 'Which word is weaker than “furious”?', 'enraged', 'calm'], ['hot', 'warm', 'Which word is weaker than “hot”?', 'scorching', 'cold'], ['brief', 'concise', 'Which word most closely matches the moderate degree of “brief”?', 'tiny', 'lengthy'], ['rapid', 'fast', 'Which word has comparable intensity to “rapid”?', 'slow', 'instant'], ['confident', 'self-assured', 'Which word matches the degree of “confident”?', 'arrogant', 'uncertain'], ['scarce', 'limited', 'Which word best matches the degree of “scarce”?', 'absent', 'abundant']] as const; return rows.map(([target, answer, prompt, mismatch, opposite]) => makeScenario(prompt, answer, target, `intensity|${target}|${answer}`, `The selected word preserves the intended strength; ${mismatch} changes the degree.`, [wrong(mismatch, 'synant_intensity_mismatch'), wrong(opposite, 'synant_wrong_relationship'), wrong('response', 'synant_related_not_equivalent')])) }
function toneScenarios(): SynonymAntonymScenario[] { const rows = [['confident', 'confident', 'Which word presents self-assurance positively?', 'arrogant'], ['arrogant', 'confident', 'Which replacement gives “arrogant” a more positive tone?', 'conceited'], ['economical', 'economical', 'Which word praises careful use of resources?', 'cheap'], ['cheap', 'economical', 'Which replacement gives “cheap” a more favorable tone?', 'wasteful'], ['confident', 'self-assured', 'Which neutral-positive word is closest to “confident”?', 'boastful'], ['arrogant', 'conceited', 'Which word preserves the negative tone of “arrogant”?', 'confident'], ['economical', 'efficient', 'Which word keeps the favorable tone of “economical”?', 'cheap'], ['cheap', 'inexpensive', 'Which word is a more neutral replacement for “cheap”?', 'costly']] as const; return rows.map(([target, answer, prompt, contrast]) => makeScenario(prompt, answer, target, `tone|${target}|${answer}`, `${answer} supplies the requested broadly recognized tone in this context.`, [wrong(contrast, 'synant_connotation_mismatch'), wrong('furious', 'synant_intensity_mismatch'), wrong('contract', 'synant_wrong_relationship')])) }
function registerScenarios(): SynonymAntonymScenario[] { const rows = [['buy', 'purchase', 'formal'], ['help', 'assist', 'formal'], ['ask', 'inquire', 'formal'], ['begin', 'commence', 'formal'], ['end', 'terminate', 'formal'], ['purchase', 'buy', 'informal'], ['assist', 'help', 'informal'], ['inquire', 'ask', 'informal'], ['commence', 'begin', 'informal'], ['terminate', 'end', 'informal']] as const; return rows.map(([target, answer, register], index) => makeScenario(`Which ${register} equivalent best replaces “${target}”?`, answer, target, `register|${target}|${register}`, `${answer} preserves meaning and part of speech while matching the requested register.`, [wrong(index % 2 === 0 ? target : 'respond', 'synant_register_mismatch'), wrong('accurate', 'synant_wrong_part_of_speech'), wrong('contract', 'synant_related_not_equivalent')])) }
function sentenceScenarios(): SynonymAntonymScenario[] { return [...contextSynonyms().map((item) => ({ ...item, signature: `sentence|syn|${item.signature}` })), ...contextAntonyms().map((item) => ({ ...item, signature: `sentence|ant|${item.signature}` }))] }
function scenariosFor(slug: GeneratorSlug): SynonymAntonymScenario[] { switch (slug) { case 'basic-synonym': return basicSynonyms(); case 'basic-antonym': return basicAntonyms(); case 'context-sensitive-synonym': return contextSynonyms(); case 'context-sensitive-antonym': return contextAntonyms(); case 'degree-intensity-synonym': return intensityScenarios(); case 'connotation-tone-synonym': return toneScenarios(); case 'formal-informal-equivalent': return registerScenarios(); case 'sentence-synonym-antonym': return sentenceScenarios(); case 'mixed-synonyms-antonyms': return [...basicSynonyms(), ...basicAntonyms(), ...contextSynonyms(), ...contextAntonyms(), ...intensityScenarios(), ...toneScenarios(), ...registerScenarios()]; default: throw new Error(`Unsupported synonym/antonym generator ${slug}.`) } }

function buildQuestion(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|${version}|${input.difficulty}`); const selected = random.pick(scenariosFor(slug)); const scenarioError = validateSynonymAntonymScenario(selected); if (scenarioError !== null) throw new Error(scenarioError); const distractors = selectSynonymAntonymDistractors(selected.correct, selected.distractors.map((item) => synonymAntonymDistractor(item.text, item.mistake))); const choices = random.shuffle([{ text: selected.correct, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: relationNumericValue(selected.correct) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [relationNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: relationNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: version, difficulty: input.difficulty, seed: input.seed, prompt: selected.prompt, parameters: { targetWord: selected.targetWord, recomputedCorrect: selected.correct, scenarioSignature: selected.signature }, choices, explanation: { title: 'Synonyms and Antonyms solution', steps: [...selected.explanation], finalAnswer: selected.correct }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${input.difficulty}|${selected.signature}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const target = question.parameters.targetWord, correct = question.parameters.recomputedCorrect, choices = question.choices.map((item) => item.text); const valid = typeof target === 'string' && synonymsAntonymsBankV1.some((item) => item.word === target) && typeof correct === 'string' && uniqueVisibleChoices(choices) && uniqueCorrectAnswer(choices, correct) && question.choices.filter((item) => item.isCorrect).length === 1 && question.choices.find((item) => item.isCorrect)?.text === correct && question.choices.filter((item) => !item.isCorrect).every((item) => item.mistakeType?.startsWith('synant_') === true && item.derivation !== null); return { valid, reason: valid ? null : 'Synonym/antonym question failed relation, answer, or distractor validation.' } }
function generator(slug: GeneratorSlug, title: string): QuestionGenerator { return { slug, version, title, supportedDifficulties, generate: (input) => buildQuestion(slug, input), validate } }
export const synonymsAntonymsGenerators = [['basic-synonym', 'Basic Synonyms'], ['basic-antonym', 'Basic Antonyms'], ['context-sensitive-synonym', 'Context-Sensitive Synonyms'], ['context-sensitive-antonym', 'Context-Sensitive Antonyms'], ['degree-intensity-synonym', 'Degree and Intensity'], ['connotation-tone-synonym', 'Connotation and Tone'], ['formal-informal-equivalent', 'Formal and Informal Equivalents'], ['sentence-synonym-antonym', 'Synonyms and Antonyms in Sentences'], ['mixed-synonyms-antonyms', 'Mixed Synonyms and Antonyms']].map(([slug, title]) => generator(slug as GeneratorSlug, title ?? 'Synonyms and Antonyms'))
