import { entriesForEnvironmentCategory,environmentBankV1,findEnvironmentEntry } from '../../domain/environment-management/environment-management.bank'
import { environmentDistractor,selectEnvironmentDistractors } from '../../domain/environment-management/environment-management.distractors'
import { environmentCategoryLabel,environmentStableNumber,formatEnvironmentReference } from '../../domain/environment-management/environment-management.format'
import { eiaConceptValid,environmentDomainValid,environmentSourceComplete,institutionRoleValid,lawConceptValid,mitigationAdaptationValid,rejectsActiveControversy,rejectsCurrentPerson,rejectsProjectAdvice,rejectsUnsupportedScientificClaim,rejectsUnverifiedNumber,scenarioSafe,uniqueEnvironmentAnswer,uniqueVisibleChoices,wasteCategoryConceptValid } from '../../domain/environment-management/environment-management.rules'
import type { EnvironmentCategory,EnvironmentSource } from '../../domain/environment-management/environment-management.types'
import { validateEnvironmentEntry } from '../../domain/environment-management/environment-management.validation'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion,GeneratorDifficulty,GeneratorSlug,GeneratorValidationResult,QuestionGenerator } from '../generator.types'
const categoryBySlug={'environmental-rights-sustainability':'rights_sustainability','clean-air-management':'air','clean-water-management':'water','ecological-solid-waste':'solid_waste','toxic-hazardous-substances':'hazardous','biodiversity-wildlife-protected-areas':'biodiversity','environmental-impact-assessment':'eia','climate-mitigation-adaptation':'climate','environmental-institutions-action':'institutions'} as const satisfies Partial<Record<GeneratorSlug,EnvironmentCategory>>
const slugs=[...Object.keys(categoryBySlug),'mixed-environment-management'] as GeneratorSlug[]
const frames=[(concept:string,scenario:string)=>`Which source-verified statement accurately explains ${concept}? ${scenario}`,(concept:string,scenario:string)=>`${scenario} Which statement best applies ${concept}?`,(concept:string,scenario:string)=>`Select the accurate environmental-management statement about ${concept}. ${scenario}`,(concept:string,scenario:string)=>`Which choice preserves the governing source and safety limits for ${concept}? ${scenario}`]
function pool(slug:GeneratorSlug,difficulty:GeneratorDifficulty){const category=slug==='mixed-environment-management'?undefined:categoryBySlug[slug as keyof typeof categoryBySlug];const entries=(category===undefined?environmentBankV1:entriesForEnvironmentCategory(category)).filter((entry)=>entry.difficulty===difficulty);return entries.flatMap((entry)=>frames.map((frame,variant)=>({entry,variant,prompt:frame(entry.concept,entry.scenarioTemplates[0]??'A neutral environmental scenario is presented.')})))}
function build(slug:GeneratorSlug,input:{seed:string;difficulty:GeneratorDifficulty}):GeneratedQuestion{const random=createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`);const scenario=random.pick(pool(slug,input.difficulty));const entry=scenario.entry;const distractors=selectEnvironmentDistractors(entry.explanation,entry.distractors.map((item)=>environmentDistractor(item.text,item.mistakeType)));const choices=random.shuffle([{text:entry.explanation,isCorrect:true,distractorType:null,mistakeType:null,derivation:null,qualityScore:1,numericValue:environmentStableNumber(entry.explanation)},...distractors.map((item)=>({text:item.text,isCorrect:false,distractorType:item.mistakeType,mistakeType:item.mistakeType,derivation:{operation:item.mistakeType,inputs:[environmentStableNumber(item.text)]},qualityScore:item.qualityScore,numericValue:environmentStableNumber(item.text)}))]);return{generatorSlug:slug,generatorVersion:1,difficulty:input.difficulty,seed:input.seed,prompt:scenario.prompt,parameters:{entryId:entry.id,category:entry.category,domain:entry.domain,lawId:entry.source.lawId,provisionId:entry.source.provisionId,institution:entry.source.institution,source:{...entry.source},scenarioTemplates:[...entry.scenarioTemplates],recomputedCorrect:entry.explanation,scenarioSignature:`${entry.id}|${scenario.variant}`},choices,explanation:{title:'Source-verified environmental-management review',steps:[`The tested area is ${environmentCategoryLabel(entry.category)}.`,entry.explanation,`Authoritative source: ${formatEnvironmentReference(entry.source)}.`,`Misconception rejected: ${entry.misconception}`,'This educational review is not legal, scientific, regulatory, or technical advice or official CSC examination material. Official sources control.'],finalAnswer:entry.explanation},metadata:{answerKind:'text',unit:null,canonicalSignature:`${slug}|${entry.id}|${scenario.variant}`}}}
function validate(question:GeneratedQuestion):GeneratorValidationResult{const id=question.parameters.entryId;const entry=typeof id==='string'?findEnvironmentEntry(id):null;const answer=question.parameters.recomputedCorrect;const source=question.parameters.source as EnvironmentSource|undefined;const choices=question.choices.map((choice)=>choice.text);const value=`${question.prompt} ${choices.join(' ')}`;const valid=entry!==null&&validateEnvironmentEntry(entry).length===0&&typeof answer==='string'&&source!==undefined&&environmentSourceComplete(source)&&JSON.stringify(source)===JSON.stringify(entry.source)&&question.parameters.lawId===entry.source.lawId&&question.parameters.provisionId===entry.source.provisionId&&lawConceptValid(entry)&&environmentDomainValid(entry)&&wasteCategoryConceptValid(entry)&&eiaConceptValid(entry)&&institutionRoleValid(entry)&&mitigationAdaptationValid(entry)&&rejectsCurrentPerson(value)&&rejectsActiveControversy(value)&&scenarioSafe(value)&&rejectsProjectAdvice(value)&&rejectsUnsupportedScientificClaim(value)&&rejectsUnverifiedNumber(value)&&uniqueVisibleChoices(choices)&&uniqueEnvironmentAnswer(choices,answer)&&question.choices.filter((choice)=>choice.isCorrect).length===1&&question.choices.filter((choice)=>!choice.isCorrect).every((choice)=>choice.mistakeType?.startsWith('env_')===true&&choice.derivation!==null)&&question.explanation.steps.some((step)=>step.includes(entry.source.provisionId)&&step.includes(entry.source.institution));return{valid,reason:valid?null:'Environment management validation failed.'}}
const make=(slug:GeneratorSlug):QuestionGenerator=>({slug,version:1,title:slug.replaceAll('-',' '),supportedDifficulties:['easy','medium','hard'],generate:(input)=>build(slug,input),validate})
export const environmentManagementGenerators=slugs.map(make)
