import type { EnvironmentCategory,EnvironmentDomain,EnvironmentEntry,EnvironmentSource } from './environment-management.types'
export function validEnvironmentProvision(value:string):boolean{return /^(?:Article II, Section 16|(?:RA (?:8749|9275|9003|6969|9147|11038|9729)|PD 1586), Section \d+|Official Mandate, [A-Za-z][A-Za-z /&-]+)$/u.test(value)}
export function environmentSourceComplete(source:EnvironmentSource):boolean{return source.sourceTitle.length>0&&/^https:\/\//u.test(source.sourceUrl)&&source.lawId.length>0&&validEnvironmentProvision(source.provisionId)&&source.institution.length>0&&source.verificationDate==='2026-08-04'&&source.contentVersion==='environment-management-v1'&&source.paraphrasedRule.length>0}
const domains:Record<EnvironmentCategory,readonly EnvironmentDomain[]>={rights_sustainability:['constitutional_ecology','sustainability'],air:['air'],water:['water'],solid_waste:['solid_waste'],hazardous:['hazardous_substances'],biodiversity:['biodiversity','protected_areas'],eia:['environmental_assessment'],climate:['climate_change'],institutions:['institutional_responsibility']}
export function environmentDomainValid(entry:EnvironmentEntry):boolean{return domains[entry.category].includes(entry.domain)}
export function wasteCategoryConceptValid(entry:EnvironmentEntry):boolean{return entry.category!=='solid_waste'||(entry.domain==='solid_waste'&&entry.source.lawId==='RA 9003'&&entry.exactTerms.some((term)=>/waste|segregation|recycling|reuse|landfill|dump|recovery/iu.test(term)))}
export function eiaConceptValid(entry:EnvironmentEntry):boolean{return entry.category!=='eia'||(entry.domain==='environmental_assessment'&&entry.source.lawId==='PD 1586'&&entry.exactTerms.some((term)=>/Environmental (?:Impact|Compliance)|critical (?:project|area)|proposed project/iu.test(term)))}
export function rejectsUnsupportedScientificClaim(value:string):boolean{return !/\b(?:guarantees? no environmental harm|one weather event (?:proves|disproves) climate change|every material is recyclable|dilution makes every discharge safe)\b/iu.test(value)}
export function rejectsCurrentPerson(value:string):boolean{return !/\b(incumbent|current officeholder|current candidate|named company|named polluter|pending case|recent controversy)\b/iu.test(value)}
export function rejectsActiveControversy(value:string):boolean{return !/\b(active environmental controversy|ongoing accusation|current enforcement case|partisan climate dispute)\b/iu.test(value)}
export function scenarioSafe(value:string):boolean{return !/\b(mix chemicals|neutralize chemicals|burn hazardous|transport unknown waste|touch unknown substance|enter restricted site|capture wildlife|hide wildlife|evade inspection|(?:should|must) (?:personally |physically )?confront|trespass|bypass permit)\b/iu.test(value)}
export function rejectsProjectAdvice(value:string):boolean{return !/\b(this project is compliant|guaranteed permit|specific permit application|exact engineering design)\b/iu.test(value)}
export function rejectsUnverifiedNumber(value:string):boolean{return !/\b\d+(?:\.\d+)?\s*(?:ppm|mg\/L|micrograms?|tons? per year)\b/iu.test(value)}
export function lawConceptValid(entry:EnvironmentEntry):boolean{const expected:Record<EnvironmentCategory,readonly string[]>={rights_sustainability:['1987 Constitution','RA 9729','RA 9275'],air:['RA 8749'],water:['RA 9275'],solid_waste:['RA 9003'],hazardous:['RA 6969'],biodiversity:['RA 9147','RA 11038'],eia:['PD 1586'],climate:['RA 9729'],institutions:['EO 192','EMB mandate','RA 9729']};return expected[entry.category].includes(entry.source.lawId)}
export function institutionRoleValid(entry:EnvironmentEntry):boolean{return !/\b(?:EMB is a court|Climate Change Commission is a weather bureau|DENR directly sets every local collection schedule|one institution performs every environmental function)\b/iu.test(entry.explanation)}
export function mitigationAdaptationValid(entry:EnvironmentEntry):boolean{return entry.category!=='climate'||(/mitigation/iu.test(entry.explanation)!==/adaptation/iu.test(entry.explanation)||/distinct|both/iu.test(entry.explanation))}
export function uniqueVisibleChoices(choices:readonly string[]):boolean{return choices.length===4&&choices.every((choice)=>choice.trim().length>0)&&new Set(choices.map((choice)=>choice.trim().toLowerCase())).size===4}
export function uniqueEnvironmentAnswer(choices:readonly string[],answer:string):boolean{return choices.filter((choice)=>choice===answer).length===1}
