import { findPronounsModifiersEntry, pronounsModifiersBankV1 } from '../../domain/pronouns-modifiers/pronouns-modifiers-bank'
import { pronounModifierDistractor, selectPronounModifierDistractors } from '../../domain/pronouns-modifiers/pronouns-modifiers-distractors'
import { pronounModifierNumericValue, pronounModifierSkillLabel } from '../../domain/pronouns-modifiers/pronouns-modifiers-format'
import { adjectiveAdverbValid, antecedentRepresented, comparativeFormValid, danglingModifierResolved, modifierTargetValid, misplacedModifierDetected, possessiveFormValid, pronounModifierAnswerMatches, reflexiveAntecedentValid, relativePronounValid, sentenceRevisionValid } from '../../domain/pronouns-modifiers/pronouns-modifiers-rules'
import { uniquePronounModifierAnswer, uniquePronounModifierChoices } from '../../domain/pronouns-modifiers/pronouns-modifiers-validation'
import type { PronounModifierSkill } from '../../domain/pronouns-modifiers/pronouns-modifiers.types'
import { createSeededRandom } from '../generator-random'
import type { GeneratedQuestion, GeneratorDifficulty, GeneratorSlug, GeneratorValidationResult, QuestionGenerator } from '../generator.types'

const slugs = ['pronoun-reference-agreement', 'pronoun-case', 'possessive-reflexive-pronoun', 'relative-pronoun-usage', 'adjective-adverb-modifier', 'comparative-modifier', 'misplaced-modifier', 'dangling-modifier', 'mixed-pronouns-modifiers'] as const satisfies readonly GeneratorSlug[]
const skills = ['reference_agreement', 'case', 'possessive_reflexive', 'relative', 'adjective_adverb', 'comparative', 'misplaced', 'dangling'] as const satisfies readonly PronounModifierSkill[]
const frames = [(template: string) => `Choose the clearest standard-English answer: "${template}"`, (template: string) => `Which option applies the target pronoun or modifier rule? "${template}"`, (template: string, skill: string) => `Apply ${skill}: "${template}"`] as const
function pool(slug: GeneratorSlug, difficulty: GeneratorDifficulty) { const index = slugs.indexOf(slug as (typeof slugs)[number]); const entries = (index === 8 ? pronounsModifiersBankV1 : pronounsModifiersBankV1.filter((entry) => entry.skill === skills[index])).filter((entry) => entry.difficulty === difficulty); return entries.flatMap((entry) => frames.map((frame, variant) => ({ entry, variant, prompt: frame(entry.sentenceTemplate, pronounModifierSkillLabel(entry.skill)) }))) }
function build(slug: GeneratorSlug, input: { seed: string; difficulty: GeneratorDifficulty }): GeneratedQuestion { const random = createSeededRandom(`${input.seed}|${slug}|1|${input.difficulty}`); const scenario = random.pick(pool(slug, input.difficulty)); const entry = scenario.entry; const distractors = selectPronounModifierDistractors(entry.correctChoice, entry.distractors.map((item) => pronounModifierDistractor(item.text, item.mistakeType))); const choices = random.shuffle([{ text: entry.correctChoice, isCorrect: true, distractorType: null, mistakeType: null, derivation: null, qualityScore: 1, numericValue: pronounModifierNumericValue(entry.correctChoice) }, ...distractors.map((item) => ({ text: item.text, isCorrect: false, distractorType: item.mistakeType, mistakeType: item.mistakeType, derivation: { operation: item.mistakeType, inputs: [pronounModifierNumericValue(item.text)] }, qualityScore: item.qualityScore, numericValue: pronounModifierNumericValue(item.text) }))]); return { generatorSlug: slug, generatorVersion: 1, difficulty: input.difficulty, seed: input.seed, prompt: scenario.prompt, parameters: { entryId: entry.id, skill: entry.skill, antecedent: entry.antecedent, modifiedTarget: entry.modifiedTarget, recomputedCorrect: entry.correctChoice, scenarioSignature: `${entry.id}|${scenario.variant}` }, choices, explanation: { title: 'Pronouns and Modifiers solution', steps: [`The primary rule is ${pronounModifierSkillLabel(entry.skill)}.`, entry.ruleDetail, entry.antecedent === null ? `The modified target is "${entry.modifiedTarget}."` : `The antecedent is "${entry.antecedent}."`, entry.explanationRationale, `The correct sentence is: "${entry.completedSentence}"`], finalAnswer: entry.correctChoice }, metadata: { answerKind: 'text', unit: null, canonicalSignature: `${slug}|${entry.id}|${scenario.variant}` } } }
function validate(question: GeneratedQuestion): GeneratorValidationResult { const id = question.parameters.entryId; const answer = question.parameters.recomputedCorrect; const entry = typeof id === 'string' ? findPronounsModifiersEntry(id) : null; const choices = question.choices.map((choice) => choice.text); const valid = entry !== null && typeof answer === 'string' && answer === entry.correctChoice && antecedentRepresented(entry) && possessiveFormValid(entry) && reflexiveAntecedentValid(entry) && relativePronounValid(entry) && adjectiveAdverbValid(entry) && modifierTargetValid(entry) && comparativeFormValid(entry) && misplacedModifierDetected(entry) && danglingModifierResolved(entry) && sentenceRevisionValid(entry) && pronounModifierAnswerMatches(entry, answer) && uniquePronounModifierChoices(choices) && uniquePronounModifierAnswer(choices, answer) && question.choices.filter((choice) => choice.isCorrect).length === 1 && question.choices.filter((choice) => !choice.isCorrect).every((choice) => choice.mistakeType?.startsWith('pronoun_') === true && choice.derivation !== null); return { valid, reason: valid ? null : 'Pronoun and modifier validation failed.' } }
const make = (slug: GeneratorSlug): QuestionGenerator => ({ slug, version: 1, title: slug.replaceAll('-', ' '), supportedDifficulties: ['easy', 'medium', 'hard'], generate: (input) => build(slug, input), validate })
export const pronounsModifiersGenerators = slugs.map(make)
