import type{ContextClueEntry}from'./context-clues.types'
export const contextCluesBankV1=[
{target:'dim',senseId:'low-light',meaning:'having very little light',partOfSpeech:'adjective',clueType:'definition',signal:'meaning',text:'The archive room was dim, meaning it had very little light.',support:'had very little light',alternateSenses:['uncertain','not intelligent'],difficulty:'easy',grammarFrame:'The room was TARGET.'},
{target:'diligent',senseId:'careful-work',meaning:'careful and hardworking',partOfSpeech:'adjective',clueType:'synonym',signal:'or',text:'The clerk was diligent, or very careful and hardworking.',support:'very careful and hardworking',alternateSenses:['quick','strict'],difficulty:'easy',grammarFrame:'The clerk was TARGET.'},
{target:'tranquil',senseId:'quiet-calm',meaning:'quiet and calm',partOfSpeech:'adjective',clueType:'contrast',signal:'unlike',text:'Unlike the noisy lobby, the archive room was tranquil.',support:'Unlike the noisy lobby',alternateSenses:['empty','dark'],difficulty:'easy',grammarFrame:'The room was TARGET.'},
{target:'beverages',senseId:'drinks',meaning:'drinks',partOfSpeech:'noun',clueType:'example',signal:'including',text:'Several beverages, including water, juice, and coffee, were served.',support:'water, juice, and coffee',alternateSenses:['containers','supplies'],difficulty:'easy',grammarFrame:'Several TARGET were served.'},
{target:'fragile',senseId:'breakable',meaning:'easily broken',partOfSpeech:'adjective',clueType:'cause_effect',signal:'therefore',text:'The box was fragile; therefore, it was handled with great care.',support:'handled with great care',alternateSenses:['heavy','valuable'],difficulty:'easy',grammarFrame:'The box was TARGET.'},
{target:'exhausted',senseId:'very-tired',meaning:'extremely tired',partOfSpeech:'adjective',clueType:'general_sense',signal:null,text:'After working for twelve hours without rest, the staff felt exhausted.',support:'twelve hours without rest',alternateSenses:['confused','busy'],difficulty:'medium',grammarFrame:'The staff felt TARGET.'},
{target:'file',senseId:'submit-v',meaning:'officially submit',partOfSpeech:'verb',clueType:'multiple_meaning',signal:null,text:'Please file the completed request before Friday.',support:'completed request before Friday',alternateSenses:['folder of records','metal smoothing tool'],difficulty:'medium',grammarFrame:'Please TARGET the request.'},
{target:'obsolete',senseId:'outdated',meaning:'no longer useful because something newer replaced it',partOfSpeech:'adjective',clueType:'two_sentence',signal:null,text:'The records were obsolete. They were no longer useful because a newer system had replaced them.',support:'no longer useful because a newer system had replaced them',alternateSenses:['damaged','confidential'],difficulty:'hard',grammarFrame:'The records were TARGET.'}
]as const satisfies readonly ContextClueEntry[]

