import type { SentenceStructureEntry, SentenceType } from './sentence-structure.types'

export function normalizeStructureText(value: string): string { return value.trim().toLowerCase().replaceAll(/\s+/gu, ' ') }
export function clauseMetadataValid(entry: SentenceStructureEntry): boolean { return entry.clauses.every((clause) => clause.text.length > 2 && clause.subject.length > 0 && clause.verb.length > 0) }
export function classifySentenceType(entry: Pick<SentenceStructureEntry, 'clauses' | 'errorType'>): SentenceType { if (entry.errorType === 'fragment') return 'fragment'; if (entry.errorType === 'fused_sentence' || entry.errorType === 'comma_splice') return 'run_on'; const independent = entry.clauses.filter((item) => item.kind === 'independent').length; const dependent = entry.clauses.filter((item) => item.kind === 'dependent').length; if (independent >= 2 && dependent >= 1) return 'compound_complex'; if (independent >= 2) return 'compound'; if (independent === 1 && dependent >= 1) return 'complex'; return 'simple' }
export function fragmentDetected(entry: SentenceStructureEntry): boolean { const independent = entry.clauses.some((item) => item.kind === 'independent'); return entry.errorType === 'fragment' && (!independent || entry.subject === null || entry.predicate === null) }
export function runOnDetected(entry: SentenceStructureEntry): boolean { return entry.errorType === 'fused_sentence' && entry.clauses.filter((item) => item.kind === 'independent').length === 2 && entry.connector === null }
export function commaSpliceDetected(entry: SentenceStructureEntry): boolean { return entry.errorType === 'comma_splice' && entry.clauses.filter((item) => item.kind === 'independent').length === 2 && entry.connector === ',' }
export function connectorLogicValid(entry: SentenceStructureEntry): boolean { if (!['coordination', 'run_on'].includes(entry.skill)) return true; if (entry.errorType === 'faulty_coordination' || entry.errorType === 'faulty_subordination') return entry.connector !== null && entry.correctedVersion !== entry.sentence; return entry.errorType === 'none' || runOnDetected(entry) || commaSpliceDetected(entry) }
export function parallelFormValid(entry: SentenceStructureEntry): boolean { return entry.skill !== 'parallel' || entry.parallelForms.length >= 2 && entry.correctedVersion !== entry.sentence && entry.errorType === 'nonparallel' }
export function logicalComparisonValid(entry: SentenceStructureEntry): boolean { return entry.errorType !== 'illogical_comparison' || entry.comparisonItems !== null && entry.comparisonItems[0] !== entry.comparisonItems[1] && /that of|those of/iu.test(entry.correctedVersion) }
export function segmentedErrorValid(entry: SentenceStructureEntry): boolean { if (entry.skill !== 'segmented_error') return true; if (entry.segments.length !== 4 || new Set(entry.segments.map((item) => item.label)).size !== 4) return false; const errors = entry.segments.filter((item) => item.hasError); return entry.noError ? errors.length === 0 && entry.errorType === 'none' && entry.correctChoice === 'No error' : errors.length === 1 && entry.errorLocation === errors[0]?.label && entry.correctChoice === errors[0]?.label }
export function structureAnswerMatches(entry: SentenceStructureEntry, answer: string): boolean { return normalizeStructureText(answer) === normalizeStructureText(entry.correctChoice) }
